/**
 * GENERATED by scripts/generate-production-workbook-source.mjs — do not edit.
 *
 * Every populated row of "Content Development Checklists.xlsx", visible and
 * hidden, as recorded on generation. The workflow templates in
 * workflowTemplates.js cite these rows by sheet and row number, and
 * server/learningProduction.templates.test.js fails if any populated row is
 * neither used by a template nor explicitly classified in traceability.js.
 *
 * Source checksum (sha256): d11cb736a00bf578f96dd647682f22f7045b3499753351b3fe387ce34ccbe3c2
 */

export const WORKBOOK_CHECKSUM = "d11cb736a00bf578f96dd647682f22f7045b3499753351b3fe387ce34ccbe3c2";

/** The master sheet: one entry per populated cell pair in each of the three paths. */
export const MASTER_SHEET = "Content Development Activities";

export const MASTER_ACTIVITIES = [
  {
    "path": "NEW_PROGRAM",
    "row": 1,
    "cells": "A1:B1",
    "activityId": "Activity ID",
    "label": "New Program Activities",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 1,
    "cells": "D1:E1",
    "activityId": "Old Programs Activities",
    "label": "Old Programs Activities",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 1,
    "cells": "G1:H1",
    "activityId": "New Programs Activities by AI ",
    "label": "New Programs Activities by AI ",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 2,
    "cells": "A2:B2",
    "activityId": "new_res_1",
    "label": "Research",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 2,
    "cells": "D2:E2",
    "activityId": "Activity ID",
    "label": "Revamping",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 2,
    "cells": "G2:H2",
    "activityId": "Activity ID",
    "label": null,
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 3,
    "cells": "A3:B3",
    "activityId": "new_curr_draft_2",
    "label": "1st Draft Curriculum Development",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 3,
    "cells": "D3:E3",
    "activityId": "rev_id_1",
    "label": "Instruction Designing",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 3,
    "cells": "G3:H3",
    "activityId": "new_res_1",
    "label": "New content ",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 4,
    "cells": "A4:B4",
    "activityId": "new_exp_3",
    "label": "Experts and Coaches Acquisition ",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 4,
    "cells": "D4:E4",
    "activityId": "rev_media_2",
    "label": "Media Production",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 4,
    "cells": "G4:H4",
    "activityId": "new_curr_draft_2",
    "label": "Outlines",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 5,
    "cells": "A5:B5",
    "activityId": "new_curr_final_4",
    "label": "Final Curriculum Details",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 5,
    "cells": "D5:E5",
    "activityId": "rev_deploy_3",
    "label": "Platform Deployment",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 5,
    "cells": "G5:H5",
    "activityId": "new_exp_3",
    "label": "Review(Outlines)",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 6,
    "cells": "A6:B6",
    "activityId": "new_id_5",
    "label": "Instructional Designing",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 6,
    "cells": "D6:E6",
    "activityId": "rev_first_run_4",
    "label": "First Internal Dry Run",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 6,
    "cells": "G6:H6",
    "activityId": "new_curr_final_4",
    "label": "Final Curriculum Details",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 7,
    "cells": "A7:B7",
    "activityId": "new_media_6",
    "label": "Media Production",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 7,
    "cells": "D7:E7",
    "activityId": "rev_change_5",
    "label": "Applying Changes if Any",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 7,
    "cells": "G7:H7",
    "activityId": "new_id_5",
    "label": "Scripts",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 8,
    "cells": "A8:B8",
    "activityId": "new_deploy_7",
    "label": "Platform Deployment",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 8,
    "cells": "D8:E8",
    "activityId": "rev_change_deploy_6",
    "label": "Applying Dry Run Comments",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 8,
    "cells": "G8:H8",
    "activityId": "new_exp_6",
    "label": "Review(Scripts) if any ",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 9,
    "cells": "A9:B9",
    "activityId": "new_first_run_8",
    "label": "1st Draft Curriculum",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 9,
    "cells": "D9:E9",
    "activityId": "rev_second_run_7",
    "label": "Second Internal Dry Run",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 9,
    "cells": "G9:H9",
    "activityId": "new_id_7",
    "label": "Slides by docki",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 10,
    "cells": "A10:B10",
    "activityId": "new_change_9",
    "label": "Applying Dry Run Comments",
    "hidden": false
  },
  {
    "path": "REVAMP",
    "row": 10,
    "cells": "D10:E10",
    "activityId": "rev_uat_8",
    "label": "User Acceptance Test",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 10,
    "cells": "G10:H10",
    "activityId": "new_media_8",
    "label": "Vo generation \nThink (Slides+ Vo)",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 11,
    "cells": "A11:B11",
    "activityId": "new_change_deploy_10",
    "label": "Platform Deployment After Changing",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 11,
    "cells": "G11:H11",
    "activityId": "new_id_9",
    "label": "Review all videos and write all comments ",
    "hidden": false
  },
  {
    "path": "NEW_PROGRAM",
    "row": 12,
    "cells": "A12:B12",
    "activityId": "new_uat_11",
    "label": "User Acceptance Test\n(UAT) is the final phase of software development where actual end users test a system in real-world scenarios to confirm it meets business requirements before release",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 12,
    "cells": "G12:H12",
    "activityId": "new_media_9",
    "label": "implement all comments",
    "hidden": false
  },
  {
    "path": "AI_NEW_PROGRAM",
    "row": 13,
    "cells": "G13:H13",
    "activityId": "new_id_10",
    "label": "Check all comments ",
    "hidden": false
  }
];

/** The detail sheets, in workbook order. */
export const DETAIL_SHEETS = [
  {
    "name": "Research",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_res_1",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Program Defining",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Define Field",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Define Target Audience",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Define Learning Outcomes",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Define Program/Journey Duration",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "ITEM",
        "text": "Define the weekly workload",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "HEADING",
        "text": "Documentation",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Create a Document to document Research Activity outcomes ",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "HEADING",
        "text": "Identify Competitors",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "ITEM",
        "text": "List potential competitors offering similar program",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "HEADING",
        "text": "Competitor Analysis",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "HEADING",
        "text": "Website Review",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "ITEM",
        "text": "Visit each competitor's website",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Note their course offerings, structure, pricing, and target audience",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "ITEM",
        "text": "Look for customer testimonials or reviews",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 18,
        "kind": "HEADING",
        "text": "Program Content Analysis",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "ITEM",
        "text": "Evaluate the topics covered in their courses",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "ITEM",
        "text": "Compare depth, breadth, and uniqueness of content",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 21,
        "kind": "HEADING",
        "text": "Learning Experience",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 22,
        "kind": "ITEM",
        "text": "Check what learning platforms or tools they use",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Evaluate user experience and interface",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 24,
        "kind": "HEADING",
        "text": "Identify Content Outlines",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "ITEM",
        "text": "Identify the main journey programs",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Identify the main program modules",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 27,
        "kind": "ITEM",
        "text": "Identify tools to be used during the program",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Pass these data to ID to craft a roadmap for your learners",
        "hidden": false,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "1st Draft Curriculum",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_curr_draft_2",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Create Draft Structure",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Get the Finalized Research Document",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Create a Document for the Journey/Program",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Name the Document \"Program Name Curriculum\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Create Program Title Page",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "ITEM",
        "text": "Create Table of Contents Page",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "ITEM",
        "text": "Create Relevant \"Introduction\" Section",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Create \"Learning Objectives\" Section (Attitude, Skills, and Knowledge)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "ITEM",
        "text": "Create \"Pre-requisites\" Section",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "ITEM",
        "text": "Create \"About the Journey\" Section (Target Audiance, Age Group, Duration (Hrs), Tasks, Projects, Weeks, Impact, and Language)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "ITEM",
        "text": "Create Section per Program (Program Numbering Starts From 1)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "ITEM",
        "text": "Create Section per Module (Module Numbering Starts From 1)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "ITEM",
        "text": "Create Module \"Introduction\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Create Module \"Learning Objectives\" (Components of Learninf Objectives {Action Verb, Conditions, and Criteria})",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "ITEM",
        "text": "Create Module Contents Table (Topics and Learning Outcomes/tpoic) (Components of Learning Outcomes {Cognitive, Psychomotor, Affective})",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 18,
        "kind": "ITEM",
        "text": "Create \"Tools\" Section",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "HEADING",
        "text": "Filling The Draft",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "ITEM",
        "text": "Write a Title \"Program Name Curriculum\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 21,
        "kind": "ITEM",
        "text": "Write Program introduction (You may use your own introduction according to your knowledge and enhance it using GPT, but remember that GPT can make some mistakes)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 22,
        "kind": "ITEM",
        "text": "Write Program Learning Objectives",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Write Program Pre-requisits",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 24,
        "kind": "ITEM",
        "text": "Write About the Journy points",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "ITEM",
        "text": "Write all Modules Introductions, all are paragraphs starting with \"In this module, learners will ......\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Write all Modules Learning Objectives, all are arrow bullet points starting with \"By the end of this module, learners will be able to:\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 27,
        "kind": "ITEM",
        "text": "Write all Modules topics, all must be short and descriptive names",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Write all topics Learning Outcomes, all are arrow bullet points",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 29,
        "kind": "HEADING",
        "text": "Fonts to be used",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 30,
        "kind": "ITEM",
        "text": "Use Heading 1 Bold Open Sans 20 for (Table of Contents, Introduction, Program Name, and Tools) Headers",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 31,
        "kind": "ITEM",
        "text": "Use Heading 2 Normal Open Sans 18 for (Program Learning Objectives, Pre-requisits, About the Journey, and Module Names) Headers",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 32,
        "kind": "ITEM",
        "text": "Use Normal Bold Open Sans 14 for (module introduction, module learning objectives, and module content) Lables",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 33,
        "kind": "ITEM",
        "text": "Use Normal Bold Open Sans 11 for\n(Attitude, Skills, Knowledge, Target Audiance, Age Group, Duration (Hrs), Tasks, Projects, Weeks, Impact, Language, Topics, and module learning outcomes) Lables and Topics",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 34,
        "kind": "ITEM",
        "text": "Use Normal Open Sans 11 for (Paragraphs, and bullet points)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 35,
        "kind": "HEADING",
        "text": "ID Review",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 36,
        "kind": "ITEM",
        "text": "Check Document Structure",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 37,
        "kind": "ITEM",
        "text": "Check Content from learning experience view",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 38,
        "kind": "ITEM",
        "text": "Check Fonts",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 39,
        "kind": "ITEM",
        "text": "Documenting Comments",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 40,
        "kind": "HEADING",
        "text": "Applying Changes",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 41,
        "kind": "ITEM",
        "text": "Apply all Changes requested from the ID",
        "hidden": false,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "Experts and Coaches Acquisition",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_exp_3",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Research",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Get the Finalized Research Document",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Use LinkedIn Search",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Use Appllo.io",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "HEADING",
        "text": "Contacting",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "ITEM",
        "text": "Send Message Requesting for a Meeting/Call and ask for the C.V, describing the type of cooperation",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "ITEM",
        "text": "Reply to the accepting candidates with a scheduled meeting/call + filling become an expert form",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Conduct 15 minutes call to assess\n- Candidate Relevant Experience\n- Candidate Teaching Experience\n- Candidate English",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "HEADING",
        "text": "Technical Discussion",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "ITEM",
        "text": "Review Arabic and English Script Video ( for all candidates )",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "ITEM",
        "text": "Review Technical Arabic and English Sample ( for below 7 years)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "HEADING",
        "text": "Technical Discussion",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "ITEM",
        "text": "Call Passed Candidates and arrange technical discussion meeting",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Following-up on the candidate to deliver the Teaching video Sample before the discussion",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "ITEM",
        "text": "Conduct 1 hour technical discussion to assess candidate technicality and professiency",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 18,
        "kind": "ITEM",
        "text": "Send Email to candidates to appreciate their time and let them know when they are expecting our answer",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "ITEM",
        "text": "Follow-up on the non-responding candidates",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "HEADING",
        "text": "Onboarding",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 21,
        "kind": "ITEM",
        "text": "Call the passed candidates and send them onbording email contains welcome onboard form",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 22,
        "kind": "ITEM",
        "text": "Arrange 1 hour meeting with the Tech. PM and Delivery PM to propose the curriculum and scope of work",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Arrange schedule weekly follow-up meetings",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 24,
        "kind": "ITEM",
        "text": "Send Calender invitations with all required milestones",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "HEADING",
        "text": "Contracting",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Send an Email with a Signed Version of Agreement and SOW",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 27,
        "kind": "ITEM",
        "text": "Negotiation Round if needed",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Send an Email with a Signed Version of Agreement and SOW after negotiation",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 29,
        "kind": "ITEM",
        "text": "Following-up on the candidate to sign the contract before starting any further activities",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 30,
        "kind": "HEADING",
        "text": "Expert Performance Tracking",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 31,
        "kind": "ITEM",
        "text": "Arrange meeting with ID team (ToT)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 32,
        "kind": "ITEM",
        "text": "Track Expert Shooting Performance",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 33,
        "kind": "ITEM",
        "text": "Track Expert Commitment",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 34,
        "kind": "ITEM",
        "text": "Track Expert Live Delivery",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 35,
        "kind": "ITEM",
        "text": "Track Coaches Commitment",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 36,
        "kind": "ITEM",
        "text": "Track Coaches Performance",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 37,
        "kind": "HEADING",
        "text": "Experts Community Engaging",
        "hidden": false,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "Final Curriculum Details",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_curr_final_4",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Creating Final Journey Document",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Send the 1st Curriculum Draft Document to the Expert",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Schedule a meeting to discuss the suggested modifications",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Document all suggestions and jsutifications",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Send the suggeted modifications to the  consultant",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "ITEM",
        "text": "Create Final Curriculum Document",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "ITEM",
        "text": "Apply the suggested modifications to the document after Consultant Approval",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Send to the ID team for leaning experience approval",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "ITEM",
        "text": "Send to the Consultant for review",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "ITEM",
        "text": "Gather feedback from the Consultant",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "HEADING",
        "text": "Creating Presentations",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "ITEM",
        "text": "Create a new \"Program Name Presentations - Developing\"",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "ITEM",
        "text": "Validate that all delivered presentations are alligned with the final detailed curriculum document (Modules, Topics, and Subtopics)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Send the presentations to the Consultant for technical review",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "HEADING",
        "text": "Creating Knowledge Check Points (MCQs)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "HEADING",
        "text": "Creating Tasks",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "HEADING",
        "text": "Creating Projects",
        "hidden": false,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "Instruction Designing",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_id_5",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "rev_id_1",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 17,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Recieve Presentations From Tech. PM",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 27,
        "kind": "ITEM",
        "text": "Research",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Compare slides against the curriculum/topic",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 29,
        "kind": "ITEM",
        "text": "Check slide notes",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 30,
        "kind": "ITEM",
        "text": "Apply Fonts and sizes",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 31,
        "kind": "ITEM",
        "text": "Check/Create Main title",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 32,
        "kind": "ITEM",
        "text": "Check/Create Outlines",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 33,
        "kind": "ITEM",
        "text": "Check visuals (icons, infographs, etc..)",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 34,
        "kind": "ITEM",
        "text": "Check links (compitator refering, illigal downloads, cracks)",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 35,
        "kind": "ITEM",
        "text": "Feedback send to Tech. PM",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 36,
        "kind": "ITEM",
        "text": "Resend to tech PM for expert final review",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 37,
        "kind": "ITEM",
        "text": "Working on the changes",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "Media Production",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_media_6",
        "hidden": false,
        "outlineLevel": 0,
        "extraCells": [
          {
            "address": "D1",
            "value": "Activity ID"
          },
          {
            "address": "E1",
            "value": "upg_media_6"
          }
        ]
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 0,
        "extraCells": [
          {
            "address": "D2",
            "value": "Checklist"
          },
          {
            "address": "E2",
            "value": "Checklist"
          }
        ]
      }
    ]
  },
  {
    "name": "Platform Deployment",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_deploy_7",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Content Team Internal Dry Run",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Review All videos will be uploaded on the platform",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Review Knowledge Checks (MCQs) that will be added on the platform",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Review all tasks",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Review all projects",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "HEADING",
        "text": "Creating Visuals",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "ITEM",
        "text": "Send a request to the marketting team to create a cover page and thumbnail for the program",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Follow-up to recieve them",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "HEADING",
        "text": "Content Team Internal Dry Run",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "ITEM",
        "text": "Review All videos will be uploaded on the platform",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "ITEM",
        "text": "Review Knowledge Checks (MCQs) that will be added on the platform",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "ITEM",
        "text": "Review all tasks",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Review all projects",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "HEADING",
        "text": "Clone",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 18,
        "kind": "ITEM",
        "text": "Clone the parent program from the latest release",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "ITEM",
        "text": "Clone the child program from the latest release",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "ITEM",
        "text": "Name the Program \"Program Name rx.y.z\" where x, y, and z are numbers describe the new release version",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 21,
        "kind": "HEADING",
        "text": "Creating Visuals (if needed)",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 22,
        "kind": "ITEM",
        "text": "Send a request to the marketting team to create a cover page and thumbnail for the program",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Follow-up to recieve them",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 24,
        "kind": "ITEM",
        "text": "Create a folder inside the main program folder and add the cover photo and thumbnail",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "HEADING",
        "text": "Send Data to Lerning Operations",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Send New Curriculum Document to the learning operations team Higliting the changes to be done:\n1. (Intro, Learning objectives, About the program, ..etc)\n2. Skeleton for the program including modules, topics and subtopics",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 27,
        "kind": "ITEM",
        "text": "Send the new visuals if any",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Send the final edited videos to upload",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 29,
        "kind": "ITEM",
        "text": "Send the final knowledge checks to add",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 30,
        "kind": "ITEM",
        "text": "Send Calender delivery event",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 31,
        "kind": "HEADING",
        "text": "Modifying Codelabs, Tasks and Projects (if needed)",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 32,
        "kind": "ITEM",
        "text": "Adding Codelabs",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 33,
        "kind": "ITEM",
        "text": "Modifying tasks",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 34,
        "kind": "ITEM",
        "text": "Modifying Projects",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 35,
        "kind": "HEADING",
        "text": "Clonning",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 36,
        "kind": "ITEM",
        "text": "Add program link on the platforn to the versioning sheet and mark as the current release",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 37,
        "kind": "ITEM",
        "text": "Clone when delivering to the learners",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 38,
        "kind": "ITEM",
        "text": "This release version should not have learners inside",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 39,
        "kind": "ITEM",
        "text": "All internal stakeholders should be enrolled before the dry run",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 40,
        "kind": "HEADING",
        "text": "Schedule Internal Dry Run",
        "hidden": true,
        "outlineLevel": 1
      },
      {
        "row": 41,
        "kind": "ITEM",
        "text": "Schedule a meeting for internal dry run involving Content Team, Learning Ops, Delivery Team, ID team, and Tech Consultant Team SPOCs",
        "checkboxCell": true,
        "hidden": true,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "First Dry Run",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_first_run_8 ",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "Stop Activities",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 4,
        "kind": "ITEM",
        "text": "Stop any program activities made on the platform",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Stop any Platform Live Changes or modifications",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 6,
        "kind": "HEADING",
        "text": "Review Program Landing Page",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Get the program link to be delivered to the learners",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 8,
        "kind": "ITEM",
        "text": "Review Program title",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 9,
        "kind": "ITEM",
        "text": "Review Program Cover Page",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Review Program Thumbnail",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 11,
        "kind": "ITEM",
        "text": "Review Program What you will learn",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 12,
        "kind": "ITEM",
        "text": "Review Program / Journey Description",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 13,
        "kind": "ITEM",
        "text": "Review Program Requirements / Prerequsits",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 14,
        "kind": "ITEM",
        "text": "Review Program Specifications",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 15,
        "kind": "HEADING",
        "text": "Review Program Content",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Check Program Modules ( names and order ) against program playbook",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 17,
        "kind": "ITEM",
        "text": "Check Topics ( Names and order ) against program playbook",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 18,
        "kind": "ITEM",
        "text": "Check Videos( Names, order, relevancy, and functionality ) against program playbook",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 19,
        "kind": "ITEM",
        "text": "Check program materials",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 20,
        "kind": "ITEM",
        "text": "Check program resources - downloadable sw, packages, etc...",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 21,
        "kind": "ITEM",
        "text": "Check tasks ( Names, Content (according to tasks creation template), Deliverables, order, submission, scoring checklist from admin panel, passing scores from admin panel)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Check projects ( Names, Content (according to tasks creation template), Deliverables, order, submission, scoring checklist from admin panel, passing scores from admin panel)",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 24,
        "kind": "HEADING",
        "text": "Documentation and Reporting",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 25,
        "kind": "ITEM",
        "text": "Document all issues appeared",
        "hidden": false,
        "outlineLevel": 1
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Send Documented issues to responsible team to act on (Operations, Content, Product)",
        "hidden": false,
        "outlineLevel": 1
      }
    ]
  },
  {
    "name": "Platform Deployment After Chang",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_res_1",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 0,
        "extraCells": [
          {
            "address": "E2",
            "value": null
          }
        ]
      }
    ]
  },
  {
    "name": "User Acceptance Test",
    "state": "visible",
    "rows": [
      {
        "row": 1,
        "kind": "META",
        "text": "Activity ID",
        "activityId": "new_res_1",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 2,
        "kind": "HEADER",
        "text": "Checklist",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 3,
        "kind": "HEADING",
        "text": "UAT Preparation",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 4,
        "kind": "HEADING",
        "text": "Identify UAT Testers",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 5,
        "kind": "ITEM",
        "text": "Select a diverse group of testers representing the target audience",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 6,
        "kind": "ITEM",
        "text": "Ensure availability of testers during UAT period",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 7,
        "kind": "ITEM",
        "text": "Prepare Test Scenarios",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 8,
        "kind": "HEADING",
        "text": "During UAT",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 9,
        "kind": "HEADING",
        "text": "Program Navigation",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 10,
        "kind": "ITEM",
        "text": "Can users easily navigate through the course materials?",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 11,
        "kind": "ITEM",
        "text": "Are menus, buttons, and links functioning correctly?",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 12,
        "kind": "HEADING",
        "text": "Content Accuracy",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 13,
        "kind": "ITEM",
        "text": "Are the training materials accurate and up-to-date?",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 14,
        "kind": "ITEM",
        "text": "Verify correctness of facts, figures, and procedures",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 15,
        "kind": "HEADING",
        "text": "Learning Objectives",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 16,
        "kind": "ITEM",
        "text": "Do the activities and exercises align with the learning objectives?",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 17,
        "kind": "ITEM",
        "text": "Are the objectives clear and achievable?",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 18,
        "kind": "HEADING",
        "text": "Interactivity",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 19,
        "kind": "ITEM",
        "text": "Test interactive elements (quizzes, simulations, etc.)",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 20,
        "kind": "ITEM",
        "text": "Verify if interactions work as intended",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 21,
        "kind": "HEADING",
        "text": "Compatibility",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 22,
        "kind": "ITEM",
        "text": "Test compatibility with different browsers (Chrome, Firefox, Safari, etc.)",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 23,
        "kind": "ITEM",
        "text": "Verify compatibility with various devices (desktop, tablet, mobile)",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 24,
        "kind": "HEADING",
        "text": "Accessibility",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 25,
        "kind": "ITEM",
        "text": "Ensure accessibility features (screen readers, keyboard navigation, etc.) work",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 26,
        "kind": "ITEM",
        "text": "Check for color contrast, font sizes, and other accessibility considerations",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 27,
        "kind": "HEADING",
        "text": "Multimedia",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 28,
        "kind": "ITEM",
        "text": "Test audio and video elements for clarity and functionality",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 29,
        "kind": "ITEM",
        "text": "Check for subtitles/captions in videos if applicable",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 30,
        "kind": "HEADING",
        "text": "Tasks and Projects Evaluations",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 31,
        "kind": "ITEM",
        "text": "Evaluate tasks and projects for accuracy and relevance",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 32,
        "kind": "ITEM",
        "text": "Verify grading and feedback mechanisms",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 33,
        "kind": "HEADING",
        "text": "Progress Tracking",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 34,
        "kind": "ITEM",
        "text": "Confirm that progress tracking features are working",
        "hidden": false,
        "outlineLevel": 0
      },
      {
        "row": 35,
        "kind": "ITEM",
        "text": "Check if completion status updates correctly",
        "hidden": false,
        "outlineLevel": 0
      }
    ]
  }
];

/** One detail row by sheet name and row number, or null. */
export function workbookRow(sheet, row) {
  return DETAIL_SHEETS.find((entry) => entry.name === sheet)?.rows.find((entry) => entry.row === row) ?? null;
}
