/**
 * The production module keeps its copy close to its feature code.  The
 * workspace dictionary is intentionally not coupled to this large surface;
 * the small exact table below covers user-facing sentences and the fallback
 * turns enum/dynamic keys into readable labels instead of exposing `lp.*`.
 */

type Pair = { ar: string; en: string };

export const LP_STRINGS: Record<string, Pair> = {
  'lp.module': { ar: 'إنتاج المحتوى التعليمي', en: 'E-Learning Production' },
  'lp.nav.dashboard': { ar: 'لوحة الإنتاج', en: 'Dashboard' },
  'lp.nav.courses': { ar: 'الكورسات', en: 'Courses' },
  'lp.nav.myWork': { ar: 'شغلي', en: 'My Work' },
  'lp.nav.reviews': { ar: 'المراجعات', en: 'Reviews' },
  'lp.nav.reports': { ar: 'التقارير', en: 'Reports' },
  'lp.sidebar.recentCourses': { ar: 'كورسات مفتوحة مؤخرًا', en: 'Recent courses' },
  'lp.sidebar.menu': { ar: 'فتح قائمة الإنتاج', en: 'Open production menu' },
  'lp.sidebar.close': { ar: 'إغلاق القائمة', en: 'Close menu' },

  // Bare enum labels for every status/stage/priority/health/role chip in the
  // module (StatusBadge, StageLabel, PriorityChip, health chips, Team roles).
  // Without an exact entry here, the humanize() fallback in this file joins
  // the key's own segments with " · " — so `lp.status.APPROVED` rendered as
  // "Status · Approved" everywhere instead of just "Approved", on every page.
  'lp.status.NOT_STARTED': { ar: 'لم يبدأ', en: 'Not started' },
  'lp.status.ASSIGNED': { ar: 'مُسند', en: 'Assigned' },
  'lp.status.IN_PROGRESS': { ar: 'قيد التنفيذ', en: 'In progress' },
  'lp.status.SUBMITTED': { ar: 'مُرسل للمراجعة', en: 'Submitted' },
  'lp.status.UNDER_REVIEW': { ar: 'قيد المراجعة', en: 'Under review' },
  'lp.status.CHANGES_REQUESTED': { ar: 'مطلوب تعديل', en: 'Changes requested' },
  'lp.status.RESUBMITTED': { ar: 'أُعيد إرساله', en: 'Resubmitted' },
  'lp.status.APPROVED': { ar: 'معتمد', en: 'Approved' },
  'lp.status.LOCKED': { ar: 'مقفل', en: 'Locked' },
  'lp.stage.OUTLINE': { ar: 'المخطط', en: 'Outline' },
  'lp.stage.PPT': { ar: 'العرض التقديمي', en: 'PPT' },
  'lp.stage.SCRIPT': { ar: 'السكريبت', en: 'Script' },
  'lp.stage.VOICE_OVER': { ar: 'التعليق الصوتي', en: 'Voice Over' },
  'lp.stage.VIDEO': { ar: 'الفيديو', en: 'Video' },
  'lp.priority.LOW': { ar: 'منخفضة', en: 'Low' },
  'lp.priority.NORMAL': { ar: 'عادية', en: 'Normal' },
  'lp.priority.HIGH': { ar: 'عالية', en: 'High' },
  'lp.priority.URGENT': { ar: 'عاجلة', en: 'Urgent' },
  'lp.health.ON_TRACK': { ar: 'في المسار الصحيح', en: 'On track' },
  'lp.health.AT_RISK': { ar: 'في خطر', en: 'At risk' },
  'lp.health.DELAYED': { ar: 'متأخر', en: 'Delayed' },
  'lp.health.COMPLETED': { ar: 'مكتمل', en: 'Completed' },
  'lp.role.PRODUCTION_MANAGER': { ar: 'مدير الإنتاج', en: 'Production Manager' },
  'lp.role.COURSE_MANAGER': { ar: 'مدير الكورس', en: 'Course Manager' },
  'lp.role.SUBJECT_MATTER_EXPERT': { ar: 'خبير المحتوى', en: 'Subject Matter Expert' },
  'lp.role.INSTRUCTIONAL_DESIGNER': { ar: 'مصمم تعليمي', en: 'Instructional Designer' },
  'lp.role.OUTLINE_WRITER': { ar: 'كاتب المخطط', en: 'Outline Writer' },
  'lp.role.SCRIPT_WRITER': { ar: 'كاتب السكريبت', en: 'Script Writer' },
  'lp.role.PPT_DESIGNER': { ar: 'مصمم العرض التقديمي', en: 'PPT Designer' },
  'lp.role.VOICE_OVER_ARTIST': { ar: 'فنان التعليق الصوتي', en: 'Voice Over Artist' },
  'lp.role.AUDIO_REVIEWER': { ar: 'مراجع الصوت', en: 'Audio Reviewer' },
  'lp.role.VIDEO_EDITOR': { ar: 'محرر الفيديو', en: 'Video Editor' },
  'lp.role.QUALITY_REVIEWER': { ar: 'مراجع الجودة', en: 'Quality Reviewer' },
  'lp.role.VIEWER': { ar: 'مُشاهد', en: 'Viewer' },
  'lp.due.OVERDUE': { ar: 'متأخر', en: 'Overdue' },
  'lp.due.DUE_TODAY': { ar: 'مستحق اليوم', en: 'Due today' },
  'lp.due.DUE_SOON': { ar: 'مستحق قريبًا', en: 'Due soon' },

  'lp.dashboard.title': { ar: 'لوحة إنتاج المحتوى', en: 'Production dashboard' },
  'lp.dashboard.subtitle': { ar: 'اعرف بسرعة ما أُنجز، وما يحتاج انتباهك، ومن عليه الدور.', en: 'See what is done, what needs attention, and who is next.' },
  'lp.dashboard.progress': { ar: 'تقدم الإنتاج', en: 'Production progress' },
  'lp.dashboard.attention': { ar: 'يحتاج انتباهك', en: 'Attention required' },
  'lp.dashboard.courses': { ar: 'الكورسات النشطة', en: 'Active courses' },
  'lp.dashboard.activity': { ar: 'آخر النشاط', en: 'Recent activity' },
  'lp.dashboard.workload': { ar: 'ضغط العمل', en: 'Workload' },
  'lp.dashboard.yourWork': { ar: 'المطلوب منك', en: 'Your work' },
  'lp.dashboard.assignedToYou': { ar: '{n} أعمال مسندة إليك', en: '{n} assigned to you' },
  'lp.dashboard.waitingForYou': { ar: '{n} مراجعات تنتظر قرارك', en: '{n} reviews waiting for you' },
  'lp.dashboard.yourOverdue': { ar: '{n} متأخر', en: '{n} overdue' },
  'lp.kpi.activeCourses': { ar: 'الكورسات النشطة', en: 'Active courses' },
  'lp.kpi.totalLessons': { ar: 'إجمالي الدروس', en: 'Total lessons' },
  'lp.kpi.completedLessons': { ar: 'دروس مكتملة', en: 'Completed lessons' },
  'lp.kpi.underReview': { ar: 'قيد المراجعة', en: 'Under review' },
  'lp.kpi.changesRequested': { ar: 'مطلوب تعديلها', en: 'Changes requested' },
  'lp.kpi.overdue': { ar: 'متأخرة', en: 'Overdue' },
  'lp.attention.overdue': { ar: '{n} أصل متأخر', en: '{n} overdue assets' },
  'lp.attention.review': { ar: '{n} أصل ينتظر المراجعة', en: '{n} assets waiting for review' },
  'lp.attention.changes': { ar: '{n} أصل يحتاج تعديلات', en: '{n} assets need changes' },
  'lp.attention.blocked': { ar: '{n} درس متوقف', en: '{n} blocked lessons' },
  'lp.attention.allClear': { ar: 'لا توجد أمور تحتاج تدخلاً الآن.', en: 'Nothing needs attention right now.' },
  'lp.course.title': { ar: 'الكورسات', en: 'Courses' },
  'lp.course.subtitle': { ar: 'أدر رحلة المحتوى من المخطط حتى الفيديو النهائي.', en: 'Manage content from outline to final video.' },
  'lp.course.new': { ar: 'كورس جديد', en: 'New course' },
  'lp.course.name': { ar: 'اسم الكورس', en: 'Course name' },
  'lp.course.code': { ar: 'كود الكورس', en: 'Course code' },
  'lp.course.description': { ar: 'الوصف', en: 'Description' },
  'lp.course.manager': { ar: 'مدير الإنتاج', en: 'Production manager' },
  'lp.course.startDate': { ar: 'تاريخ البدء', en: 'Start date' },
  'lp.course.targetDate': { ar: 'موعد الإنجاز المستهدف', en: 'Target completion date' },
  'lp.course.target': { ar: 'الموعد', en: 'Target' },
  'lp.course.cover': { ar: 'صورة الغلاف', en: 'Cover image' },
  'lp.course.status': { ar: 'الحالة', en: 'Status' },
  'lp.course.health': { ar: 'صحة الكورس', en: 'Course health' },
  'lp.course.lessonsCount': { ar: '{n} درس', en: '{n} lessons' },
  'lp.course.emptyTitle': { ar: 'لا توجد كورسات بعد', en: 'No courses yet' },
  'lp.course.emptyBody': { ar: 'ستظهر الكورسات التي لديك صلاحية رؤيتها هنا.', en: 'Courses you can access will appear here.' },
  'lp.course.emptyBodyManager': { ar: 'ابدأ بكورس، ثم أضف الوحدات والدروس في دقائق.', en: 'Start with a course, then add modules and lessons in minutes.' },
  'lp.course.createFirst': { ar: 'أنشئ أول كورس', en: 'Create your first course' },
  'lp.course.noneActive': { ar: 'لا توجد كورسات نشطة.', en: 'No active courses.' },
  'lp.create.title': { ar: 'إنشاء كورس', en: 'Create course' },
  'lp.create.stepBasics': { ar: 'بيانات الكورس', en: 'Course details' },
  'lp.create.stepLessons': { ar: 'الوحدات والدروس', en: 'Modules and lessons' },
  'lp.create.stepTeam': { ar: 'فريق الإنتاج', en: 'Production team' },
  'lp.create.steps': { ar: 'خطوات إنشاء الكورس', en: 'Course creation steps' },
  'lp.create.finish': { ar: 'إنشاء الكورس', en: 'Create course' },
  'lp.create.finishNow': { ar: 'إنشاء بدون فريق الآن', en: 'Create without team for now' },
  'lp.create.lessonsHint': { ar: 'أضف أسماء الدروس والصق قائمة كاملة أو استورد CSV.', en: 'Add lesson names, paste a list, or import a CSV.' },
  'lp.create.lessonsPlaceholder': { ar: 'اكتب اسم كل درس في سطر مستقل…', en: 'One lesson name per line…' },
  'lp.create.lessonsLabel': { ar: 'أسماء الدروس', en: 'Lesson names' },
  'lp.create.lessonsDetected': { ar: '{n} درس', en: '{n} lessons' },
  'lp.create.totalAssets': { ar: '{lessons} درس · {assets} أصل إنتاج', en: '{lessons} lessons · {assets} production assets' },
  'lp.module.label': { ar: 'الوحدة', en: 'Module' },
  'lp.module.add': { ar: 'إضافة وحدة', en: 'Add module' },
  'lp.module.name': { ar: 'اسم الوحدة', en: 'Module name' },
  'lp.module.namePrompt': { ar: 'اكتب اسم الوحدة', en: 'Enter a module name' },
  'lp.tab.content': { ar: 'المحتوى', en: 'Content' },
  'lp.tab.assets': { ar: 'الملفات الإنتاجية', en: 'Assets' },
  'lp.tab.overview': { ar: 'نظرة عامة', en: 'Overview' },
  'lp.tab.lessons': { ar: 'الدروس', en: 'Lessons' },
  'lp.tab.production': { ar: 'مصفوفة الإنتاج', en: 'Production' },
  'lp.tab.team': { ar: 'الفريق', en: 'Team' },
  'lp.tab.files': { ar: 'الملفات', en: 'Files' },
  'lp.tab.activity': { ar: 'النشاط', en: 'Activity' },
  'lp.tab.settings': { ar: 'الإعدادات', en: 'Settings' },
  'lp.overview.pipeline': { ar: 'مسار الإنتاج', en: 'Production pipeline' },
  'lp.overview.openMatrix': { ar: 'فتح مصفوفة الإنتاج', en: 'Open production matrix' },
  'lp.overview.blocked': { ar: '{n} أصل متوقف في {lessons} درس', en: '{n} assets blocked across {lessons} lessons' },
  'lp.overview.details': { ar: 'التفاصيل', en: 'Details' },
  'lp.production.filters': { ar: 'تصفية المصفوفة', en: 'Matrix filters' },
  'lp.production.searchLesson': { ar: 'ابحث عن درس…', en: 'Search lessons…' },
  'lp.production.noMatch': { ar: 'لا توجد دروس تطابق الفلاتر الحالية.', en: 'No lessons match the current filters.' },
  'lp.production.emptyBody': { ar: 'أضف دروسًا لتظهر مراحل الإنتاج هنا.', en: 'Add lessons to see the production stages here.' },
  'lp.matrix.quickAssign': { ar: 'إسناد سريع', en: 'Quick assign' },
  'lp.matrix.selectAll': { ar: 'تحديد الكل', en: 'Select all' },
  'lp.lessons.add': { ar: 'إضافة درس', en: 'Add lesson' },
  'lp.lessons.create': { ar: 'إضافة الدروس', en: 'Add lessons' },
  'lp.lessons.emptyTitle': { ar: 'لا توجد دروس بعد', en: 'No lessons yet' },
  'lp.lessons.emptyBody': { ar: 'أضف أول درس وابدأ رحلة الإنتاج.', en: 'Add the first lesson to start production.' },
  'lp.lessons.duplicate': { ar: 'تكرار الدرس', en: 'Duplicate lesson' },
  'lp.lessons.archive': { ar: 'أرشفة الدرس', en: 'Archive lesson' },
  'lp.myWork.title': { ar: 'شغلي', en: 'My work' },
  'lp.myWork.subtitle': { ar: 'الأصول المسندة إليك والمراجعات التي تنتظر قرارك.', en: 'Your assigned work and reviews waiting for your decision.' },
  'lp.myWork.assigned': { ar: 'مسند إليّ', en: 'Assigned to me' },
  'lp.myWork.review': { ar: 'أراجعها', en: 'I review' },
  'lp.myWork.overdue': { ar: 'متأخر', en: 'Overdue' },
  'lp.myWork.completed': { ar: 'مكتمل', en: 'Completed' },
  'lp.myWork.caughtUp': { ar: 'أنت متابع كل المطلوب منك.', en: 'You are caught up.' },
  'lp.reviews.title': { ar: 'المراجعات', en: 'Reviews' },
  'lp.reviews.subtitle': { ar: 'افتح المحتوى، اترك ملاحظاتك، ثم اعتمد أو اطلب التعديل.', en: 'Open the content, leave feedback, then approve or request changes.' },
  'lp.reviews.needsReview': { ar: 'تنتظر قرارك', en: 'Needs your review' },
  'lp.reviews.recent': { ar: 'آخر المراجعات', en: 'Recent reviews' },
  'lp.reviews.caughtUp': { ar: 'لا توجد مراجعات معلقة.', en: 'No pending reviews.' },
  'lp.reviews.caughtUpBody': { ar: 'ستظهر هنا الأصول التي أُرسلت إلى المراجعة.', en: 'Assets submitted for review will appear here.' },
  'lp.reports.title': { ar: 'تقارير الإنتاج', en: 'Production reports' },
  'lp.reports.subtitle': { ar: 'اعرف أين يتعطل العمل وكيف يتحسن تدفق الإنتاج.', en: 'See where work slows down and how production flows.' },
  'lp.asset': { ar: 'أصل إنتاج', en: 'Production asset' },
  'lp.lesson': { ar: 'الدرس', en: 'Lesson' },
  'lp.assignee': { ar: 'المسؤول', en: 'Assignee' },
  'lp.reviewer': { ar: 'المراجع', en: 'Reviewer' },
  'lp.dueDate': { ar: 'موعد التسليم', en: 'Due date' },
  'lp.priority': { ar: 'الأولوية', en: 'Priority' },
  'lp.action.start': { ar: 'ابدأ العمل', en: 'Start work' },
  'lp.action.submit': { ar: 'إرسال للمراجعة', en: 'Submit for review' },
  'lp.action.resubmit': { ar: 'إعادة الإرسال', en: 'Resubmit' },
  'lp.action.approve': { ar: 'اعتماد', en: 'Approve' },
  'lp.action.requestChanges': { ar: 'طلب تعديلات', en: 'Request changes' },
  'lp.action.uploadFirst': { ar: 'رفع أول نسخة', en: 'Upload first version' },
  'lp.action.uploadNew': { ar: 'رفع نسخة جديدة', en: 'Upload new version' },
  'lp.action.newRevision': { ar: 'بدء نسخة جديدة', en: 'Start new revision' },
  'lp.action.newRevisionFile': { ar: 'رفع نسخة جديدة', en: 'Upload new revision' },
  'lp.action.lock': { ar: 'قفل الأصل', en: 'Lock asset' },
  'lp.action.reopen': { ar: 'إعادة فتح', en: 'Reopen' },
  'lp.action.override': { ar: 'تجاوز الاعتماد', en: 'Override dependency' },
  'lp.action.more': { ar: 'إجراءات إضافية', en: 'More actions' },
  'lp.waitingForReview': { ar: 'في انتظار المراجعة', en: 'Waiting for review' },
  'lp.blocked': { ar: 'متوقف مؤقتًا', en: 'Blocked' },
  'lp.waitingFor': { ar: 'ينتظر', en: 'Waiting for' },
  'lp.openComments': { ar: '{n} ملاحظات مفتوحة', en: '{n} open comments' },
  'lp.upload.title': { ar: 'رفع نسخة', en: 'Upload version' },
  'lp.upload.drop': { ar: 'اسحب الملف هنا أو اختره من جهازك', en: 'Drop a file here or choose one from your device' },
  'lp.upload.browse': { ar: 'اختيار ملف', en: 'Choose file' },
  'lp.upload.link': { ar: 'إضافة رابط', en: 'Add a link' },
  'lp.upload.notes': { ar: 'ملاحظات النسخة', en: 'Version notes' },
  'lp.upload.notesPlaceholder': { ar: 'ما الذي تغير في هذه النسخة؟', en: 'What changed in this version?' },
  'lp.versions.compare': { ar: 'مقارنة النسخ', en: 'Compare versions' },
  'lp.versions.reviewHistory': { ar: 'سجل المراجعة', en: 'Review history' },
  'lp.versions.none': { ar: 'لا توجد نسخ بعد.', en: 'No versions yet.' },
  'lp.comment.placeholder': { ar: 'اكتب ملاحظتك…', en: 'Write your comment…' },
  'lp.comment.send': { ar: 'إرسال الملاحظة', en: 'Send comment' },
  'lp.comment.resolve': { ar: 'حل الملاحظة', en: 'Resolve comment' },
  'lp.comment.reopen': { ar: 'إعادة فتح الملاحظة', en: 'Reopen comment' },
  'lp.comment.none': { ar: 'لا توجد ملاحظات.', en: 'No comments.' },
  'lp.comment.noneOpen': { ar: 'لا توجد ملاحظات مفتوحة.', en: 'No open comments.' },
  'lp.save.saving': { ar: 'جارٍ الحفظ…', en: 'Saving…' },
  'lp.save.saved': { ar: 'تم الحفظ', en: 'Saved' },
  'lp.save.failed': { ar: 'تعذر الحفظ', en: 'Could not save' },
  'lp.save.conflict': { ar: 'تغير المحتوى في مكان آخر.', en: 'This content changed elsewhere.' },
  'lp.save.reload': { ar: 'تحميل النسخة الأحدث', en: 'Load latest' },
  'lp.unavailable.title': { ar: 'إنتاج المحتوى غير متاح الآن', en: 'Production is unavailable right now' },
  'lp.unavailable.body': { ar: 'تأكد من تشغيل قاعدة البيانات ثم أعد المحاولة.', en: 'Make sure the database is running, then try again.' },

  // ── shared labels ────────────────────────────────────────────────
  'lp.stage': { ar: 'المرحلة', en: 'Stage' },
  'lp.team': { ar: 'فريق الكورس', en: 'Course team' },
  'lp.everyone': { ar: 'الجميع', en: 'Everyone' },
  'lp.person': { ar: 'الشخص', en: 'Person' },
  'lp.progress': { ar: 'التقدم', en: 'Progress' },
  'lp.unassigned': { ar: 'غير مسند', en: 'Unassigned' },
  'lp.currentPerson': { ar: 'الشخص الحالي', en: 'Current person' },
  'lp.noReviewer': { ar: 'بدون مراجع', en: 'No reviewer' },
  'lp.noModule': { ar: 'دروس بدون وحدة', en: 'Lessons without a module' },
  'lp.assign': { ar: 'إسناد', en: 'Assign' },
  'lp.assignTo': { ar: 'إسناد إلى', en: 'Assign to' },
  'lp.allStages': { ar: 'كل المراحل', en: 'All stages' },
  'lp.allPriorities': { ar: 'كل الأولويات', en: 'All priorities' },
  'lp.lastUpdated': { ar: 'آخر تحديث', en: 'Last updated' },
  'lp.latestVersion': { ar: 'أحدث نسخة', en: 'Latest version' },
  'lp.overallCompletion': { ar: 'نسبة الإنجاز الكلية', en: 'Overall completion' },
  'lp.viewAll': { ar: 'عرض الكل', en: 'View all' },
  'lp.loadMore': { ar: 'عرض المزيد', en: 'Load more' },
  'lp.retry': { ar: 'إعادة المحاولة', en: 'Try again' },
  'lp.rename': { ar: 'إعادة تسمية', en: 'Rename' },
  'lp.restore': { ar: 'استعادة', en: 'Restore' },
  'lp.next': { ar: 'التالي', en: 'Next' },
  'lp.approvalOf': { ar: 'اعتماد {stage}', en: '{stage} approval' },
  'lp.lockedBanner': { ar: 'مقفل — هذا الأصل نهائي ولا يمكن تعديله.', en: 'Locked — this asset is final and can’t be changed.' },
  'lp.changesBanner': { ar: 'طلب {name} تعديلات — {n} ملاحظات مفتوحة للمعالجة', en: '{name} requested changes — {n} open comments to address' },
  'lp.overrideNote': { ar: 'تجاوز {name} الاعتماد:', en: 'Dependency overridden by {name}:' },
  'lp.action.approveVersion': { ar: 'اعتماد النسخة', en: 'Approve version' },
  'lp.action.editAssignment': { ar: 'تعديل الإسناد', en: 'Edit assignment' },
  'lp.search.course': { ar: 'كورس إنتاج', en: 'Production course' },
  'lp.search.lesson': { ar: 'درس إنتاج', en: 'Production lesson' },
  'lp.sidebar.comments': { ar: 'الملاحظات', en: 'Comments' },
  'lp.sidebar.versions': { ar: 'النسخ', en: 'Versions' },
  'lp.sidebar.activity': { ar: 'النشاط', en: 'Activity' },
  'lp.sidebar.collapse': { ar: 'إخفاء اللوحة', en: 'Hide panel' },
  'lp.sidebar.open': { ar: 'الملاحظات', en: 'Comments' },

  // ── lesson / course state enums ──────────────────────────────────
  'lp.lessonState.COMPLETE': { ar: 'مكتمل', en: 'Complete' },
  'lp.lessonState.CHANGES_REQUESTED': { ar: 'مطلوب تعديل', en: 'Changes requested' },
  'lp.lessonState.IN_REVIEW': { ar: 'قيد المراجعة', en: 'In review' },
  'lp.lessonState.IN_PRODUCTION': { ar: 'قيد الإنتاج', en: 'In production' },
  'lp.lessonState.NOT_STARTED': { ar: 'لم يبدأ', en: 'Not started' },
  'lp.decision.APPROVED': { ar: 'معتمد', en: 'Approved' },
  'lp.decision.CHANGES_REQUESTED': { ar: 'مطلوب تعديل', en: 'Changes requested' },
  'lp.decision.PENDING': { ar: 'بانتظار المراجعة', en: 'Pending review' },
  'lp.quick.ALL': { ar: 'الكل', en: 'All' },
  'lp.quick.OVERDUE': { ar: 'متأخر', en: 'Overdue' },
  'lp.quick.REVIEW': { ar: 'قيد المراجعة', en: 'In review' },
  'lp.quick.CHANGES': { ar: 'تعديلات', en: 'Changes' },
  'lp.quick.APPROVED': { ar: 'معتمد', en: 'Approved' },
  'lp.quick.BLOCKED': { ar: 'متوقف', en: 'Blocked' },
  'lp.attention.list.overdue': { ar: 'الأصول المتأخرة', en: 'Overdue assets' },
  'lp.attention.list.review': { ar: 'بانتظار المراجعة', en: 'Waiting for review' },
  'lp.attention.list.changes': { ar: 'مطلوب تعديلها', en: 'Changes requested' },
  'lp.attention.list.blocked': { ar: 'الأصول المتوقفة', en: 'Blocked assets' },
  'lp.healthReason.TARGET_PASSED': { ar: 'فات الموعد المستهدف في {date}', en: 'Target date passed on {date}' },
  'lp.healthReason.MANY_OVERDUE': { ar: '{n} أصول متأخرة ({share}٪ من العمل المفتوح)', en: '{n} overdue assets ({share}% of open work)' },
  'lp.healthReason.SOME_OVERDUE': { ar: '{n} أصول متأخرة', en: '{n} overdue assets' },
  'lp.healthReason.BEHIND_SCHEDULE': { ar: 'أُنجز {actual}٪ والمتوقع حتى الآن {expected}٪', en: '{actual}% done, {expected}% expected by now' },
  'lp.healthReason.TARGET_CLOSE': { ar: '{n} يوم على الموعد، والمنجز {actual}٪', en: '{n} days to target, {actual}% done' },

  // ── courses, creation, settings ──────────────────────────────────
  'lp.course.active': { ar: 'نشط', en: 'Active' },
  'lp.course.onHold': { ar: 'معلّق', en: 'On hold' },
  'lp.course.archived': { ar: 'المؤرشفة', en: 'Archived' },
  'lp.course.archivedChip': { ar: 'مؤرشف', en: 'Archived' },
  'lp.course.allHealth': { ar: 'كل الحالات', en: 'All health states' },
  'lp.course.allManagers': { ar: 'كل المديرين', en: 'All managers' },
  'lp.course.noArchived': { ar: 'لا توجد كورسات مؤرشفة.', en: 'No archived courses.' },
  'lp.course.noMatch': { ar: 'لا توجد كورسات تطابق الفلاتر.', en: 'No courses match these filters.' },
  'lp.course.search': { ar: 'ابحث عن كورس…', en: 'Search courses…' },
  'lp.course.sections': { ar: 'أقسام الكورس', en: 'Course sections' },
  'lp.sort': { ar: 'الترتيب', en: 'Sort' },
  'lp.sort.recent': { ar: 'آخر نشاط', en: 'Recent activity' },
  'lp.sort.name': { ar: 'الاسم', en: 'Name' },
  'lp.sort.target': { ar: 'الموعد المستهدف', en: 'Target date' },
  'lp.sort.progress': { ar: 'التقدم', en: 'Progress' },
  'lp.create.coverFailed': { ar: 'أُنشئ الكورس، لكن تعذر رفع صورة الغلاف.', en: 'The course was created, but the cover image couldn’t be uploaded.' },
  'lp.create.defaultMaker': { ar: 'منفّذ {stage}', en: '{stage} maker' },
  'lp.create.defaultReviewer': { ar: 'المراجع', en: 'Reviewer' },
  'lp.create.defaultsHint': { ar: 'اختر من ينفذ ويراجع كل مرحلة عادةً. الدروس الجديدة تبدأ بإسنادهم تلقائيًا.', en: 'Pick who usually makes and reviews each stage. New lessons start with these people assigned.' },
  'lp.create.import': { ar: 'استيراد', en: 'Import' },
  'lp.create.importCsv': { ar: 'استيراد الدروس من ملف CSV', en: 'Import lessons from CSV' },
  'lp.create.me': { ar: 'أنا', en: 'Me' },
  'lp.create.modulePlaceholder': { ar: 'اسم الوحدة {n}', en: 'Module {n} name' },
  'lp.create.namePlaceholder': { ar: 'مثال: أساسيات الاعتمادية الصناعية', en: 'e.g. Industrial Reliability Essentials' },
  'lp.create.nameRequired': { ar: 'اسم الكورس مطلوب.', en: 'A course name is required.' },
  'lp.create.removeModule': { ar: 'إزالة الوحدة', en: 'Remove module' },
  'lp.settings.basics': { ar: 'البيانات الأساسية', en: 'Basics' },
  'lp.settings.rules': { ar: 'قواعد الإنتاج', en: 'Production rules' },
  'lp.settings.enforce': { ar: 'فرض ترتيب المراحل', en: 'Enforce stage dependencies' },
  'lp.settings.enforceHint': { ar: 'لا تبدأ المرحلة قبل اعتماد المراحل التي تعتمد عليها.', en: 'A stage can’t start until the stages it depends on are approved.' },
  'lp.settings.wpm': { ar: 'سرعة التعليق (كلمة في الدقيقة)', en: 'Narration speed (words per minute)' },
  'lp.settings.wpmHint': { ar: 'تُستخدم لتقدير مدة السكريبت.', en: 'Used to estimate script duration.' },
  'lp.settings.riskGap': { ar: 'في خطر عند التأخر بنسبة (٪)', en: 'At risk when behind by (%)' },
  'lp.settings.riskGapHint': { ar: 'الفرق بين التقدم المتوقع والفعلي.', en: 'Gap between expected and actual progress.' },
  'lp.settings.riskDays': { ar: 'في خطر قبل الموعد بـ (يوم)', en: 'At risk within (days of target)' },
  'lp.settings.riskDaysHint': { ar: 'نبّه على الكورس إذا اقترب الموعد والعمل متأخر.', en: 'Flag the course when the target is this close and work is behind.' },
  'lp.settings.delayedShare': { ar: 'متأخر عندما تبلغ نسبة المتأخر (٪)', en: 'Delayed when overdue share reaches (%)' },
  'lp.settings.delayedShareHint': { ar: 'نسبة الأصول المفتوحة المتأخرة.', en: 'Share of open assets that are overdue.' },
  'lp.settings.checklist': { ar: 'قائمة جودة الفيديو', en: 'Video QA checklist' },
  'lp.settings.checklistHint': { ar: 'النسخ الجديدة من الفيديو تبدأ بهذه البنود.', en: 'New video versions start with these items.' },
  'lp.settings.checkItem': { ar: 'بند القائمة {n}', en: 'Checklist item {n}' },
  'lp.settings.addItem': { ar: 'إضافة بند', en: 'Add item' },
  'lp.settings.required': { ar: 'إلزامي', en: 'Required' },
  'lp.settings.archiveTitle': { ar: 'الأرشفة', en: 'Archive' },
  'lp.settings.archive': { ar: 'أرشفة الكورس', en: 'Archive course' },
  'lp.settings.archiveBody': { ar: 'الأرشفة تخفي الكورس من القوائم ولوحات المتابعة دون حذف أي شيء.', en: 'Archiving hides the course from lists and dashboards. Nothing is deleted.' },
  'lp.settings.restoreBody': { ar: 'هذا الكورس مؤرشف. الاستعادة تعيده إلى القوائم ولوحات المتابعة.', en: 'This course is archived. Restoring brings it back to lists and dashboards.' },
  'lp.settings.archiveConfirmTitle': { ar: 'أرشفة {name}؟', en: 'Archive {name}?' },

  // ── lessons, team, files ─────────────────────────────────────────
  'lp.lesson.course': { ar: 'الكورس', en: 'Course' },
  'lp.lesson.currentStage': { ar: 'المرحلة الحالية', en: 'Current stage' },
  'lp.lesson.stages': { ar: 'مراحل الدرس', en: 'Lesson stages' },
  'lp.lessons.summary': { ar: '{modules} وحدات · {lessons} درس', en: '{modules} modules · {lessons} lessons' },
  'lp.lessons.archived': { ar: 'الدروس المؤرشفة', en: 'Archived lessons' },
  'lp.lessons.noArchived': { ar: 'لا توجد دروس مؤرشفة.', en: 'No archived lessons.' },
  'lp.lessons.moduleEmpty': { ar: 'لا توجد دروس في هذه الوحدة بعد.', en: 'No lessons in this module yet.' },
  'lp.lessons.addTo': { ar: 'إضافة درس إلى {module}', en: 'Add lesson to {module}' },
  'lp.lessons.collapse': { ar: 'طي الوحدة', en: 'Collapse module' },
  'lp.lessons.expand': { ar: 'توسيع الوحدة', en: 'Expand module' },
  'lp.lessons.rename': { ar: 'إعادة تسمية الدرس', en: 'Rename lesson' },
  'lp.lessons.moveUp': { ar: 'نقل لأعلى', en: 'Move up' },
  'lp.lessons.moveDown': { ar: 'نقل لأسفل', en: 'Move down' },
  'lp.lessons.moveTo': { ar: 'نقل إلى وحدة', en: 'Move to module' },
  'lp.lessons.copyName': { ar: '{name} (نسخة)', en: '{name} (copy)' },
  'lp.lessons.archiveTitle': { ar: 'أرشفة هذا الدرس؟', en: 'Archive this lesson?' },
  'lp.lessons.archiveBody': { ar: 'سيُخفى «{name}» وأصوله الخمسة من الإنتاج، ويمكن استعادته لاحقًا.', en: '“{name}” and its five assets will be hidden from production. You can restore it later.' },
  'lp.lessons.pasteHint': { ar: 'الصق درسًا في كل سطر، أو صفوف «الوحدة، الدرس» من جدول بيانات.', en: 'Paste one lesson per line, or “Module, Lesson” rows from a spreadsheet.' },
  'lp.module.rename': { ar: 'إعادة تسمية الوحدة', en: 'Rename module' },
  'lp.module.archive': { ar: 'أرشفة الوحدة', en: 'Archive module' },
  'lp.team.members': { ar: 'الأعضاء ({n})', en: 'Members ({n})' },
  'lp.team.add': { ar: 'إضافة عضو', en: 'Add member' },
  'lp.team.roles': { ar: 'الأدوار', en: 'Roles' },
  'lp.team.editRoles': { ar: 'تعديل الأدوار', en: 'Edit roles' },
  'lp.team.remove': { ar: 'إزالة من الكورس', en: 'Remove from course' },
  'lp.team.choose': { ar: 'اختر شخصًا', en: 'Choose a person' },
  'lp.team.empty': { ar: 'لا يوجد أعضاء بعد.', en: 'No team members yet.' },
  'lp.team.contributors': { ar: 'يعملون أيضًا على الكورس', en: 'Also working on this course' },
  'lp.team.defaults': { ar: 'الإسناد الافتراضي للمراحل', en: 'Stage defaults' },
  'lp.team.defaultsHint': { ar: 'لمن تُسند الدروس الجديدة في كل مرحلة.', en: 'Who new lessons are assigned to for each stage.' },
  'lp.team.applyToOpen': { ar: 'املأ أيضًا الأصول المفتوحة غير المسندة', en: 'Also fill open assets that have nobody assigned' },
  'lp.files.file': { ar: 'الملف', en: 'File' },
  'lp.files.version': { ar: 'النسخة', en: 'Version' },
  'lp.files.uploadedBy': { ar: 'رفعه', en: 'Uploaded by' },
  'lp.files.size': { ar: 'الحجم', en: 'Size' },
  'lp.files.current': { ar: 'الحالية', en: 'Current' },
  'lp.files.latestOnly': { ar: 'أحدث النسخ فقط', en: 'Latest versions only' },
  'lp.files.empty': { ar: 'لا توجد ملفات بعد', en: 'No files yet' },
  'lp.files.emptyBody': { ar: 'ستظهر هنا ملفات العروض والتعليقات الصوتية والفيديوهات المرفوعة.', en: 'Uploaded slides, voice-overs and videos will appear here.' },

  // ── matrix, my work, reviews, reports ────────────────────────────
  'lp.matrix.selectLesson': { ar: 'تحديد {name}', en: 'Select {name}' },
  'lp.matrix.assignTitle': { ar: 'إسناد {stage} لدرس {lesson}', en: 'Assign {stage} for {lesson}' },
  'lp.matrix.roleHint': { ar: 'عادةً ينفذه {maker} ويراجعه {reviewer}.', en: 'Usually made by a {maker} and reviewed by a {reviewer}.' },
  'lp.production.quick': { ar: 'فلاتر سريعة', en: 'Quick filters' },
  'lp.production.clear': { ar: 'مسح الفلاتر', en: 'Clear filters' },
  'lp.production.showing': { ar: '{n} من {total} درس', en: '{n} of {total} lessons' },
  'lp.production.allModules': { ar: 'كل الوحدات', en: 'All modules' },
  'lp.production.anyAssignee': { ar: 'أي مسؤول', en: 'Any assignee' },
  'lp.production.anyReviewer': { ar: 'أي مراجع', en: 'Any reviewer' },
  'lp.bulk.selected': { ar: '{n} درس محدد', en: '{n} lessons selected' },
  'lp.bulk.keep': { ar: 'بدون تغيير', en: 'Keep as is' },
  'lp.bulk.apply': { ar: 'تطبيق على المحدد', en: 'Apply to selected' },
  'lp.myWork.changesRequested': { ar: 'مطلوب تعديلها', en: 'Changes requested' },
  'lp.myWork.emptyTitle': { ar: 'لا يوجد عمل مسند إليك', en: 'Nothing assigned to you' },
  'lp.myWork.emptyBody': { ar: 'ستظهر هنا الأصول المسندة إليك والمراجعات التي تنتظر قرارك.', en: 'Assets assigned to you and reviews waiting for your decision will show up here.' },
  'lp.reviews.scope': { ar: 'نطاق المراجعات', en: 'Review scope' },
  'lp.reviews.scopeMine': { ar: 'مراجعاتي', en: 'My reviews' },
  'lp.reviews.scopeAll': { ar: 'كل المراجعات', en: 'All reviews' },
  'lp.reviews.allCourses': { ar: 'كل الكورسات', en: 'All courses' },
  'lp.reviews.resubmitted': { ar: 'أُعيد إرسالها', en: 'Resubmitted' },
  'lp.workload.active': { ar: 'نشط', en: 'Active' },
  'lp.workload.review': { ar: 'يراجع', en: 'Reviewing' },
  'lp.workload.overdue': { ar: 'متأخر', en: 'Overdue' },
  'lp.workload.empty': { ar: 'لا يوجد عمل مسند بعد.', en: 'No assigned work yet.' },
  'lp.reports.allCourses': { ar: 'كل الكورسات', en: 'All courses' },
  'lp.reports.export': { ar: 'تصدير CSV', en: 'Export CSV' },
  'lp.reports.bottleneck': { ar: 'عنق الزجاجة', en: 'Bottleneck' },
  'lp.reports.noBottleneck': { ar: 'لا توجد مرحلة تعطل العمل الآن.', en: 'No stage is holding work up right now.' },
  'lp.reports.waitDays': { ar: 'متوسط انتظار {n} يوم', en: 'waiting {n} days on average' },
  'lp.reports.turnaround': { ar: 'سرعة المراجعة', en: 'Review turnaround' },
  'lp.reports.throughput': { ar: 'الاعتمادات أسبوعيًا', en: 'Approvals per week' },
  'lp.reports.throughputLabel': { ar: '{n} اعتماد في الأسابيع الأخيرة', en: '{n} approvals in recent weeks' },
  'lp.reports.stages': { ar: 'المراحل', en: 'Stages' },
  'lp.reports.courses': { ar: 'الكورسات', en: 'Courses' },
  'lp.reports.completion': { ar: 'الإنجاز', en: 'Completion' },
  'lp.reports.complete': { ar: 'مكتمل', en: 'Complete' },
  'lp.reports.total': { ar: 'الإجمالي', en: 'Total' },
  'lp.reports.review': { ar: 'قيد المراجعة', en: 'In review' },
  'lp.reports.overdue': { ar: 'متأخر', en: 'Overdue' },
  'lp.reports.avgReview': { ar: 'متوسط زمن المراجعة', en: 'Avg. review time' },
  'lp.reports.avgWait': { ar: 'متوسط الانتظار', en: 'Avg. wait' },
  'lp.reports.versions': { ar: 'متوسط النسخ', en: 'Avg. versions' },
  'lp.reports.rounds': { ar: 'متوسط جولات التعديل', en: 'Avg. change rounds' },
  'lp.reports.productionDays': { ar: 'متوسط أيام الإنتاج', en: 'Avg. production days' },
  'lp.reports.hours': { ar: '{n} ساعة', en: '{n} h' },
  'lp.reports.days': { ar: '{n} يوم', en: '{n} days' },
  'lp.reports.overdueList': { ar: 'العمل المتأخر ({n})', en: 'Overdue work ({n})' },
  'lp.reports.noOverdue': { ar: 'لا يوجد شيء متأخر.', en: 'Nothing is overdue.' },
  'lp.reports.method': { ar: 'طريقة القياس: زمن المراجعة من الإرسال حتى القرار، وزمن الانتظار من الإرسال حتى بدء المراجعة.', en: 'How these are measured: review time runs from submission to decision; wait time from submission until review starts.' },

  // ── asset header dialogs ─────────────────────────────────────────
  'lp.dialog.submitTitle': { ar: 'إرسال للمراجعة', en: 'Submit for review' },
  'lp.dialog.resubmitTitle': { ar: 'إعادة الإرسال للمراجعة', en: 'Resubmit for review' },
  'lp.dialog.submitBody': { ar: 'سيتم إشعار {name} لمراجعة هذه النسخة.', en: '{name} will be notified to review this version.' },
  'lp.dialog.theReviewer': { ar: 'المراجع', en: 'the reviewer' },
  'lp.dialog.openCommentsWarning': { ar: 'لا تزال هناك {n} ملاحظات مفتوحة على هذا الأصل.', en: 'There are still {n} open comments on this asset.' },
  'lp.dialog.changesTitle': { ar: 'طلب تعديلات', en: 'Request changes' },
  'lp.dialog.changesBody': { ar: 'وضّح للمنفّذ ما الذي يحتاج إلى تعديل.', en: 'Tell the maker what needs to change.' },
  'lp.dialog.changesBodyWithComments': { ar: 'ستُرسل {n} ملاحظات مفتوحة مع هذا الطلب.', en: '{n} open comments will be sent back with this request.' },
  'lp.dialog.summary': { ar: 'ملخص التعديلات المطلوبة', en: 'Summary of changes needed' },
  'lp.dialog.summaryPlaceholder': { ar: 'مثال: اختصر المقدمة وصحح عناوين الرسم البياني.', en: 'e.g. Shorten the introduction and fix the chart labels.' },
  'lp.dialog.approveTitle': { ar: 'اعتماد {version}؟', en: 'Approve {version}?' },
  'lp.dialog.approveBody': { ar: 'الاعتماد يجعل هذه النسخة نهائية لهذه المرحلة ويفتح المراحل التي تعتمد عليها.', en: 'Approving marks this version as final for this stage and unblocks the stages that depend on it.' },
  'lp.dialog.approveNotes': { ar: 'ملاحظات للفريق (اختياري)', en: 'Notes for the team (optional)' },
  'lp.dialog.lockToo': { ar: 'قفله أيضًا حتى لا يتغير', en: 'Also lock it so it can’t change' },
  'lp.dialog.lockTitle': { ar: 'قفل هذا الأصل؟', en: 'Lock this asset?' },
  'lp.dialog.lockBody': { ar: 'الأصل المقفل لا يقبل نسخًا أو ملاحظات أو إعادة إسناد حتى يعيد المدير فتحه.', en: 'A locked asset can’t take new versions, comments or reassignment until a manager reopens it.' },
  'lp.dialog.reopenTitle': { ar: 'إعادة فتح هذا الأصل؟', en: 'Reopen this asset?' },
  'lp.dialog.reopenBody': { ar: 'إعادة الفتح تسمح بتعديل الأصل مرة أخرى، ويُحفظ السبب في السجل.', en: 'Reopening lets the asset change again. The reason is kept in the history.' },
  'lp.dialog.reason': { ar: 'السبب', en: 'Reason' },
  'lp.dialog.overrideTitle': { ar: 'تجاوز الاعتماد؟', en: 'Override the dependency?' },
  'lp.dialog.overrideBody': { ar: 'هذا الأصل ينتظر {stages}. التجاوز يسمح ببدء العمل الآن، ويُحفظ السبب في السجل.', en: 'This asset is waiting for {stages}. Overriding lets work start now; the reason is kept in the history.' },
  'lp.dialog.revisionTitle': { ar: 'بدء نسخة جديدة؟', en: 'Start a new revision?' },
  'lp.dialog.revisionBody': { ar: 'تبقى {version} في السجل، وتبدأ النسخة الجديدة من محتواها.', en: '{version} stays in the history. The new revision starts from its content.' },

  // ── comments, drawing, text review ───────────────────────────────
  'lp.comment.filter.OPEN': { ar: 'مفتوحة', en: 'Open' },
  'lp.comment.filter.RESOLVED': { ar: 'محلولة', en: 'Resolved' },
  'lp.comment.filter.ALL': { ar: 'الكل', en: 'All' },
  'lp.comment.generalPlaceholderPositional': { ar: 'ملاحظة عامة على هذه النسخة…', en: 'General comment on this version…' },
  'lp.comment.reply': { ar: 'رد', en: 'Reply' },
  'lp.comment.resolved': { ar: 'محلولة', en: 'Resolved' },
  'lp.comment.suggestion': { ar: 'اقتراح', en: 'Suggestion' },
  'lp.comment.suggestDelete': { ar: 'حذف هذا النص', en: 'Delete this text' },
  'lp.comment.apply': { ar: 'تطبيق الاقتراح', en: 'Apply suggestion' },
  'lp.comment.slide': { ar: 'الشريحة {n}', en: 'Slide {n}' },
  'lp.comment.block': { ar: 'مقطع السكريبت', en: 'Script block' },
  'lp.comment.deleteShape': { ar: 'حذف الشكل', en: 'Delete shape' },
  'lp.comment.deleteTitle': { ar: 'حذف هذا التعليق التوضيحي؟', en: 'Delete this annotation?' },
  'lp.comment.deleteBody': { ar: 'سيُحذف الشكل وملاحظته من هذه الشريحة.', en: 'The shape and its comment will be removed from this slide.' },
  'lp.draw.toolbar': { ar: 'أدوات التعليق', en: 'Annotation tools' },
  'lp.draw.color': { ar: 'اللون', en: 'Color' },
  'lp.draw.undo': { ar: 'تراجع', en: 'Undo' },
  'lp.draw.redo': { ar: 'إعادة', en: 'Redo' },
  'lp.draw.POINTER': { ar: 'تحديد', en: 'Select' },
  'lp.draw.PIN': { ar: 'دبوس', en: 'Pin' },
  'lp.draw.RECTANGLE': { ar: 'مستطيل', en: 'Rectangle' },
  'lp.draw.CIRCLE': { ar: 'دائرة', en: 'Circle' },
  'lp.draw.ARROW': { ar: 'سهم', en: 'Arrow' },
  'lp.draw.FREEHAND': { ar: 'رسم حر', en: 'Free draw' },
  'lp.draw.HIGHLIGHT': { ar: 'تظليل', en: 'Highlight' },
  'lp.text.comment': { ar: 'ملاحظة', en: 'Comment' },
  'lp.text.suggest': { ar: 'اقتراح', en: 'Suggest' },
  'lp.text.replaceWith': { ar: 'استبدل بـ', en: 'Replace with' },
  'lp.text.suggestWhy': { ar: 'لماذا هذا التعديل؟ (اختياري)', en: 'Why this change? (optional)' },
  'lp.text.readOnly': { ar: 'للقراءة فقط', en: 'Read only' },
  'lp.text.words': { ar: '{n} كلمة', en: '{n} words' },

  // ── outline ──────────────────────────────────────────────────────
  'lp.outline.emptyTitle': { ar: 'لا يوجد مخطط بعد', en: 'No outline yet' },
  'lp.outline.emptyStart': { ar: 'ابدأ العمل لكتابة المسودة الأولى.', en: 'Start work to write the first draft.' },
  'lp.outline.emptyBlocked': { ar: 'لا يمكن البدء قبل اعتماد المراحل السابقة.', en: 'This can start once the earlier stages are approved.' },
  'lp.outline.emptyBody': { ar: 'لم يُكتب شيء في هذا المخطط بعد.', en: 'Nothing has been written for this outline yet.' },
  'lp.outline.lessonTitle': { ar: 'عنوان الدرس', en: 'Lesson title' },
  'lp.outline.lessonTitlePlaceholder': { ar: 'عنوان الدرس كما سيراه المتعلم', en: 'The lesson title as learners will see it' },
  'lp.outline.learningObjectives': { ar: 'أهداف التعلم', en: 'Learning objectives' },
  'lp.outline.learningObjectivesPlaceholder': { ar: 'هدف قابل للقياس في كل سطر…', en: 'One measurable objective per line…' },
  'lp.outline.keyTopics': { ar: 'الموضوعات الرئيسية', en: 'Key topics' },
  'lp.outline.keyTopicsPlaceholder': { ar: 'الأفكار الرئيسية التي يغطيها الدرس…', en: 'The main ideas this lesson covers…' },
  'lp.outline.definitions': { ar: 'التعريفات', en: 'Definitions' },
  'lp.outline.definitionsPlaceholder': { ar: 'المصطلحات التي يجب أن يعرفها المتعلم…', en: 'Terms learners must know…' },
  'lp.outline.examples': { ar: 'الأمثلة', en: 'Examples' },
  'lp.outline.examplesPlaceholder': { ar: 'أمثلة واقعية توضح الفكرة…', en: 'Real examples that make the idea concrete…' },
  'lp.outline.exercises': { ar: 'التمارين', en: 'Exercises' },
  'lp.outline.exercisesPlaceholder': { ar: 'ما سيتدرب عليه المتعلم…', en: 'What learners will practice…' },
  'lp.outline.caseStudies': { ar: 'دراسات الحالة', en: 'Case studies' },
  'lp.outline.caseStudiesPlaceholder': { ar: 'سيناريو قصير من الواقع العملي…', en: 'A short scenario from the field…' },
  'lp.outline.references': { ar: 'المراجع', en: 'References' },
  'lp.outline.referencesPlaceholder': { ar: 'معايير أو كتب أو روابط…', en: 'Standards, books or links…' },
  'lp.outline.estimatedDuration': { ar: 'المدة التقديرية', en: 'Estimated duration' },
  'lp.outline.estimatedDurationPlaceholder': { ar: 'مثال: 18 دقيقة', en: 'e.g. 18 minutes' },
  'lp.outline.instructorNotes': { ar: 'ملاحظات المدرب', en: 'Instructor notes' },
  'lp.outline.instructorNotesPlaceholder': { ar: 'إرشادات لمن يقدم الدرس…', en: 'Guidance for whoever delivers the lesson…' },
  'lp.outline.productionNotes': { ar: 'ملاحظات الإنتاج', en: 'Production notes' },
  'lp.outline.productionNotesPlaceholder': { ar: 'ملاحظات للمصمم والمعلق والمونتير…', en: 'Notes for the designer, narrator and editor…' },

  // ── script ───────────────────────────────────────────────────────
  'lp.script.emptyTitle': { ar: 'لا يوجد سكريبت بعد', en: 'No script yet' },
  'lp.script.emptyBlocked': { ar: 'يمكن بدء السكريبت بعد اعتماد المخطط.', en: 'The script can start once the outline is approved.' },
  'lp.script.emptyBody': { ar: 'لم يُكتب شيء في هذا السكريبت بعد.', en: 'Nothing has been written for this script yet.' },
  'lp.script.startTitle': { ar: 'جاهز لكتابة السكريبت', en: 'Ready to write the script' },
  'lp.script.startBody': { ar: 'ابدأ العمل لكتابة التعليق شريحة بشريحة.', en: 'Start work to write the narration slide by slide.' },
  'lp.script.mode.SLIDE': { ar: 'حسب الشريحة', en: 'By slide' },
  'lp.script.mode.SCENE': { ar: 'حسب المشهد', en: 'By scene' },
  'lp.script.slide': { ar: 'الشريحة {n}', en: 'Slide {n}' },
  'lp.script.scene': { ar: 'المشهد {n}', en: 'Scene {n}' },
  'lp.script.block': { ar: 'المقطع {n}', en: 'Block {n}' },
  'lp.script.blocks': { ar: '{n} مقاطع', en: '{n} blocks' },
  'lp.script.duration': { ar: 'مدة التعليق التقديرية', en: 'Estimated narration' },
  'lp.script.durationHint': { ar: 'محسوبة على {wpm} كلمة في الدقيقة', en: 'Estimated at {wpm} words per minute' },
  'lp.script.addBlock': { ar: 'إضافة مقطع', en: 'Add block' },
  'lp.script.addAfter': { ar: 'إضافة مقطع بعده', en: 'Add block after' },
  'lp.script.commentBlock': { ar: 'ملاحظة على هذا المقطع', en: 'Comment on this block' },
  'lp.script.commentOn': { ar: 'ملاحظة على {label}', en: 'Comment on {label}' },
  'lp.script.title': { ar: 'عنوان المقطع', en: 'Block title' },
  'lp.script.titlePlaceholder': { ar: 'عنوان المقطع…', en: 'Block title…' },
  'lp.script.narration': { ar: 'نص التعليق', en: 'Narration' },
  'lp.script.narrationPlaceholder': { ar: 'ما يقوله المعلق الصوتي في هذه الشريحة…', en: 'What the voice-over says for this slide…' },
  'lp.script.visual': { ar: 'التوجيه البصري', en: 'Visual direction' },
  'lp.script.visualPlaceholder': { ar: 'ما يظهر على الشاشة…', en: 'What appears on screen…' },
  'lp.script.delivery': { ar: 'ملاحظات الأداء', en: 'Delivery notes' },
  'lp.script.pronunciation': { ar: 'النطق', en: 'Pronunciation' },
  'lp.script.pauses': { ar: 'الوقفات', en: 'Pauses' },
  'lp.script.pausesHint': { ar: 'اكتب [pause 2s] حيث يجب أن يتوقف المعلق.', en: 'Write [pause 2s] where the narrator should stop.' },
  'lp.script.emphasis': { ar: 'التأكيد', en: 'Emphasis' },
  'lp.script.notes': { ar: 'ملاحظات', en: 'Notes' },
  'lp.script.manualDuration': { ar: 'مدة يدوية (بالثواني)', en: 'Duration override (seconds)' },
  'lp.script.removeTitle': { ar: 'حذف هذا المقطع؟', en: 'Remove this block?' },
  'lp.script.removeBody': { ar: 'سيُحذف نص هذا المقطع وملاحظاته من المسودة.', en: 'This block’s narration and notes will be removed from the draft.' },

  // ── PPT ──────────────────────────────────────────────────────────
  'lp.ppt.emptyTitle': { ar: 'لا توجد شرائح بعد', en: 'No slides yet' },
  'lp.ppt.emptyStart': { ar: 'ارفع أول نسخة من الشرائح للبدء.', en: 'Upload the first version of the slides to start.' },
  'lp.ppt.emptyBlocked': { ar: 'يمكن بدء الشرائح بعد اعتماد المخطط.', en: 'The slides can start once the outline is approved.' },
  'lp.ppt.emptyBody': { ar: 'لم تُرفع أي شرائح بعد.', en: 'No slides have been uploaded yet.' },
  'lp.ppt.linkOnly': { ar: 'لا يمكن معاينة هذا الرابط هنا. افتحه في تبويب جديد.', en: 'This link can’t be previewed here. Open it in a new tab.' },
  'lp.ppt.needsPdfTitle': { ar: 'يلزم إرفاق معاينة PDF', en: 'A PDF preview is needed' },
  'lp.ppt.needsPdfBody': { ar: 'المتصفحات لا تعرض ملفات PowerPoint بدقة. أرفق نسخة PDF حتى يعلّق المراجعون على كل شريحة.', en: 'Browsers can’t show PowerPoint files faithfully. Attach the PDF export so reviewers can comment on each slide.' },
  'lp.ppt.downloadOriginal': { ar: 'تنزيل الملف الأصلي', en: 'Download original' },
  'lp.ppt.attachPdf': { ar: 'إرفاق معاينة PDF', en: 'Attach PDF preview' },
  'lp.ppt.loadFailed': { ar: 'تعذر عرض الشرائح.', en: 'The slides couldn’t be displayed.' },
  'lp.ppt.previous': { ar: 'الشريحة السابقة', en: 'Previous slide' },
  'lp.ppt.next': { ar: 'الشريحة التالية', en: 'Next slide' },
  'lp.ppt.slide': { ar: 'الشريحة', en: 'Slide' },
  'lp.ppt.zoomIn': { ar: 'تكبير', en: 'Zoom in' },
  'lp.ppt.zoomOut': { ar: 'تصغير', en: 'Zoom out' },
  'lp.ppt.showResolved': { ar: 'عرض المحلولة', en: 'Show resolved' },
  'lp.ppt.commentSlide': { ar: 'ملاحظة على الشريحة', en: 'Comment on slide' },
  'lp.ppt.commentOn': { ar: 'ملاحظة على الشريحة {n}', en: 'Comment on slide {n}' },
  'lp.ppt.markOn': { ar: '{shape} على الشريحة {n}', en: '{shape} on slide {n}' },
  'lp.ppt.desktopHint': { ar: 'الرسم على الشرائح متاح على شاشة أكبر، ويمكنك قراءة الملاحظات والرد عليها.', en: 'Drawing on slides works on a larger screen. You can still read and reply to comments.' },

  // ── voice over, video, media ─────────────────────────────────────
  'lp.media.play': { ar: 'تشغيل', en: 'Play' },
  'lp.media.pause': { ar: 'إيقاف مؤقت', en: 'Pause' },
  'lp.media.back5': { ar: 'رجوع 5 ثوانٍ', en: 'Back 5 seconds' },
  'lp.media.forward5': { ar: 'تقدم 5 ثوانٍ', en: 'Forward 5 seconds' },
  'lp.media.speed': { ar: 'سرعة التشغيل', en: 'Playback speed' },
  'lp.media.seek': { ar: 'التنقل في المقطع', en: 'Seek' },
  'lp.media.commentAt': { ar: 'ملاحظة عند {time}', en: 'Comment at {time}' },
  'lp.media.markerAt': { ar: 'ملاحظة عند {time}', en: 'Comment at {time}' },
  'lp.media.endRange': { ar: 'إنهاء النطاق عند {time}', en: 'End range at {time}' },
  'lp.media.rangeHint': { ar: 'استمر في التشغيل واضغط «إنهاء النطاق» للتعليق على مقطع بدل لحظة واحدة.', en: 'Keep playing and press “End range” to comment on a stretch instead of a moment.' },
  'lp.voice.emptyTitle': { ar: 'لا يوجد تعليق صوتي بعد', en: 'No voice-over yet' },
  'lp.voice.emptyStart': { ar: 'ارفع أول تسجيل للبدء.', en: 'Upload the first recording to start.' },
  'lp.voice.emptyBlocked': { ar: 'يمكن بدء التعليق الصوتي بعد اعتماد السكريبت.', en: 'The voice-over can start once the script is approved.' },
  'lp.voice.emptyBody': { ar: 'لم يُرفع تسجيل بعد.', en: 'No recording has been uploaded yet.' },
  'lp.voice.transcript': { ar: 'النص المكتوب', en: 'Transcript' },
  'lp.voice.transcriptPlaceholder': { ar: 'النص المكتوب لهذا التسجيل…', en: 'Transcript of this recording…' },
  'lp.voice.transcriptHint': { ar: 'الصق النص كما سُجل.', en: 'Paste the script as recorded.' },
  'lp.voice.noTranscript': { ar: 'لا يوجد نص مكتوب لهذه النسخة.', en: 'No transcript for this version.' },
  'lp.video.emptyTitle': { ar: 'لا يوجد فيديو بعد', en: 'No video yet' },
  'lp.video.emptyStart': { ar: 'ارفع النسخة الأولى لبدء المراجعة.', en: 'Upload the first cut to start the review.' },
  'lp.video.emptyBlocked': { ar: 'يمكن بدء الفيديو بعد اعتماد العرض والسكريبت والتعليق الصوتي.', en: 'The video can start once the slides, script and voice-over are approved.' },
  'lp.video.emptyBody': { ar: 'لم يُرفع فيديو بعد.', en: 'No video has been uploaded yet.' },
  'lp.video.linkNotPlayable': { ar: 'لا يمكن تشغيل هذا الرابط هنا.', en: 'This link can’t be played here.' },
  'lp.video.drawOnFrame': { ar: 'الرسم على اللقطة', en: 'Draw on frame' },
  'lp.video.drawHint': { ar: '{n} أشكال · ارسم على اللقطة المتوقفة', en: '{n} shapes · draw on the paused frame' },
  'lp.video.references': { ar: 'المراجع', en: 'References' },
  'lp.video.noReferences': { ar: 'لا توجد مراجع معتمدة بعد.', en: 'No approved references yet.' },
  'lp.video.notApprovedYet': { ar: 'لم يُعتمد بعد', en: 'Not approved yet' },
  'lp.video.openSlides': { ar: 'فتح الشرائح', en: 'Open slides' },
  'lp.video.checklist': { ar: 'قائمة الجودة', en: 'QA checklist' },
  'lp.video.checklistSummary': { ar: 'اجتاز {passed} من {total} · {issues} ملاحظات', en: '{passed} of {total} passed · {issues} issues' },
  'lp.video.checklistReadOnly': { ar: 'المراجع وحده يمكنه تحديث القائمة.', en: 'Only the reviewer can update the checklist.' },
  'lp.video.issueNotes': { ar: 'ما المشكلة؟', en: 'What’s wrong?' },
  'lp.checkState.PENDING': { ar: 'معلق', en: 'Pending' },
  'lp.checkState.PASSED': { ar: 'ناجح', en: 'Passed' },
  'lp.checkState.ISSUE': { ar: 'مشكلة', en: 'Issue' },
  'lp.check.CONTENT_ACCURACY': { ar: 'دقة المحتوى', en: 'Content accuracy' },
  'lp.check.VISUAL_QUALITY': { ar: 'الجودة البصرية', en: 'Visual quality' },
  'lp.check.AUDIO_QUALITY': { ar: 'جودة الصوت', en: 'Audio quality' },
  'lp.check.SYNCHRONIZATION': { ar: 'التزامن', en: 'Synchronization' },
  'lp.check.BRANDING': { ar: 'الهوية البصرية', en: 'Branding' },
  'lp.check.SPELLING': { ar: 'الإملاء', en: 'Spelling' },
  'lp.check.ANIMATIONS': { ar: 'الحركات', en: 'Animations' },
  'lp.check.TRANSITIONS': { ar: 'الانتقالات', en: 'Transitions' },
  'lp.check.TECHNICAL_QUALITY': { ar: 'الجودة التقنية', en: 'Technical quality' },
  'lp.check.FINAL_APPROVAL': { ar: 'الموافقة النهائية', en: 'Final approval' },

  // ── uploads and versions ─────────────────────────────────────────
  'lp.upload.file': { ar: 'رفع ملف', en: 'Upload a file' },
  'lp.upload.linkLabel': { ar: 'الرابط', en: 'Link' },
  'lp.upload.linkHintPpt': { ar: 'رابط Google Slides أو OneDrive.', en: 'A Google Slides or OneDrive link.' },
  'lp.upload.linkHintVideo': { ar: 'رابط مباشر لملف MP4 أو MOV أو WebM.', en: 'A direct link to an MP4, MOV or WebM file.' },
  'lp.upload.accepted': { ar: '{types} · حتى {max}', en: '{types} · up to {max}' },
  'lp.upload.remove': { ar: 'إزالة الملف', en: 'Remove file' },
  'lp.upload.submit': { ar: 'رفع كنسخة v{n}', en: 'Upload as v{n}' },
  'lp.upload.tooLarge': { ar: 'حجم الملف أكبر من {max}.', en: 'This file is larger than {max}.' },
  'lp.upload.wrongType': { ar: 'الأنواع المقبولة: {types}.', en: 'Accepted types: {types}.' },
  'lp.upload.cancelled': { ar: 'تم إلغاء الرفع.', en: 'Upload cancelled.' },
  'lp.upload.afterApproval': { ar: 'هذا الأصل معتمد. الرفع يبدأ نسخة جديدة تحتاج مراجعة من جديد.', en: 'This asset is approved. Uploading starts a new revision that needs review again.' },
  'lp.versions.view': { ar: 'عرض', en: 'View' },
  'lp.versions.download': { ar: 'تنزيل', en: 'Download' },
  'lp.versions.openLink': { ar: 'فتح الرابط', en: 'Open link' },
  'lp.versions.noneText': { ar: 'لا توجد نسخ مرسلة بعد. تصبح المسودة v1 عند إرسالها.', en: 'No submitted versions yet. The draft becomes v1 when it’s submitted.' },
  'lp.versions.viewingOld': { ar: 'أنت تعرض v{n}، وهي نسخة أقدم.', en: 'You’re viewing v{n}, an older version.' },
  'lp.versions.backToCurrent': { ar: 'العودة إلى النسخة الحالية', en: 'Back to current version' },
  'lp.versions.compareTitle': { ar: 'مقارنة النسخ', en: 'Compare versions' },
  'lp.versions.before': { ar: 'النسخة الأقدم', en: 'Older version' },
  'lp.versions.after': { ar: 'النسخة الأحدث', en: 'Newer version' },
  'lp.versions.added': { ar: 'مضاف', en: 'Added' },
  'lp.versions.removed': { ar: 'محذوف', en: 'Removed' },
  'lp.versions.block.added': { ar: 'مقطع مضاف', en: 'Added block' },
  'lp.versions.block.removed': { ar: 'مقطع محذوف', en: 'Removed block' },
  'lp.versions.block.same': { ar: 'بدون تغيير', en: 'Unchanged' },

  // ── toasts ───────────────────────────────────────────────────────
  'lp.toast.started': { ar: 'بدأ العمل.', en: 'Work started.' },
  'lp.toast.submitted': { ar: 'أُرسل للمراجعة.', en: 'Submitted for review.' },
  'lp.toast.resubmitted': { ar: 'أُعيد الإرسال للمراجعة.', en: 'Resubmitted for review.' },
  'lp.toast.approved': { ar: 'تم الاعتماد.', en: 'Approved.' },
  'lp.toast.changesRequested': { ar: 'تم طلب التعديلات.', en: 'Changes requested.' },
  'lp.toast.locked': { ar: 'تم قفل الأصل.', en: 'Asset locked.' },
  'lp.toast.reopened': { ar: 'تمت إعادة فتح الأصل.', en: 'Asset reopened.' },
  'lp.toast.overridden': { ar: 'تم تجاوز الاعتماد.', en: 'Dependency overridden.' },
  'lp.toast.assigned': { ar: 'تم حفظ الإسناد.', en: 'Assignment saved.' },
  'lp.toast.bulkAssigned': { ar: 'تم تحديث {n} أصول.', en: '{n} assets updated.' },
  'lp.toast.bulkSkipped': { ar: 'تم تحديث {n} أصول وتخطي {skipped}.', en: '{n} assets updated, {skipped} skipped.' },
  'lp.toast.saved': { ar: 'تم الحفظ.', en: 'Saved.' },
  'lp.toast.versionUploaded': { ar: 'تم رفع النسخة {n}.', en: 'Version {n} uploaded.' },
  'lp.toast.previewAttached': { ar: 'تم إرفاق معاينة PDF.', en: 'PDF preview attached.' },
  'lp.toast.commentResolved': { ar: 'تم تحديث الملاحظة.', en: 'Comment updated.' },
  'lp.toast.suggestionApplied': { ar: 'طُبق الاقتراح على المسودة.', en: 'Suggestion applied to the draft.' },
  'lp.toast.courseCreated': { ar: 'تم إنشاء الكورس.', en: 'Course created.' },
  'lp.toast.courseArchived': { ar: 'تمت أرشفة الكورس.', en: 'Course archived.' },
  'lp.toast.courseRestored': { ar: 'تمت استعادة الكورس.', en: 'Course restored.' },
  'lp.toast.defaultsApplied': { ar: 'تم حفظ الافتراضيات وإسناد {n} أصول مفتوحة.', en: 'Defaults saved and {n} open assets assigned.' },
  'lp.toast.memberRemoved': { ar: 'تمت إزالة العضو.', en: 'Member removed.' },
  'lp.toast.moduleCreated': { ar: 'تمت إضافة الوحدة.', en: 'Module added.' },
  'lp.toast.moduleArchived': { ar: 'تمت أرشفة الوحدة.', en: 'Module archived.' },
  'lp.toast.lessonsCreated': { ar: 'تمت إضافة {n} دروس.', en: '{n} lessons added.' },
  'lp.toast.lessonArchived': { ar: 'تمت أرشفة الدرس.', en: 'Lesson archived.' },
  'lp.toast.lessonRestored': { ar: 'تمت استعادة الدرس.', en: 'Lesson restored.' },
  'lp.toast.lessonDuplicated': { ar: 'تم تكرار الدرس.', en: 'Lesson duplicated.' },
  'lp.toast.lessonMoved': { ar: 'تم نقل الدرس.', en: 'Lesson moved.' },

  // ── refusals (lp.error.*) ────────────────────────────────────────
  'lp.error.GENERIC': { ar: 'حدث خطأ ما. حاول مرة أخرى.', en: 'Something went wrong. Please try again.' },
  'lp.error.NETWORK': { ar: 'تعذر الوصول إلى الخادم. تحقق من الاتصال وحاول مرة أخرى.', en: 'Couldn’t reach the server. Check your connection and try again.' },
  'lp.error.VALIDATION_FAILED': { ar: 'بعض الحقول تحتاج مراجعة.', en: 'Some fields need attention.' },
  'lp.error.NOT_FOUND': { ar: 'هذا العنصر غير موجود أو ليست لديك صلاحية الوصول إليه.', en: 'This item no longer exists or you don’t have access to it.' },
  'lp.error.FORBIDDEN': { ar: 'ليست لديك صلاحية لتنفيذ ذلك.', en: 'You don’t have permission to do this.' },
  'lp.error.INVALID_TRANSITION': { ar: 'هذا الإجراء غير متاح في الحالة الحالية.', en: 'This action isn’t available in the current status.' },
  'lp.error.ASSET_LOCKED': { ar: 'هذا الأصل مقفل.', en: 'This asset is locked.' },
  'lp.error.ASSET_BLOCKED': { ar: 'بانتظار اعتماد مرحلة سابقة.', en: 'Waiting for an earlier stage to be approved.' },
  'lp.error.NOT_BLOCKED': { ar: 'هذا الأصل لا ينتظر أي مرحلة.', en: 'This asset isn’t waiting on anything.' },
  'lp.error.NOT_SUPPORTED': { ar: 'غير متاح لهذه المرحلة.', en: 'Not available for this stage.' },
  'lp.error.CONTENT_REQUIRED': { ar: 'أضف محتوى قبل الإرسال.', en: 'Add content before submitting.' },
  'lp.error.NEW_VERSION_REQUIRED': { ar: 'عدّل المحتوى أو ارفع نسخة جديدة قبل إعادة الإرسال.', en: 'Change the content or upload a new version before resubmitting.' },
  'lp.error.OWN_WORK': { ar: 'لا يمكنك مراجعة عملك بنفسك.', en: 'You can’t review your own work.' },
  'lp.error.FEEDBACK_REQUIRED': { ar: 'أضف ملاحظة أو ملخصًا قبل طلب التعديلات.', en: 'Add a comment or a summary before requesting changes.' },
  'lp.error.CHECKLIST_INCOMPLETE': { ar: 'أكمل بنود قائمة الجودة المطلوبة أولًا.', en: 'Finish the required QA checklist items first.' },
  'lp.error.DRAFT_CONFLICT': { ar: 'تغير هذا المحتوى في مكان آخر. حمّل النسخة الأحدث.', en: 'This content changed elsewhere. Load the latest copy.' },
  'lp.error.REASON_REQUIRED': { ar: 'السبب مطلوب.', en: 'A reason is required.' },
  'lp.error.ASSIGNEE_INVALID': { ar: 'لا يمكن إسناد هذا الشخص إلى هذا الكورس.', en: 'That person can’t be assigned to this course.' },
  'lp.error.REVIEWER_IS_ASSIGNEE': { ar: 'يجب أن يكون المراجع شخصًا غير المسؤول.', en: 'The reviewer must be someone other than the assignee.' },
  'lp.error.COURSE_CODE_TAKEN': { ar: 'هذا الكود مستخدم لكورس آخر.', en: 'Another course already uses this code.' },
  'lp.error.MODULE_NOT_EMPTY': { ar: 'انقل دروس هذه الوحدة أو أرشفها أولًا.', en: 'Move or archive this module’s lessons first.' },
  'lp.error.FILE_REQUIRED': { ar: 'اختر ملفًا للرفع.', en: 'Choose a file to upload.' },
  'lp.error.FILE_TOO_LARGE': { ar: 'حجم الملف أكبر من المسموح.', en: 'This file is larger than allowed.' },
  'lp.error.FILE_TYPE_NOT_ALLOWED': { ar: 'نوع الملف غير مقبول هنا.', en: 'This file type isn’t accepted here.' },
  'lp.error.LINK_INVALID': { ar: 'أدخل رابطًا صحيحًا.', en: 'Enter a valid link.' },
  'lp.error.PREVIEW_EXISTS': { ar: 'هذه النسخة لديها معاينة بالفعل.', en: 'This version already has a preview.' },
  'lp.error.COMMENT_NOT_EDITABLE': { ar: 'لم يعد بالإمكان تعديل هذه الملاحظة.', en: 'This comment can no longer be edited.' },
  'lp.error.SUGGESTION_OUTDATED': { ar: 'تغير النص منذ تقديم هذا الاقتراح.', en: 'The text changed since this suggestion was made.' },
  'lp.error.LAST_MANAGER': { ar: 'يحتاج الكورس إلى مدير إنتاج واحد على الأقل.', en: 'A course needs at least one production manager.' },
  'lp.error.STORAGE_UNAVAILABLE': { ar: 'تخزين الملفات غير متاح الآن. حاول بعد قليل.', en: 'File storage is unavailable right now. Try again shortly.' },

  // ── activity sentences ({actor}, {stage}, {version}, {count}) ────
  'lp.activity.empty': { ar: 'لا يوجد نشاط بعد.', en: 'No activity yet.' },
  'lp.activity.system': { ar: 'النظام', en: 'System' },
  'lp.activity.milestone': { ar: '{course} اكتمل بنسبة {n}٪', en: '{course} is now {n}% complete' },
  'lp.activity.COURSE_CREATED': { ar: 'أنشأ {actor} الكورس', en: '{actor} created the course' },
  'lp.activity.COURSE_UPDATED': { ar: 'حدّث {actor} بيانات الكورس', en: '{actor} updated the course' },
  'lp.activity.COURSE_UPDATED_many': { ar: 'حدّث {actor} {count} بنود في الكورس', en: '{actor} updated {count} course items' },
  'lp.activity.COURSE_ARCHIVED': { ar: 'أرشف {actor} الكورس', en: '{actor} archived the course' },
  'lp.activity.COURSE_RESTORED': { ar: 'استعاد {actor} الكورس', en: '{actor} restored the course' },
  'lp.activity.MODULE_CREATED': { ar: 'أضاف {actor} وحدة', en: '{actor} added a module' },
  'lp.activity.MODULE_UPDATED': { ar: 'أعاد {actor} تسمية وحدة', en: '{actor} renamed a module' },
  'lp.activity.MODULE_ARCHIVED': { ar: 'أرشف {actor} وحدة', en: '{actor} archived a module' },
  'lp.activity.LESSON_CREATED': { ar: 'أضاف {actor} درسًا', en: '{actor} added a lesson' },
  'lp.activity.LESSON_CREATED_many': { ar: 'أضاف {actor} {count} دروس', en: '{actor} added {count} lessons' },
  'lp.activity.LESSON_UPDATED': { ar: 'حدّث {actor} درسًا', en: '{actor} updated a lesson' },
  'lp.activity.LESSON_ARCHIVED': { ar: 'أرشف {actor} درسًا', en: '{actor} archived a lesson' },
  'lp.activity.LESSON_ARCHIVED_many': { ar: 'أرشف {actor} {count} دروس', en: '{actor} archived {count} lessons' },
  'lp.activity.LESSON_RESTORED': { ar: 'استعاد {actor} درسًا', en: '{actor} restored a lesson' },
  'lp.activity.TEAM_MEMBER_ADDED': { ar: 'أضاف {actor} عضوًا إلى الفريق', en: '{actor} added a team member' },
  'lp.activity.TEAM_MEMBER_UPDATED': { ar: 'غيّر {actor} أدوار عضو', en: '{actor} changed a member’s roles' },
  'lp.activity.TEAM_MEMBER_REMOVED': { ar: 'أزال {actor} عضوًا من الفريق', en: '{actor} removed a team member' },
  'lp.activity.ASSET_ASSIGNED': { ar: 'أسند {actor} {stage}', en: '{actor} assigned the {stage}' },
  'lp.activity.ASSET_ASSIGNED_many': { ar: 'أسند {actor} {count} أصول {stage}', en: '{actor} assigned {count} {stage} assets' },
  'lp.activity.WORK_STARTED': { ar: 'بدأ {actor} العمل على {stage}', en: '{actor} started the {stage}' },
  'lp.activity.VERSION_UPLOADED': { ar: 'رفع {actor} {stage} v{version}', en: '{actor} uploaded {stage} v{version}' },
  'lp.activity.VERSION_UPLOADED_preview': { ar: 'أرفق {actor} معاينة PDF لـ{stage} v{version}', en: '{actor} attached a PDF preview to {stage} v{version}' },
  'lp.activity.SUBMITTED_FOR_REVIEW': { ar: 'أرسل {actor} {stage} v{version} للمراجعة', en: '{actor} submitted {stage} v{version} for review' },
  'lp.activity.REVIEW_STARTED': { ar: 'بدأ {actor} مراجعة {stage} v{version}', en: '{actor} started reviewing {stage} v{version}' },
  'lp.activity.CHANGES_REQUESTED': { ar: 'طلب {actor} تعديلات على {stage} v{version}', en: '{actor} requested changes on {stage} v{version}' },
  'lp.activity.RESUBMITTED': { ar: 'أعاد {actor} إرسال {stage} v{version}', en: '{actor} resubmitted {stage} v{version}' },
  'lp.activity.APPROVED': { ar: 'اعتمد {actor} {stage} v{version}', en: '{actor} approved {stage} v{version}' },
  'lp.activity.LOCKED': { ar: 'قفل {actor} {stage}', en: '{actor} locked the {stage}' },
  'lp.activity.REOPENED': { ar: 'أعاد {actor} فتح {stage}', en: '{actor} reopened the {stage}' },
  'lp.activity.DEPENDENCY_OVERRIDDEN': { ar: 'تجاوز {actor} الاعتماد لـ{stage}', en: '{actor} overrode the dependency for the {stage}' },
  'lp.activity.COMMENT_CREATED': { ar: 'علّق {actor} على {stage}', en: '{actor} commented on the {stage}' },
  'lp.activity.COMMENT_RESOLVED': { ar: 'حلّ {actor} ملاحظة على {stage}', en: '{actor} resolved a comment on the {stage}' },
  'lp.activity.COMMENT_REOPENED': { ar: 'أعاد {actor} فتح ملاحظة على {stage}', en: '{actor} reopened a comment on the {stage}' },
  'lp.activity.SUGGESTION_APPLIED': { ar: 'طبّق {actor} اقتراحًا على {stage}', en: '{actor} applied a suggestion to the {stage}' },
  'lp.activity.CHECKLIST_UPDATED': { ar: 'حدّث {actor} قائمة جودة {stage}', en: '{actor} updated the {stage} QA checklist' },
  'lp.activity.CHECKLIST_UPDATED_many': { ar: 'حدّث {actor} قائمة جودة الفيديو ({count} بنود)', en: '{actor} updated the video checklist ({count} items)' },
  'lp.activity.TRANSCRIPT_UPDATED': { ar: 'حدّث {actor} النص المكتوب لـ{stage}', en: '{actor} updated the {stage} transcript' },

  // ── The course workspace ────────────────────────────────────────
  'lp.status': { ar: 'الحالة', en: 'Status' },
  'lp.course.completedShare': { ar: '{n}% مكتمل', en: '{n}% completed' },
  'lp.course.share': { ar: 'مشاركة', en: 'Share' },
  'lp.course.linkCopied': { ar: 'تم نسخ رابط الكورس', en: 'Course link copied' },
  'lp.course.more': { ar: 'المزيد', en: 'More' },
  'lp.course.demo': { ar: 'بيانات تجريبية', en: 'Demo data' },

  'lp.stageCard.done': { ar: '{done} من {total}', en: '{done} of {total}' },
  'lp.stageCard.inReview': { ar: '{n} قيد المراجعة', en: '{n} in review' },

  'lp.overview.current': { ar: 'الإنتاج الجاري', en: 'Current production' },
  'lp.overview.currentStage': { ar: 'المرحلة الحالية', en: 'Current stage' },
  'lp.overview.nothingInFlight': { ar: 'لا يوجد عمل جارٍ في هذا الكورس الآن.', en: 'Nothing is in production in this course right now.' },
  'lp.overview.inProduction': { ar: '{n} قيد الإنتاج', en: '{n} in active production' },
  'lp.overview.acrossStages': { ar: 'على {n} مراحل', en: 'Across {n} stages' },
  'lp.overview.noneOverdue': { ar: 'لا شيء متأخر', en: 'Nothing is late' },
  'lp.overview.attention.overdue': { ar: '{n} ملفات متأخرة', en: '{n} assets overdue' },
  'lp.overview.attention.review': { ar: '{n} ملفات تنتظر المراجعة', en: '{n} assets waiting for review' },
  'lp.overview.attention.reviewBody': { ar: 'موزعة على {n} مراحل إنتاج.', en: 'Spread across {n} production stages.' },
  'lp.overview.attention.changes': { ar: '{n} ملفات مطلوب تعديلها', en: '{n} assets need changes' },
  'lp.overview.attention.changesBody': { ar: 'رجعت من المراجعة وتنتظر صاحب العمل.', en: 'Came back from review and are waiting on their maker.' },
  'lp.overview.attention.blocked': { ar: '{n} ملفات متوقفة في {lessons} دروس', en: '{n} assets blocked in {lessons} lessons' },
  'lp.overview.attention.blockedBody': { ar: 'مُسندة لأشخاص لا يستطيعون البدء قبل اعتماد مرحلة سابقة.', en: 'Assigned to somebody who cannot start until an earlier stage is approved.' },

  'lp.lessons.moduleComplete': { ar: '{n}% مكتمل', en: '{n}% complete' },
  'lp.lessons.minutes': { ar: '{n} دقيقة', en: '{n} min' },
  'lp.lessons.updated': { ar: 'آخر تحديث {when}', en: 'Updated {when}' },

  'lp.assets.chooseLesson': { ar: 'اختر الدرس', en: 'Choose a lesson' },
  'lp.assets.openLesson': { ar: 'فتح الدرس', en: 'Open lesson' },
  'lp.assets.emptyBody': { ar: 'أضف دروسًا ليظهر لكل درس ملفاته الخمسة.', en: 'Add lessons and each one arrives with its five production assets.' },
  'lp.assets.complete': { ar: '{done} من {total} مراحل معتمدة', en: '{done} of {total} stages approved' },
  'lp.assets.version': { ar: 'إصدار {n}', en: 'v{n}' },
  'lp.assets.open': { ar: 'فتح', en: 'Open' },
  'lp.assets.noVersion': { ar: 'لا يوجد إصدار بعد', en: 'No version yet' },
  'lp.assets.noNarration': { ar: 'لم يُكتب نص بعد', en: 'No narration written yet' },
  'lp.assets.waitingOn': { ar: 'ينتظر: {stages}', en: 'Waiting for: {stages}' },
  'lp.asset.title.OUTLINE': { ar: 'مخطط الدرس', en: 'Lesson outline' },
  'lp.asset.title.PPT': { ar: 'العرض التقديمي', en: 'Presentation' },
  'lp.asset.title.SCRIPT': { ar: 'نص التعليق', en: 'Narration script' },
  'lp.asset.title.VOICE_OVER': { ar: 'التسجيل الصوتي', en: 'Audio recording' },
  'lp.asset.title.VIDEO': { ar: 'الفيديو النهائي', en: 'Final video' },

  'lp.team.active': { ar: 'نشط', en: 'Active' },
  'lp.team.inactive': { ar: 'غير نشط', en: 'Inactive' },
  'lp.team.load': { ar: '{active} عمل · {reviews} مراجعة', en: '{active} active · {reviews} reviews' },
  'lp.team.loadOverdue': { ar: '{n} متأخر', en: '{n} overdue' },
};

const WORDS: Record<string, Pair> = {
  dashboard: { ar: 'لوحة التحكم', en: 'Dashboard' }, courses: { ar: 'الكورسات', en: 'Courses' }, course: { ar: 'الكورس', en: 'Course' },
  lessons: { ar: 'الدروس', en: 'Lessons' }, lesson: { ar: 'الدرس', en: 'Lesson' }, production: { ar: 'الإنتاج', en: 'Production' },
  settings: { ar: 'الإعدادات', en: 'Settings' }, team: { ar: 'الفريق', en: 'Team' }, files: { ar: 'الملفات', en: 'Files' },
  activity: { ar: 'النشاط', en: 'Activity' }, review: { ar: 'المراجعة', en: 'Review' }, reviews: { ar: 'المراجعات', en: 'Reviews' },
  title: { ar: 'العنوان', en: 'Title' }, name: { ar: 'الاسم', en: 'Name' }, description: { ar: 'الوصف', en: 'Description' },
  status: { ar: 'الحالة', en: 'Status' }, progress: { ar: 'التقدم', en: 'Progress' }, empty: { ar: 'فارغ', en: 'Empty' },
  loading: { ar: 'جارٍ التحميل', en: 'Loading' }, search: { ar: 'بحث', en: 'Search' }, all: { ar: 'الكل', en: 'All' },
  assigned: { ar: 'مسند', en: 'Assigned' }, waiting: { ar: 'ينتظر', en: 'Waiting' }, completed: { ar: 'مكتمل', en: 'Completed' },
  overdue: { ar: 'متأخر', en: 'Overdue' }, changes: { ar: 'تعديلات', en: 'Changes' }, requested: { ar: 'مطلوب', en: 'Requested' },
  save: { ar: 'حفظ', en: 'Save' }, saved: { ar: 'تم الحفظ', en: 'Saved' }, add: { ar: 'إضافة', en: 'Add' }, remove: { ar: 'إزالة', en: 'Remove' },
  create: { ar: 'إنشاء', en: 'Create' }, upload: { ar: 'رفع', en: 'Upload' }, download: { ar: 'تنزيل', en: 'Download' },
  start: { ar: 'بدء', en: 'Start' }, submit: { ar: 'إرسال', en: 'Submit' }, approve: { ar: 'اعتماد', en: 'Approve' },
  outline: { ar: 'المخطط', en: 'Outline' }, ppt: { ar: 'العرض التقديمي', en: 'PPT' }, script: { ar: 'السكريبت', en: 'Script' },
  voice: { ar: 'التعليق الصوتي', en: 'Voice' }, video: { ar: 'الفيديو', en: 'Video' },
  OUTLINE: { ar: 'المخطط', en: 'Outline' }, PPT: { ar: 'العرض التقديمي', en: 'PPT' }, SCRIPT: { ar: 'السكريبت', en: 'Script' },
  VOICE_OVER: { ar: 'التعليق الصوتي', en: 'Voice Over' }, VIDEO: { ar: 'الفيديو', en: 'Video' },
  NOT_STARTED: { ar: 'لم يبدأ', en: 'Not started' }, ASSIGNED: { ar: 'مُسند', en: 'Assigned' }, IN_PROGRESS: { ar: 'قيد التنفيذ', en: 'In progress' },
  SUBMITTED: { ar: 'مُرسل للمراجعة', en: 'Submitted' }, UNDER_REVIEW: { ar: 'قيد المراجعة', en: 'Under review' },
  CHANGES_REQUESTED: { ar: 'مطلوب تعديل', en: 'Changes requested' }, RESUBMITTED: { ar: 'أُعيد إرساله', en: 'Resubmitted' }, APPROVED: { ar: 'معتمد', en: 'Approved' }, LOCKED: { ar: 'مقفل', en: 'Locked' },
  LOW: { ar: 'منخفضة', en: 'Low' }, NORMAL: { ar: 'عادية', en: 'Normal' }, HIGH: { ar: 'عالية', en: 'High' }, URGENT: { ar: 'عاجلة', en: 'Urgent' },
  ON_TRACK: { ar: 'في المسار الصحيح', en: 'On track' }, AT_RISK: { ar: 'في خطر', en: 'At risk' }, DELAYED: { ar: 'متأخر', en: 'Delayed' }, COMPLETED: { ar: 'مكتمل', en: 'Completed' },
};

function humanize(token: string): Pair {
  const exact = WORDS[token];
  if (exact) return exact;
  const spaced = token.replace(/([a-z])([A-Z])/g, '$1 $2').replaceAll('_', ' ').toLowerCase();
  return { ar: spaced, en: spaced.replace(/\b\w/g, (char) => char.toUpperCase()) };
}

/** Returns readable feature copy for a key not yet added to the exact table. */
export function learningProductionString(key: string, lang: 'ar' | 'en') {
  const exact = LP_STRINGS[key];
  if (exact) return exact[lang];
  if (!key.startsWith('lp.')) return key;
  const parts = key.split('.').slice(1);
  const labels = parts.map(humanize);
  return labels.map((label) => label[lang]).join(lang === 'ar' ? ' · ' : ' · ');
}
