/**
 * The production module keeps its copy close to its feature code.  The
 * workspace dictionary is intentionally not coupled to this large surface;
 * the small exact table below covers user-facing sentences and the fallback
 * turns enum/dynamic keys into readable labels instead of exposing `lp.*`.
 */

type Pair = { ar: string; en: string };

export const LP_STRINGS: Record<string, Pair> = {
  'lp.module': { ar: 'إنتاج المحتوى التعليمي', en: 'E-Learning Production' },
  'lp.nav.dashboard': { ar: 'لوحة الإنتاج', en: 'Dashboard' },
  'lp.nav.courses': { ar: 'الكورسات', en: 'Courses' },
  'lp.nav.myWork': { ar: 'شغلي', en: 'My Work' },
  'lp.nav.reviews': { ar: 'المراجعات', en: 'Reviews' },
  'lp.nav.reports': { ar: 'التقارير', en: 'Reports' },
  'lp.dashboard.title': { ar: 'لوحة إنتاج المحتوى', en: 'Production dashboard' },
  'lp.dashboard.subtitle': { ar: 'اعرف بسرعة ما أُنجز، وما يحتاج انتباهك، ومن عليه الدور.', en: 'See what is done, what needs attention, and who is next.' },
  'lp.dashboard.progress': { ar: 'تقدم الإنتاج', en: 'Production progress' },
  'lp.dashboard.attention': { ar: 'يحتاج انتباهك', en: 'Attention required' },
  'lp.dashboard.courses': { ar: 'الكورسات النشطة', en: 'Active courses' },
  'lp.dashboard.activity': { ar: 'آخر النشاط', en: 'Recent activity' },
  'lp.dashboard.workload': { ar: 'ضغط العمل', en: 'Workload' },
  'lp.dashboard.yourWork': { ar: 'المطلوب منك', en: 'Your work' },
  'lp.dashboard.assignedToYou': { ar: '{n} أعمال مسندة إليك', en: '{n} assigned to you' },
  'lp.dashboard.waitingForYou': { ar: '{n} مراجعات تنتظر قرارك', en: '{n} reviews waiting for you' },
  'lp.dashboard.yourOverdue': { ar: '{n} متأخر', en: '{n} overdue' },
  'lp.kpi.activeCourses': { ar: 'الكورسات النشطة', en: 'Active courses' },
  'lp.kpi.totalLessons': { ar: 'إجمالي الدروس', en: 'Total lessons' },
  'lp.kpi.completedLessons': { ar: 'دروس مكتملة', en: 'Completed lessons' },
  'lp.kpi.underReview': { ar: 'قيد المراجعة', en: 'Under review' },
  'lp.kpi.changesRequested': { ar: 'مطلوب تعديلها', en: 'Changes requested' },
  'lp.kpi.overdue': { ar: 'متأخرة', en: 'Overdue' },
  'lp.attention.overdue': { ar: '{n} أصل متأخر', en: '{n} overdue assets' },
  'lp.attention.review': { ar: '{n} أصل ينتظر المراجعة', en: '{n} assets waiting for review' },
  'lp.attention.changes': { ar: '{n} أصل يحتاج تعديلات', en: '{n} assets need changes' },
  'lp.attention.blocked': { ar: '{n} درس متوقف', en: '{n} blocked lessons' },
  'lp.attention.allClear': { ar: 'لا توجد أمور تحتاج تدخلاً الآن.', en: 'Nothing needs attention right now.' },
  'lp.course.title': { ar: 'الكورسات', en: 'Courses' },
  'lp.course.subtitle': { ar: 'أدر رحلة المحتوى من المخطط حتى الفيديو النهائي.', en: 'Manage content from outline to final video.' },
  'lp.course.new': { ar: 'كورس جديد', en: 'New course' },
  'lp.course.name': { ar: 'اسم الكورس', en: 'Course name' },
  'lp.course.code': { ar: 'كود الكورس', en: 'Course code' },
  'lp.course.description': { ar: 'الوصف', en: 'Description' },
  'lp.course.manager': { ar: 'مدير الإنتاج', en: 'Production manager' },
  'lp.course.startDate': { ar: 'تاريخ البدء', en: 'Start date' },
  'lp.course.targetDate': { ar: 'موعد الإنجاز المستهدف', en: 'Target completion date' },
  'lp.course.target': { ar: 'الموعد', en: 'Target' },
  'lp.course.cover': { ar: 'صورة الغلاف', en: 'Cover image' },
  'lp.course.status': { ar: 'الحالة', en: 'Status' },
  'lp.course.health': { ar: 'صحة الكورس', en: 'Course health' },
  'lp.course.lessonsCount': { ar: '{n} درس', en: '{n} lessons' },
  'lp.course.emptyTitle': { ar: 'لا توجد كورسات بعد', en: 'No courses yet' },
  'lp.course.emptyBody': { ar: 'ستظهر الكورسات التي لديك صلاحية رؤيتها هنا.', en: 'Courses you can access will appear here.' },
  'lp.course.emptyBodyManager': { ar: 'ابدأ بكورس، ثم أضف الوحدات والدروس في دقائق.', en: 'Start with a course, then add modules and lessons in minutes.' },
  'lp.course.createFirst': { ar: 'أنشئ أول كورس', en: 'Create your first course' },
  'lp.course.noneActive': { ar: 'لا توجد كورسات نشطة.', en: 'No active courses.' },
  'lp.create.title': { ar: 'إنشاء كورس', en: 'Create course' },
  'lp.create.stepBasics': { ar: 'بيانات الكورس', en: 'Course details' },
  'lp.create.stepLessons': { ar: 'الوحدات والدروس', en: 'Modules and lessons' },
  'lp.create.stepTeam': { ar: 'فريق الإنتاج', en: 'Production team' },
  'lp.create.steps': { ar: 'خطوات إنشاء الكورس', en: 'Course creation steps' },
  'lp.create.finish': { ar: 'إنشاء الكورس', en: 'Create course' },
  'lp.create.finishNow': { ar: 'إنشاء بدون فريق الآن', en: 'Create without team for now' },
  'lp.create.lessonsHint': { ar: 'أضف أسماء الدروس والصق قائمة كاملة أو استورد CSV.', en: 'Add lesson names, paste a list, or import a CSV.' },
  'lp.create.lessonsPlaceholder': { ar: 'اكتب اسم كل درس في سطر مستقل…', en: 'One lesson name per line…' },
  'lp.create.lessonsLabel': { ar: 'أسماء الدروس', en: 'Lesson names' },
  'lp.create.lessonsDetected': { ar: '{n} درس', en: '{n} lessons' },
  'lp.create.totalAssets': { ar: '{lessons} درس · {assets} أصل إنتاج', en: '{lessons} lessons · {assets} production assets' },
  'lp.module.label': { ar: 'الوحدة', en: 'Module' },
  'lp.module.add': { ar: 'إضافة وحدة', en: 'Add module' },
  'lp.module.name': { ar: 'اسم الوحدة', en: 'Module name' },
  'lp.module.namePrompt': { ar: 'اكتب اسم الوحدة', en: 'Enter a module name' },
  'lp.tab.overview': { ar: 'نظرة عامة', en: 'Overview' },
  'lp.tab.lessons': { ar: 'الدروس', en: 'Lessons' },
  'lp.tab.production': { ar: 'مصفوفة الإنتاج', en: 'Production' },
  'lp.tab.team': { ar: 'الفريق', en: 'Team' },
  'lp.tab.files': { ar: 'الملفات', en: 'Files' },
  'lp.tab.activity': { ar: 'النشاط', en: 'Activity' },
  'lp.tab.settings': { ar: 'الإعدادات', en: 'Settings' },
  'lp.overview.pipeline': { ar: 'مسار الإنتاج', en: 'Production pipeline' },
  'lp.overview.openMatrix': { ar: 'فتح مصفوفة الإنتاج', en: 'Open production matrix' },
  'lp.production.filters': { ar: 'تصفية المصفوفة', en: 'Matrix filters' },
  'lp.production.searchLesson': { ar: 'ابحث عن درس…', en: 'Search lessons…' },
  'lp.production.noMatch': { ar: 'لا توجد دروس تطابق الفلاتر الحالية.', en: 'No lessons match the current filters.' },
  'lp.production.emptyBody': { ar: 'أضف دروسًا لتظهر مراحل الإنتاج هنا.', en: 'Add lessons to see the production stages here.' },
  'lp.matrix.quickAssign': { ar: 'إسناد سريع', en: 'Quick assign' },
  'lp.matrix.selectAll': { ar: 'تحديد الكل', en: 'Select all' },
  'lp.lessons.add': { ar: 'إضافة درس', en: 'Add lesson' },
  'lp.lessons.create': { ar: 'إضافة الدروس', en: 'Add lessons' },
  'lp.lessons.emptyTitle': { ar: 'لا توجد دروس بعد', en: 'No lessons yet' },
  'lp.lessons.emptyBody': { ar: 'أضف أول درس وابدأ رحلة الإنتاج.', en: 'Add the first lesson to start production.' },
  'lp.lessons.duplicate': { ar: 'تكرار الدرس', en: 'Duplicate lesson' },
  'lp.lessons.archive': { ar: 'أرشفة الدرس', en: 'Archive lesson' },
  'lp.myWork.title': { ar: 'شغلي', en: 'My work' },
  'lp.myWork.subtitle': { ar: 'الأصول المسندة إليك والمراجعات التي تنتظر قرارك.', en: 'Your assigned work and reviews waiting for your decision.' },
  'lp.myWork.assigned': { ar: 'مسند إليّ', en: 'Assigned to me' },
  'lp.myWork.review': { ar: 'أراجعها', en: 'I review' },
  'lp.myWork.overdue': { ar: 'متأخر', en: 'Overdue' },
  'lp.myWork.completed': { ar: 'مكتمل', en: 'Completed' },
  'lp.myWork.caughtUp': { ar: 'أنت متابع كل المطلوب منك.', en: 'You are caught up.' },
  'lp.reviews.title': { ar: 'المراجعات', en: 'Reviews' },
  'lp.reviews.subtitle': { ar: 'افتح المحتوى، اترك ملاحظاتك، ثم اعتمد أو اطلب التعديل.', en: 'Open the content, leave feedback, then approve or request changes.' },
  'lp.reviews.needsReview': { ar: 'تنتظر قرارك', en: 'Needs your review' },
  'lp.reviews.recent': { ar: 'آخر المراجعات', en: 'Recent reviews' },
  'lp.reviews.caughtUp': { ar: 'لا توجد مراجعات معلقة.', en: 'No pending reviews.' },
  'lp.reviews.caughtUpBody': { ar: 'ستظهر هنا الأصول التي أُرسلت إلى المراجعة.', en: 'Assets submitted for review will appear here.' },
  'lp.reports.title': { ar: 'تقارير الإنتاج', en: 'Production reports' },
  'lp.reports.subtitle': { ar: 'اعرف أين يتعطل العمل وكيف يتحسن تدفق الإنتاج.', en: 'See where work slows down and how production flows.' },
  'lp.asset': { ar: 'أصل إنتاج', en: 'Production asset' },
  'lp.lesson': { ar: 'الدرس', en: 'Lesson' },
  'lp.assignee': { ar: 'المسؤول', en: 'Assignee' },
  'lp.reviewer': { ar: 'المراجع', en: 'Reviewer' },
  'lp.dueDate': { ar: 'موعد التسليم', en: 'Due date' },
  'lp.priority': { ar: 'الأولوية', en: 'Priority' },
  'lp.action.start': { ar: 'ابدأ العمل', en: 'Start work' },
  'lp.action.submit': { ar: 'إرسال للمراجعة', en: 'Submit for review' },
  'lp.action.resubmit': { ar: 'إعادة الإرسال', en: 'Resubmit' },
  'lp.action.approve': { ar: 'اعتماد', en: 'Approve' },
  'lp.action.requestChanges': { ar: 'طلب تعديلات', en: 'Request changes' },
  'lp.action.uploadFirst': { ar: 'رفع أول نسخة', en: 'Upload first version' },
  'lp.action.uploadNew': { ar: 'رفع نسخة جديدة', en: 'Upload new version' },
  'lp.action.newRevision': { ar: 'بدء نسخة جديدة', en: 'Start new revision' },
  'lp.action.newRevisionFile': { ar: 'رفع نسخة جديدة', en: 'Upload new revision' },
  'lp.action.lock': { ar: 'قفل الأصل', en: 'Lock asset' },
  'lp.action.reopen': { ar: 'إعادة فتح', en: 'Reopen' },
  'lp.action.override': { ar: 'تجاوز الاعتماد', en: 'Override dependency' },
  'lp.action.more': { ar: 'إجراءات إضافية', en: 'More actions' },
  'lp.waitingForReview': { ar: 'في انتظار المراجعة', en: 'Waiting for review' },
  'lp.blocked': { ar: 'متوقف مؤقتًا', en: 'Blocked' },
  'lp.waitingFor': { ar: 'ينتظر', en: 'Waiting for' },
  'lp.openComments': { ar: '{n} ملاحظات مفتوحة', en: '{n} open comments' },
  'lp.upload.title': { ar: 'رفع نسخة', en: 'Upload version' },
  'lp.upload.drop': { ar: 'اسحب الملف هنا أو اختره من جهازك', en: 'Drop a file here or choose one from your device' },
  'lp.upload.browse': { ar: 'اختيار ملف', en: 'Choose file' },
  'lp.upload.link': { ar: 'إضافة رابط', en: 'Add a link' },
  'lp.upload.notes': { ar: 'ملاحظات النسخة', en: 'Version notes' },
  'lp.upload.notesPlaceholder': { ar: 'ما الذي تغير في هذه النسخة؟', en: 'What changed in this version?' },
  'lp.versions.compare': { ar: 'مقارنة النسخ', en: 'Compare versions' },
  'lp.versions.reviewHistory': { ar: 'سجل المراجعة', en: 'Review history' },
  'lp.versions.none': { ar: 'لا توجد نسخ بعد.', en: 'No versions yet.' },
  'lp.comment.placeholder': { ar: 'اكتب ملاحظتك…', en: 'Write your comment…' },
  'lp.comment.send': { ar: 'إرسال الملاحظة', en: 'Send comment' },
  'lp.comment.resolve': { ar: 'حل الملاحظة', en: 'Resolve comment' },
  'lp.comment.reopen': { ar: 'إعادة فتح الملاحظة', en: 'Reopen comment' },
  'lp.comment.none': { ar: 'لا توجد ملاحظات.', en: 'No comments.' },
  'lp.comment.noneOpen': { ar: 'لا توجد ملاحظات مفتوحة.', en: 'No open comments.' },
  'lp.save.saving': { ar: 'جارٍ الحفظ…', en: 'Saving…' },
  'lp.save.saved': { ar: 'تم الحفظ', en: 'Saved' },
  'lp.save.failed': { ar: 'تعذر الحفظ', en: 'Could not save' },
  'lp.save.conflict': { ar: 'تغير المحتوى في مكان آخر.', en: 'This content changed elsewhere.' },
  'lp.save.reload': { ar: 'تحميل النسخة الأحدث', en: 'Load latest' },
  'lp.unavailable.title': { ar: 'إنتاج المحتوى غير متاح الآن', en: 'Production is unavailable right now' },
  'lp.unavailable.body': { ar: 'تأكد من تشغيل قاعدة البيانات ثم أعد المحاولة.', en: 'Make sure the database is running, then try again.' },
};

const WORDS: Record<string, Pair> = {
  dashboard: { ar: 'لوحة التحكم', en: 'Dashboard' }, courses: { ar: 'الكورسات', en: 'Courses' }, course: { ar: 'الكورس', en: 'Course' },
  lessons: { ar: 'الدروس', en: 'Lessons' }, lesson: { ar: 'الدرس', en: 'Lesson' }, production: { ar: 'الإنتاج', en: 'Production' },
  settings: { ar: 'الإعدادات', en: 'Settings' }, team: { ar: 'الفريق', en: 'Team' }, files: { ar: 'الملفات', en: 'Files' },
  activity: { ar: 'النشاط', en: 'Activity' }, review: { ar: 'المراجعة', en: 'Review' }, reviews: { ar: 'المراجعات', en: 'Reviews' },
  title: { ar: 'العنوان', en: 'Title' }, name: { ar: 'الاسم', en: 'Name' }, description: { ar: 'الوصف', en: 'Description' },
  status: { ar: 'الحالة', en: 'Status' }, progress: { ar: 'التقدم', en: 'Progress' }, empty: { ar: 'فارغ', en: 'Empty' },
  loading: { ar: 'جارٍ التحميل', en: 'Loading' }, search: { ar: 'بحث', en: 'Search' }, all: { ar: 'الكل', en: 'All' },
  assigned: { ar: 'مسند', en: 'Assigned' }, waiting: { ar: 'ينتظر', en: 'Waiting' }, completed: { ar: 'مكتمل', en: 'Completed' },
  overdue: { ar: 'متأخر', en: 'Overdue' }, changes: { ar: 'تعديلات', en: 'Changes' }, requested: { ar: 'مطلوب', en: 'Requested' },
  save: { ar: 'حفظ', en: 'Save' }, saved: { ar: 'تم الحفظ', en: 'Saved' }, add: { ar: 'إضافة', en: 'Add' }, remove: { ar: 'إزالة', en: 'Remove' },
  create: { ar: 'إنشاء', en: 'Create' }, upload: { ar: 'رفع', en: 'Upload' }, download: { ar: 'تنزيل', en: 'Download' },
  start: { ar: 'بدء', en: 'Start' }, submit: { ar: 'إرسال', en: 'Submit' }, approve: { ar: 'اعتماد', en: 'Approve' },
  outline: { ar: 'المخطط', en: 'Outline' }, ppt: { ar: 'العرض التقديمي', en: 'PPT' }, script: { ar: 'السكريبت', en: 'Script' },
  voice: { ar: 'التعليق الصوتي', en: 'Voice' }, video: { ar: 'الفيديو', en: 'Video' },
  OUTLINE: { ar: 'المخطط', en: 'Outline' }, PPT: { ar: 'العرض التقديمي', en: 'PPT' }, SCRIPT: { ar: 'السكريبت', en: 'Script' },
  VOICE_OVER: { ar: 'التعليق الصوتي', en: 'Voice Over' }, VIDEO: { ar: 'الفيديو', en: 'Video' },
  NOT_STARTED: { ar: 'لم يبدأ', en: 'Not started' }, ASSIGNED: { ar: 'مُسند', en: 'Assigned' }, IN_PROGRESS: { ar: 'قيد التنفيذ', en: 'In progress' },
  SUBMITTED: { ar: 'مُرسل للمراجعة', en: 'Submitted' }, UNDER_REVIEW: { ar: 'قيد المراجعة', en: 'Under review' },
  CHANGES_REQUESTED: { ar: 'مطلوب تعديل', en: 'Changes requested' }, RESUBMITTED: { ar: 'أُعيد إرساله', en: 'Resubmitted' }, APPROVED: { ar: 'معتمد', en: 'Approved' }, LOCKED: { ar: 'مقفل', en: 'Locked' },
  LOW: { ar: 'منخفضة', en: 'Low' }, NORMAL: { ar: 'عادية', en: 'Normal' }, HIGH: { ar: 'عالية', en: 'High' }, URGENT: { ar: 'عاجلة', en: 'Urgent' },
  ON_TRACK: { ar: 'في المسار الصحيح', en: 'On track' }, AT_RISK: { ar: 'في خطر', en: 'At risk' }, DELAYED: { ar: 'متأخر', en: 'Delayed' }, COMPLETED: { ar: 'مكتمل', en: 'Completed' },
};

function humanize(token: string): Pair {
  const exact = WORDS[token];
  if (exact) return exact;
  const spaced = token.replace(/([a-z])([A-Z])/g, '$1 $2').replaceAll('_', ' ').toLowerCase();
  return { ar: spaced, en: spaced.replace(/\b\w/g, (char) => char.toUpperCase()) };
}

/** Returns readable feature copy for a key not yet added to the exact table. */
export function learningProductionString(key: string, lang: 'ar' | 'en') {
  const exact = LP_STRINGS[key];
  if (exact) return exact[lang];
  if (!key.startsWith('lp.')) return key;
  const parts = key.split('.').slice(1);
  const labels = parts.map(humanize);
  return labels.map((label) => label[lang]).join(lang === 'ar' ? ' · ' : ' · ');
}
