/**
 * E-Learning Production — the copy of the rebuilt screens. See
 * studioStrings.ts for the conventions; this file holds the sentences and
 * labels, that one the enum families and history.
 */

type Pair = { ar: string; en: string };

export const SCREEN_STRINGS: Record<string, Pair> = {
  /* ── shared ────────────────────────────────────────────────── */
  'lp.action.next': { ar: 'التالي', en: 'Next' },
  'lp.action.retry': { ar: 'إعادة المحاولة', en: 'Try again' },
  'lp.breadcrumb': { ar: 'مسار التنقل', en: 'Breadcrumb' },
  'lp.chrome.show': { ar: 'إظهار شريط مساحة العمل', en: 'Show the workspace bar' },
  'lp.chrome.hide': { ar: 'إخفاء شريط مساحة العمل', en: 'Hide the workspace bar' },
  'lp.nav.guide': { ar: 'كيف يعمل', en: 'How it works' },
  'lp.nav.templates': { ar: 'قوالب سير العمل', en: 'Workflow templates' },
  'lp.people.search': { ar: 'ابحث بالاسم أو الوظيفة أو القسم', en: 'Search by name, title or department' },
  'lp.people.everyone': { ar: 'كل الموظفين', en: 'Everyone' },
  'lp.people.noMatch': { ar: 'لا يوجد أحد بهذا الاسم', en: 'Nobody matches' },
  'lp.people.none': { ar: 'لا يوجد موظفون نشطون في مساحة العمل', en: 'There are no active people in the workspace' },
  'lp.people.loadFailed': { ar: 'تعذر تحميل قائمة الموظفين — أعد تحميل الصفحة، وإن تكرر فصلاحيتك لا تسمح بالإسناد', en: 'The people list did not load — reload the page; if it persists, your role cannot assign work' },
  'lp.people.choose': { ar: 'اختر شخصًا', en: 'Choose a person' },
  'lp.people.later': { ar: 'يُحدد لاحقًا', en: 'Decide later' },
  'lp.people.optional': { ar: 'اختياري', en: 'Optional' },
  'lp.people.unassigned': { ar: 'غير مسند', en: 'Unassigned' },
  'lp.reason.label': { ar: 'السبب', en: 'Reason' },
  'lp.reason.kept': { ar: 'يُحفظ السبب في السجل مع اسمك والتاريخ.', en: 'The reason is kept in the history with your name and the date.' },
  'lp.unsaved.confirm': { ar: 'لديك نص لم يُحفظ. هل تريد الإغلاق وفقدانه؟', en: 'You have unsaved text. Close and lose it?' },
  'lp.blocker.stage': { ar: 'مرحلة «{stage}»', en: 'Stage “{stage}”' },
  'lp.blocker.task': { ar: 'مهمة «{task}»', en: 'Task “{task}”' },
  'lp.blocker.asset': { ar: 'اعتماد {asset}', en: 'Approval of the {asset}' },
  'lp.blocker.with': { ar: 'لدى {who}', en: 'with {who}' },
  'lp.gate.progress': { ar: '{done} من {total}', en: '{done} of {total}' },
  'lp.ai.assisted': { ar: 'أُعدت بمساعدة أداة ذكاء اصطناعي', en: 'Made with an AI tool' },
  'lp.ai.tool': { ar: 'الأداة', en: 'Tool' },
  'lp.ai.toolPlaceholder': { ar: 'مثل GPT أو Docki أو Think', en: 'e.g. GPT, Docki, Think' },
  'lp.ai.reviewed': { ar: 'تُراجع النسخة ويعتمدها شخص غير من أرسلها، كأي نسخة أخرى.', en: 'The version is still reviewed and approved by someone other than the sender.' },
  'lp.ai.label': { ar: 'بمساعدة الذكاء الاصطناعي · {tool}', en: 'AI-assisted · {tool}' },
  'lp.asset.notApplicable': { ar: 'لا ينطبق على هذا الدرس', en: 'Not applicable to this lesson' },
  'lp.asset.notApplicableShort': { ar: 'لا ينطبق', en: 'N/A' },
  'lp.asset.markNotApplicable': { ar: 'تعليم بأنه لا ينطبق', en: 'Mark not applicable' },
  'lp.asset.notApplicableBody': {
    ar: 'يخرج هذا الملف من حساب التقدم والبوابات، وتبقى نسخه ومراجعاته كما هي. يمكن إعادته لاحقًا.',
    en: 'The asset leaves the progress count and the gates; its versions and reviews stay as they are. You can bring it back later.',
  },
  'lp.asset.bringBack': { ar: 'إعادته إلى الدرس', en: 'Bring it back' },
  'lp.matrix.notInWorkflow': { ar: 'ليس ضمن سير عمل هذا الدرس', en: 'Not part of this lesson’s workflow' },

  /* ── lesson cells: states in plain words ───────────────────── */
  'lp.blocked': { ar: 'بانتظار خطوة سابقة', en: 'Waiting for an earlier step' },
  'lp.waitsOn': { ar: 'ينتظر {stages}', en: 'Waits for {stages}' },
  'lp.quick.BLOCKED': { ar: 'بانتظار خطوة سابقة', en: 'Waiting' },
  'lp.error.CHECKLIST_INCOMPLETE': {
    ar: 'علّم كل بنود القائمة المطلوبة أولًا — أو اجعل غير المنطبق منها «لا ينطبق» مع ذكر السبب.',
    en: 'Tick every required checklist line first — or mark the ones that do not apply as N/A, with a reason.',
  },
  'lp.listSeparator': { ar: '، ', en: ', ' },
  'lp.strip.next': { ar: 'بعدها: {stage}', en: 'Then: {stage}' },
  'lp.strip.done': { ar: 'اكتملت {done} من {total} مراحل', en: '{done} of {total} stages done' },
  'lp.strip.openPlan': { ar: 'عرض الخطة', en: 'Open the plan' },
  'lp.cell.inReview': { ar: 'قيد المراجعة', en: 'In review' },
  'lp.cell.ready': { ar: 'جاهز للبدء', en: 'Ready to start' },
  'lp.cell.unassigned': { ar: 'غير مُسند', en: 'Not assigned' },
  'lp.lessons.next.done': { ar: 'اكتمل الدرس — كل ملفاته معتمدة', en: 'Lesson complete — every asset approved' },
  'lp.lessons.next.work': { ar: 'التالي: {stage} — عند {who}', en: 'Next: {stage} — with {who}' },
  'lp.lessons.next.unassigned': { ar: 'التالي: {stage} — لم يُسند لأحد بعد', en: 'Next: {stage} — not assigned yet' },
  'lp.lessons.next.review': { ar: '{stage} بانتظار مراجعة {who}', en: '{stage} is waiting for {who} to review' },
  'lp.lessons.next.reviewAnyone': { ar: '{stage} بانتظار المراجعة', en: '{stage} is waiting for review' },
  'lp.lessons.next.changes': { ar: '{stage}: مطلوب تعديل — عند {who}', en: '{stage}: changes needed — with {who}' },
  'lp.lessons.next.overdue': { ar: '{stage} متأخر — عند {who}', en: '{stage} is overdue — with {who}' },
  'lp.lessons.progressOf': { ar: '{done} من {total}', en: '{done} of {total}' },
  'lp.lessons.orderHint': {
    ar: 'الترتيب: المخطط أولًا، ثم العرض التقديمي والسكريبت، ثم التعليق الصوتي بعد السكريبت، والفيديو في النهاية.',
    en: 'Order: the outline first, then slides and script, the voice-over after the script, and the video last.',
  },

  /* ── what each role does, in one line ──────────────────────── */
  'lp.roleHint.PRODUCTION_MANAGER': { ar: 'يدير الدورة كلها: يوزع العمل ويعتمد ويجهّز الإصدار.', en: 'Runs the whole program: hands out work, approves, prepares the release.' },
  'lp.roleHint.COURSE_MANAGER': { ar: 'شريك المدير في الإدارة: يوزع ويعتمد، ويعتمد الإصدار الذي جهّزه غيره.', en: 'Co-manages: assigns and approves, and signs off a release someone else prepared.' },
  'lp.roleHint.SUBJECT_MATTER_EXPERT': { ar: 'يراجع دقة المحتوى ويعتمد المخططات والسكريبتات.', en: 'Checks the content is right; approves outlines and scripts.' },
  'lp.roleHint.INSTRUCTIONAL_DESIGNER': { ar: 'يراجع المنهج ويصمم تجربة التعلم ويعتمد التعديلات عليه.', en: 'Reviews the curriculum, designs the learning experience, approves changes to it.' },
  'lp.roleHint.OUTLINE_WRITER': { ar: 'يكتب مخطط كل درس — أول ملف في كل درس.', en: 'Writes each lesson’s outline — the first file of every lesson.' },
  'lp.roleHint.SCRIPT_WRITER': { ar: 'يكتب سكريبت الدرس بعد اعتماد المخطط.', en: 'Writes the lesson script once the outline is approved.' },
  'lp.roleHint.PPT_DESIGNER': { ar: 'يصمم العرض التقديمي بعد اعتماد المخطط.', en: 'Designs the slides once the outline is approved.' },
  'lp.roleHint.VOICE_OVER_ARTIST': { ar: 'يسجل التعليق الصوتي بعد اعتماد السكريبت.', en: 'Records the voice-over once the script is approved.' },
  'lp.roleHint.AUDIO_REVIEWER': { ar: 'يراجع جودة التعليق الصوتي ويعتمده.', en: 'Reviews and approves the voice-over.' },
  'lp.roleHint.VIDEO_EDITOR': { ar: 'يُخرج الفيديو النهائي بعد اعتماد العرض والسكريبت والصوت.', en: 'Produces the final video once slides, script and voice are approved.' },
  'lp.roleHint.QUALITY_REVIEWER': { ar: 'يراجع جودة العروض والصوت والفيديو ويعتمدها.', en: 'Reviews and approves slides, audio and video.' },
  'lp.roleHint.VIEWER': { ar: 'يتابع فقط، بلا صلاحية تعديل.', en: 'Follows along; cannot change anything.' },
  'lp.roleHint.RESEARCHER': { ar: 'يبحث السوق والمنافسين ويكتب مسودة المنهج.', en: 'Researches the market and competitors and drafts the curriculum.' },
  'lp.roleHint.EXPERT_COORDINATOR': { ar: 'يبحث عن الخبراء ويتواصل معهم حتى التعاقد.', en: 'Finds experts and takes them through to a contract.' },
  'lp.roleHint.TECHNICAL_PM': { ar: 'يتابع التنفيذ التقني ويطبق التصحيحات.', en: 'Oversees technical delivery and applies corrections.' },
  'lp.roleHint.DELIVERY_PM': { ar: 'يتابع تسليم البرنامج للعميل.', en: 'Oversees delivering the program to the client.' },
  'lp.roleHint.TECHNICAL_CONSULTANT': { ar: 'يراجع المنهج النهائي والتقييمات فنيًا ويعتمدها.', en: 'Technically reviews and approves the final curriculum and assessments.' },
  'lp.roleHint.LEARNING_OPERATIONS': { ar: 'يجهّز البرنامج على المنصة وينشره ويصلح مشكلاتها.', en: 'Sets the program up on the platform, deploys it, fixes platform issues.' },
  'lp.roleHint.MARKETING': { ar: 'يجهّز الغلاف والصورة المصغرة وصفحة البرنامج.', en: 'Prepares the cover, thumbnail and landing page.' },
  'lp.roleHint.UAT_COORDINATOR': { ar: 'ينظم اختبار القبول ويجمع نتائجه ويعتمده.', en: 'Runs user acceptance testing, collects results, signs it off.' },
  'lp.roleHint.UAT_TESTER': { ar: 'يجرب البرنامج كمتعلم ويسجل المشكلات.', en: 'Tries the program as a learner and logs issues.' },
  'lp.newRun.section.management': { ar: 'إدارة البرنامج', en: 'Running the program' },
  'lp.newRun.section.program': { ar: 'مراحل البرنامج', en: 'Program stages' },
  'lp.newRun.section.programHint': { ar: 'من يعمل على مهام المراحل: البحث والمنهج والتصميم والنشر واختبار القبول.', en: 'Who works the stage tasks: research, curriculum, design, deployment, UAT.' },
  'lp.newRun.section.lessons': { ar: 'إنتاج الدروس', en: 'Making the lessons' },
  'lp.newRun.section.lessonsHint': {
    ar: 'كل درس جديد يُسند تلقائيًا لهؤلاء: من يصنع كل ملف ومن يراجعه. يمكن تغيير الإسناد لاحقًا لأي درس.',
    en: 'Every new lesson is assigned to these people automatically — who makes each file and who reviews it. Any lesson can be reassigned later.',
  },

  /* ── columns ───────────────────────────────────────────────── */
  'lp.col.action': { ar: 'الإجراء', en: 'Action' },
  'lp.col.active': { ar: 'قيد العمل', en: 'Active' },
  'lp.col.approvedShort': { ar: 'معتمد', en: 'Approved' },
  'lp.col.approver': { ar: 'المعتمِد', en: 'Approver' },
  'lp.col.checks': { ar: 'البنود', en: 'Checks' },
  'lp.col.content': { ar: 'المحتوى', en: 'Content' },
  'lp.col.course': { ar: 'الكورس', en: 'Course' },
  'lp.col.due': { ar: 'الموعد', en: 'Due' },
  'lp.col.health': { ar: 'الحالة العامة', en: 'Health' },
  'lp.col.issues': { ar: 'المشكلات', en: 'Issues' },
  'lp.col.lesson': { ar: 'الدرس', en: 'Lesson' },
  'lp.col.lessons': { ar: 'الدروس', en: 'Lessons' },
  'lp.col.manager': { ar: 'المدير', en: 'Manager' },
  'lp.col.overdue': { ar: 'متأخر', en: 'Overdue' },
  'lp.col.owner': { ar: 'المسؤول', en: 'Owner' },
  'lp.col.person': { ar: 'الشخص', en: 'Person' },
  'lp.col.priority': { ar: 'الأولوية', en: 'Priority' },
  'lp.col.reviewing': { ar: 'يراجع', en: 'Reviewing' },
  'lp.col.run': { ar: 'دورة الإنتاج', en: 'Run' },
  'lp.col.stage': { ar: 'المرحلة', en: 'Stage' },
  'lp.col.status': { ar: 'الحالة', en: 'Status' },
  'lp.col.target': { ar: 'الموعد المستهدف', en: 'Target' },
  'lp.col.task': { ar: 'المهمة', en: 'Task' },
  'lp.col.waiting': { ar: 'بانتظار الاعتماد', en: 'Waiting' },
  'lp.col.what': { ar: 'العمل', en: 'What' },
  'lp.col.where': { ar: 'أين', en: 'Where' },
  'lp.col.workflow': { ar: 'سير العمل', en: 'Workflow' },

  /* ── fields and filters ────────────────────────────────────── */
  'lp.field.course': { ar: 'الكورس', en: 'Course' },
  'lp.field.courseCode': { ar: 'كود الكورس', en: 'Course code' },
  'lp.field.courseName': { ar: 'اسم الكورس', en: 'Course name' },
  'lp.field.description': { ar: 'الوصف', en: 'Description' },
  'lp.field.manager': { ar: 'مدير الإنتاج', en: 'Production manager' },
  'lp.field.runTitle': { ar: 'عنوان الدورة', en: 'Run title' },
  'lp.field.runTitleHint': { ar: 'اختياري — مثل «دفعة ربيع 2027».', en: 'Optional — e.g. “Spring 2027 cohort”.' },
  'lp.field.startDate': { ar: 'تاريخ البدء', en: 'Start date' },
  'lp.field.targetDate': { ar: 'الموعد المستهدف', en: 'Target date' },
  'lp.filter.anyHealth': { ar: 'كل الحالات', en: 'Any health' },
  'lp.filter.anyScenario': { ar: 'كل الطرق', en: 'Any way' },
  'lp.filter.health': { ar: 'الحالة العامة', en: 'Health' },
  'lp.filter.scenario': { ar: 'طريقة الإنتاج', en: 'Way' },

  /* ── dashboard ─────────────────────────────────────────────── */
  'lp.dashboard.lede': { ar: 'كل دورات الإنتاج الجارية: أين هي، وما الذي ينتظر الاعتماد، وما المتأخر، ومن يحمل العمل.', en: 'Every production run in flight: where it is, what waits for approval, what is late, and who carries the work.' },
  'lp.dashboard.yours': { ar: 'لديك {n} عمل الآن', en: '{n} things for you now' },
  'lp.dashboard.yourReviews': { ar: '{n} بانتظار قرارك', en: '{n} waiting for your decision' },
  'lp.dashboard.figures': { ar: 'الأرقام الرئيسية', en: 'Key figures' },
  'lp.dashboard.runs': { ar: 'دورات الإنتاج الجارية', en: 'Runs in flight' },
  'lp.dashboard.searchRuns': { ar: 'ابحث باسم الكورس أو كوده', en: 'Search course name or code' },
  'lp.dashboard.noRuns': { ar: 'لا توجد دورات إنتاج جارية', en: 'No production runs in flight' },
  'lp.dashboard.noRunsBody': { ar: 'ابدأ دورة إنتاج لبرنامج جديد أو لتطوير برنامج قائم.', en: 'Start a run for a new program or to revamp an existing one.' },
  'lp.dashboard.noMatch': { ar: 'لا توجد دورات تطابق التصفية', en: 'No runs match these filters' },
  'lp.dashboard.pipeline': { ar: 'أين تقف الدورات', en: 'Where runs are' },
  'lp.dashboard.pipelineEmpty': { ar: 'لا توجد دورات جارية.', en: 'No runs in flight.' },
  'lp.dashboard.bottleneck': { ar: 'أكثر المراحل ازدحامًا الآن: {stage}.', en: 'Busiest stage right now: {stage}.' },
  'lp.dashboard.workloadEmpty': { ar: 'لا أحد يحمل عملًا مفتوحًا الآن.', en: 'Nobody is carrying open work right now.' },
  'lp.dashboard.releases': { ar: 'إصدارات آخر 90 يومًا', en: 'Releases, last 90 days' },
  'lp.dashboard.releasesEmpty': { ar: 'لم يُنشر إصدار في آخر 90 يومًا.', en: 'Nothing published in the last 90 days.' },
  'lp.kpi.activeRuns': { ar: 'دورات نشطة', en: 'Active runs' },
  'lp.kpi.legacyRuns': { ar: 'إضافة إلى {n} من الإنتاج السابق', en: 'plus {n} legacy' },
  'lp.kpi.pendingApprovals': { ar: 'بانتظار الاعتماد', en: 'Waiting for approval' },
  'lp.kpi.blockingIssues': { ar: 'مشكلات عالية أو حرجة', en: 'High or critical issues' },
  'lp.kpi.atRisk': { ar: 'في خطر أو متأخرة', en: 'At risk or delayed' },
  'lp.kpi.released90': { ar: 'نُشرت خلال 90 يومًا', en: 'Released in 90 days' },

  /* ── courses ───────────────────────────────────────────────── */
  'lp.courses.title': { ar: 'الكورسات', en: 'Courses' },
  'lp.courses.lede': { ar: 'كل كورس مع دورة الإنتاج الجارية له، وأين وصلت، وكم من محتواه معتمد.', en: 'Each course with its run in flight, where it is, and how much of its content is approved.' },
  'lp.courses.active': { ar: 'نشطة', en: 'Active' },
  'lp.courses.onHold': { ar: 'متوقفة', en: 'On hold' },
  'lp.courses.archived': { ar: 'مؤرشفة', en: 'Archived' },
  'lp.courses.search': { ar: 'ابحث باسم الكورس أو كوده', en: 'Search name or code' },
  'lp.courses.sort': { ar: 'الترتيب', en: 'Sort' },
  'lp.courses.sort.recent': { ar: 'الأحدث نشاطًا', en: 'Recent activity' },
  'lp.courses.sort.name': { ar: 'الاسم', en: 'Name' },
  'lp.courses.sort.target': { ar: 'الموعد المستهدف', en: 'Target date' },
  'lp.courses.sort.progress': { ar: 'التقدم', en: 'Progress' },
  'lp.courses.noRun': { ar: 'بلا دورة', en: 'No run' },
  'lp.courses.empty': { ar: 'لا توجد كورسات هنا', en: 'No courses here' },
  'lp.courses.emptyBody': { ar: 'ابدأ دورة إنتاج جديدة لإنشاء كورس.', en: 'Start a production run to create a course.' },
  'lp.courses.noMatch': { ar: 'لا يوجد كورس بهذا الاسم', en: 'No course matches' },

  /* ── runs ──────────────────────────────────────────────────── */
  'lp.run.new': { ar: 'دورة إنتاج جديدة', en: 'New production run' },
  'lp.run.number': { ar: 'الدورة {n}', en: 'Run {n}' },
  'lp.run.stageOf': { ar: 'المرحلة {n} من {total}', en: 'Stage {n} of {total}' },
  'lp.run.allStagesDone': { ar: 'اكتملت كل المراحل', en: 'All stages done' },
  'lp.run.legacyNoStages': { ar: 'بلا مراحل متتبعة', en: 'No tracked stages' },
  'lp.run.nowAt': { ar: 'الآن في:', en: 'Now at:' },
  'lp.run.none': { ar: 'لا توجد دورة إنتاج لهذا الكورس بعد', en: 'This course has no production run yet' },
  'lp.run.noneTitle': { ar: 'لا توجد دورة إنتاج', en: 'No production run' },
  'lp.run.noneBody': { ar: 'ابدأ دورة إنتاج لتتبع المراحل والمهام والإصدار.', en: 'Start a run to track its stages, tasks and release.' },
  'lp.run.viewing': { ar: 'عرض', en: 'Viewing' },
  'lp.run.startAnother': { ar: 'بدء دورة جديدة', en: 'Start a new run' },
  'lp.run.menu': { ar: 'إجراءات الدورة', en: 'Run actions' },
  'lp.run.hold': { ar: 'إيقاف مؤقت', en: 'Put on hold' },
  'lp.run.resume': { ar: 'استئناف', en: 'Resume' },
  'lp.run.cancel': { ar: 'إلغاء الدورة', en: 'Cancel the run' },
  'lp.run.cancelBody': { ar: 'تبقى الدورة وسجلها وملفاتها كما هي، لكن لا يمكن العمل عليها بعد الإلغاء، وتُسحب أي نسخة إصدار مرشحة.', en: 'The run, its history and its files stay, but no more work happens on it, and any release candidate is withdrawn.' },
  'lp.run.cancelConfirm': { ar: 'إلغاء الدورة', en: 'Cancel the run' },
  'lp.run.createdNotice': { ar: 'بدأت دورة الإنتاج. أُبلغ كل من أُسندت إليه مهمة، وأول مرحلة جاهزة.', en: 'The run has started. Everyone with a task was told, and the first stage is ready.' },
  'lp.run.onHoldNotice': { ar: 'هذه الدورة متوقفة مؤقتًا — لا يمكن العمل على مهامها حتى تُستأنف.', en: 'This run is on hold — its tasks cannot move until it resumes.' },
  'lp.course.settings': { ar: 'إعدادات الكورس', en: 'Course settings' },
  'lp.course.tabs': { ar: 'أقسام الكورس', en: 'Course sections' },
  'lp.tab.plan': { ar: 'الخطة والمراحل', en: 'Plan & stages' },
  'lp.tab.curriculum': { ar: 'المنهج والدروس', en: 'Curriculum & lessons' },
  'lp.tab.qa': { ar: 'الجودة والإصدار', en: 'QA & release' },
  'lp.files.files': { ar: 'الملفات', en: 'Files' },
  'lp.files.activity': { ar: 'السجل', en: 'Activity' },

  /* ── new run ───────────────────────────────────────────────── */
  'lp.newRun.lede': { ar: 'اختر الطريقة، واملأ الأساسيات، وحدد الفريق، وراجع المراحل والمهام قبل الإنشاء. لا حاجة لإضافة الدروس الآن.', en: 'Choose the way, fill in the basics, pick the team, and review the stages and tasks before anything is created. No lessons needed yet.' },
  'lp.newRun.steps': { ar: 'خطوات الإنشاء', en: 'Steps' },
  'lp.newRun.stepN': { ar: 'الخطوة {n}', en: 'Step {n}' },
  'lp.newRun.step.way': { ar: 'الطريقة', en: 'Way' },
  'lp.newRun.step.basics': { ar: 'الأساسيات', en: 'Basics' },
  'lp.newRun.step.team': { ar: 'الفريق', en: 'Team' },
  'lp.newRun.step.review': { ar: 'المراجعة', en: 'Review' },
  'lp.newRun.wayQuestion': { ar: 'كيف سيُنتج هذا البرنامج؟', en: 'How will this program be produced?' },
  'lp.newRun.courseMode': { ar: 'الكورس', en: 'Course' },
  'lp.newRun.newCourse': { ar: 'كورس جديد', en: 'A new course' },
  'lp.newRun.existingCourse': { ar: 'كورس موجود', en: 'An existing course' },
  'lp.newRun.existingHint': { ar: 'يظهر هنا فقط ما لا توجد له دورة جارية.', en: 'Only courses without a run in progress are listed.' },
  'lp.newRun.revampCourseHint': { ar: 'التطوير يكون لكورس موجود دائمًا.', en: 'A revamp is always of an existing course.' },
  'lp.newRun.chooseCourse': { ar: 'اختر كورسًا', en: 'Choose a course' },
  'lp.newRun.source': { ar: 'يبدأ التطوير من', en: 'Revamp starting from' },
  'lp.newRun.sourceHint': { ar: 'يُحفظ ما في هذا الإصدار كنقطة مقارنة، ولا يتغير إصداره القديم.', en: 'This release is kept as the baseline to compare against; the old release is never changed.' },
  'lp.newRun.currentContent': { ar: 'المحتوى الحالي (لا يوجد إصدار مسجل)', en: 'The current content (no release recorded)' },
  'lp.newRun.baselineNote': { ar: 'سيُسجل المحتوى الحالي كخط أساس «مسجل» وليس «منشورًا ومتحققًا منه».', en: 'The current content will be recorded as a baseline — marked as recorded, not as a verified publication.' },
  'lp.newRun.closesLegacy': { ar: 'لهذا الكورس إنتاج سابق جارٍ؛ سيُغلق مع حفظ سجله، وتصبح الدورة الجديدة هي الجارية.', en: 'This course has a legacy run in progress; it will be closed with its history kept, and the new run takes over.' },
  'lp.newRun.expertContracted': { ar: 'يوجد خبير متعاقد بالفعل', en: 'An expert is already contracted' },
  'lp.newRun.expertContractedHint': { ar: 'تُتخطى مرحلة استقطاب الخبراء، ويُحفظ السبب في السجل.', en: 'The expert acquisition stage is skipped and the reason is kept in the history.' },
  'lp.newRun.expertPerson': { ar: 'الخبير', en: 'The expert' },
  'lp.newRun.expertReason': { ar: 'السبب (مثل رقم العقد)', en: 'Reason (e.g. the contract)' },
  'lp.newRun.teamHint': { ar: 'الدور الذي يشغله شخص واحد تُسند مهامه إليه تلقائيًا.', en: 'A role held by one person gets that role’s tasks automatically.' },
  'lp.newRun.managerNote': { ar: 'مدير الإنتاج يُضاف تلقائيًا ويتولى مهام الإدارة والإصدار.', en: 'The production manager is added automatically and holds the management and release tasks.' },
  'lp.newRun.previewTitle': { ar: '{template} · النسخة {version}', en: '{template} · version {version}' },
  'lp.newRun.countStages': { ar: '{n} مراحل', en: '{n} stages' },
  'lp.newRun.countRequired': { ar: '{n} مهمة مطلوبة', en: '{n} required tasks' },
  'lp.newRun.countApprovals': { ar: '{n} اعتماد', en: '{n} approvals' },
  'lp.newRun.countProposed': { ar: '{n} مقترح', en: '{n} proposals' },
  'lp.newRun.stageTasks': { ar: '{n} مهام', en: '{n} tasks' },
  'lp.newRun.stageGates': { ar: '{n} بوابة تلقائية', en: '{n} automatic gates' },
  'lp.newRun.willSkip': { ar: 'ستُتخطى', en: 'Will be skipped' },
  'lp.newRun.uncovered': { ar: 'أدوار بلا أشخاص بعد: {roles}. ستبقى مهامها غير مسندة حتى يسندها المدير.', en: 'Roles without people yet: {roles}. Their tasks stay unassigned until the manager hands them out.' },
  'lp.newRun.noLessonsYet': { ar: 'تُضاف الدروس عندما يصل المنهج إليها — لا حاجة لإضافتها الآن.', en: 'Lessons are added when the curriculum gets there — no need to add them now.' },
  'lp.newRun.create': { ar: 'إنشاء دورة الإنتاج', en: 'Create the run' },

  /* ── overview ──────────────────────────────────────────────── */
  'lp.overview.where': { ar: 'أين وصلت الدورة', en: 'Where the run is' },
  'lp.overview.nextGate': { ar: 'البوابة التالية: {stage}', en: 'Next gate: {stage}' },
  'lp.overview.allDone': { ar: 'اكتملت كل المراحل', en: 'Every stage is done' },
  'lp.overview.allDoneBody': { ar: 'لا يوجد شيء بانتظار أحد في هذه الدورة.', en: 'Nothing in this run is waiting on anyone.' },
  'lp.overview.openStage': { ar: 'فتح المرحلة', en: 'Open the stage' },
  'lp.overview.stageWaits': { ar: 'هذه المرحلة بانتظار:', en: 'This stage is waiting for:' },
  'lp.overview.approvals': { ar: 'بانتظار الاعتماد ({n})', en: 'Waiting for approval ({n})' },
  'lp.overview.noApprovals': { ar: 'لا شيء بانتظار الاعتماد.', en: 'Nothing is waiting for approval.' },
  'lp.overview.reviewer': { ar: 'المعتمِد:', en: 'Approver:' },
  'lp.overview.assetReviews': { ar: 'مراجعات ملفات الدروس في شاشة الإنتاج', en: 'Lesson asset reviews are in Production' },
  'lp.overview.overdue': { ar: 'المتأخر ({n})', en: 'Overdue ({n})' },
  'lp.overview.noOverdue': { ar: 'لا يوجد عمل متأخر.', en: 'Nothing is late.' },
  'lp.overview.assetsOverdue': { ar: '{n} ملف درس متأخر — عرضها', en: '{n} lesson assets overdue — show them' },
  'lp.overview.progress': { ar: 'التقدم', en: 'Progress' },
  'lp.overview.health': { ar: 'الحالة العامة', en: 'Health' },
  'lp.overview.healthy': { ar: 'لا توجد مؤشرات تأخر.', en: 'No sign of delay.' },
  'lp.overview.who': { ar: 'من المسؤول', en: 'Who is responsible' },
  'lp.overview.onTheGate': { ar: 'على البوابة الحالية', en: 'On the current gate' },
  'lp.overview.template': { ar: 'قالب سير العمل: النسخة {version}', en: 'Workflow template: version {version}' },
  'lp.overview.releases': { ar: 'الإصدارات', en: 'Releases' },
  'lp.progress.workflow': { ar: 'سير العمل', en: 'Workflow' },
  'lp.progress.workflowExplain': { ar: '{done} من {total} مهمة مطلوبة منجزة.', en: '{done} of {total} gating tasks done.' },
  'lp.progress.waivedExplain': { ar: 'خارج الحساب بسبب مسجل: {waived} مهمة متخطاة و{skipped} مرحلة متخطاة.', en: 'Left out with a recorded reason: {waived} waived tasks, {skipped} skipped stages.' },
  'lp.progress.content': { ar: 'محتوى الدروس', en: 'Lesson content' },
  'lp.progress.contentExplain': { ar: '{done} من {total} ملف درس معتمد.', en: '{done} of {total} lesson assets approved.' },
  'lp.progress.contentNone': { ar: 'لا توجد دروس بعد.', en: 'No lessons yet.' },
  'lp.progress.contentNotDone': { ar: 'اكتمال المحتوى لا يعني اكتمال البرنامج — ما زال سير العمل مفتوحًا.', en: 'Content complete is not program complete — the workflow is still open.' },
  'lp.progress.readiness': { ar: 'جاهزية الإصدار', en: 'Release readiness' },
  'lp.progress.published': { ar: 'نُشر {label} في {day}', en: '{label} published on {day}' },
  'lp.progress.notPublished': { ar: 'لم يُنشر إصدار من هذه الدورة.', en: 'Nothing from this run is published.' },
  'lp.readiness.andMore': { ar: 'و{n} مراحل أخرى', en: 'and {n} more' },
  'lp.readiness.met': { ar: 'متحقق', en: 'met' },
  'lp.readiness.notMet': { ar: 'غير متحقق', en: 'not met' },
  'lp.readiness.openStages': { ar: 'مفتوحة: {stages}', en: 'Open: {stages}' },
  'lp.readiness.blockingIssues': { ar: '{n} مشكلة مفتوحة', en: '{n} open' },
  'lp.readiness.notAssessed': { ar: 'الجاهزية غير مقيّمة', en: 'Readiness not assessed' },

  /* ── legacy ────────────────────────────────────────────────── */
  'lp.legacy.title': { ar: 'إنتاج سُجل قبل تتبع سير العمل', en: 'Production recorded before workflow tracking' },
  'lp.legacy.body': { ar: 'نُقل هذا الكورس من النظام السابق كما هو: دروسه وملفاته ونسخها واعتماداتها وسجلها محفوظة كاملة.', en: 'This course came over from the earlier system as it was: its lessons, files, versions, approvals and history are all kept.' },
  'lp.legacy.nothingAssumed': { ar: 'لم يُفترض شيء عن المنهج أو النشر أو اختبار القبول أو الإصدار — لم تكن هذه المراحل متتبعة.', en: 'Nothing is assumed about its curriculum, deployment, UAT or release — those were not tracked.' },
  'lp.legacy.adoptTitle': { ar: 'اعتماد سير عمل', en: 'Adopt a workflow' },
  'lp.legacy.adoptBody': { ar: 'تُنشأ المراحل والمهام من جديد، ولا يُعلّم شيء كمنجز: البوابات التلقائية تقرأ الملفات المعتمدة فعلًا، وباقي المهام تنتظر أدلتها.', en: 'Stages and tasks are created fresh and nothing is marked done: automatic gates read the assets actually approved, and every other task waits for its evidence.' },
  'lp.legacy.adoptExpert': { ar: 'سير عمل بقيادة خبير', en: 'Expert-led workflow' },
  'lp.legacy.adoptAi': { ar: 'سير عمل بالذكاء الاصطناعي', en: 'AI-assisted workflow' },
  'lp.legacy.revamp': { ar: 'بدء تطوير من المحتوى الحالي', en: 'Start a revamp from the current content' },
  'lp.legacy.adopted': { ar: 'اعتُمد سير العمل.', en: 'Workflow adopted.' },
  'lp.legacy.noPlan': { ar: 'لا توجد خطة لهذه الدورة', en: 'This run has no plan' },
  'lp.legacy.toOverview': { ar: 'إلى النظرة العامة', en: 'Go to the overview' },

  /* ── plan ──────────────────────────────────────────────────── */
  'lp.plan.stages': { ar: 'مراحل الدورة', en: 'Run stages' },
  'lp.plan.filter': { ar: 'تصفية المهام', en: 'Filter tasks' },
  'lp.plan.all': { ar: 'الكل', en: 'All' },
  'lp.plan.mine': { ar: 'مهامي', en: 'Mine' },
  'lp.plan.needsAction': { ar: 'تحتاج تدخلًا', en: 'Needs action' },
  'lp.plan.expandAll': { ar: 'فتح الكل', en: 'Expand all' },
  'lp.plan.collapseAll': { ar: 'طي الكل', en: 'Collapse all' },
  'lp.plan.stageProgress': { ar: '{done} من {total}', en: '{done} of {total}' },
  'lp.plan.openIssues': { ar: '{n} مشكلة مفتوحة', en: '{n} open issues' },
  'lp.plan.now': { ar: 'الآن', en: 'Now' },
  'lp.plan.tasksDone': { ar: '{done} من {total} مهام منجزة', en: '{done} of {total} tasks done' },
  'lp.plan.tasksTitle': { ar: 'المهام ({n})', en: 'Tasks ({n})' },
  'lp.plan.startsAfter': { ar: 'تبدأ بعد:', en: 'Starts after:' },
  'lp.plan.skip': { ar: 'تخطي المرحلة', en: 'Skip stage' },
  'lp.plan.unskip': { ar: 'إلغاء التخطي', en: 'Undo skip' },
  'lp.plan.skipped': { ar: 'تم تخطي المرحلة، والسبب محفوظ.', en: 'Stage skipped; the reason is kept.' },
  'lp.plan.skipTitle': { ar: 'تخطي «{stage}»', en: 'Skip “{stage}”' },
  'lp.plan.skipConditional': { ar: 'كل مهام هذه المرحلة شرطية، فيمكن تخطيها بسبب مسجل.', en: 'Every task here is conditional, so the stage can be skipped with a recorded reason.' },
  'lp.plan.skipAdmin': { ar: 'هذه مرحلة مطلوبة. تخطيها صلاحية مدير النظام وحده، ويُسجل كتجاوز.', en: 'This stage is required. Only an administrator may skip it, and it is recorded as an override.' },
  'lp.plan.skipReason': { ar: 'سبب التخطي:', en: 'Skipped because:' },
  'lp.plan.waitsFor': { ar: 'تنتظر:', en: 'Waiting for:' },
  'lp.plan.noTasksInFilter': { ar: 'لا توجد مهام هنا بهذه التصفية.', en: 'No tasks here with this filter.' },

  /* ── task ──────────────────────────────────────────────────── */
  'lp.task.loading': { ar: 'جارٍ التحميل…', en: 'Loading…' },
  'lp.task.automatic': { ar: 'تلقائية', en: 'Automatic' },
  'lp.task.needsApproval': { ar: 'تحتاج اعتمادًا', en: 'Needs approval' },
  'lp.task.sensitive': { ar: 'بيانات حساسة', en: 'Sensitive' },
  'lp.task.waitsFor': { ar: 'تنتظر: {what}', en: 'Waiting for: {what}' },
  'lp.task.evidenceCount': { ar: '{n} دليل', en: '{n} evidence' },
  'lp.task.next': { ar: 'الخطوة التالية', en: 'Next step' },
  'lp.task.autoTitle': { ar: 'تُحسب هذه البوابة تلقائيًا', en: 'This gate is checked automatically' },
  'lp.task.openProduction': { ar: 'فتح شاشة الإنتاج', en: 'Open Production' },
  'lp.task.blockedTitle': { ar: 'لا يمكن البدء بعد', en: 'Cannot start yet' },
  'lp.task.override': { ar: 'السماح بالبدء مبكرًا', en: 'Let it start early' },
  'lp.task.overrideTitle': { ar: 'السماح بالبدء قبل انتهاء ما قبلها', en: 'Start before its prerequisites finish' },
  'lp.task.overrideBody': { ar: 'تبقى المتطلبات السابقة كما هي؛ يُسجل التجاوز مع اسمك والسبب.', en: 'The prerequisites stay as they are; the override is recorded with your name and reason.' },
  'lp.task.reviewSubmission': { ar: 'مراجعة الإرسال رقم {n}', en: 'Review submission {n}' },
  'lp.task.reviewResubmission': { ar: 'مراجعة إعادة الإرسال رقم {n}', en: 'Review resubmission {n}' },
  'lp.task.submittedBy': { ar: 'أرسله {who} في {day}', en: 'Sent by {who} on {day}' },
  'lp.task.reviewNotes': { ar: 'ملاحظاتك (مطلوبة لطلب التعديل)', en: 'Your notes (required to request changes)' },
  'lp.task.overrideReason': { ar: 'سبب اعتماد عملك بنفسك', en: 'Why you are approving your own work' },
  'lp.task.overrideHint': { ar: 'مدير النظام وحده يعتمد عمله بنفسه، ويُحفظ السبب مع القرار.', en: 'Only an administrator may approve their own work; the reason is kept with the decision.' },
  'lp.task.approve': { ar: 'اعتماد', en: 'Approve' },
  'lp.task.requestChanges': { ar: 'طلب تعديل', en: 'Request changes' },
  'lp.task.changesNeedNote': { ar: 'اكتب ما يجب تعديله أولًا.', en: 'Write what needs changing first.' },
  'lp.task.start': { ar: 'بدء العمل', en: 'Start' },
  'lp.task.submit': { ar: 'إرسال للاعتماد', en: 'Send for approval' },
  'lp.task.resubmit': { ar: 'إعادة الإرسال', en: 'Resubmit' },
  'lp.task.complete': { ar: 'تم الإنجاز', en: 'Mark done' },
  'lp.task.submitNotes': { ar: 'ملاحظة للمعتمِد (اختياري)', en: 'Note for the approver (optional)' },
  'lp.task.completeNotes': { ar: 'ملاحظة (اختياري)', en: 'Note (optional)' },
  'lp.task.submitted': { ar: 'أُرسلت للاعتماد.', en: 'Sent for approval.' },
  'lp.task.completed': { ar: 'سُجل الإنجاز.', en: 'Marked done.' },
  'lp.task.approved': { ar: 'اعتُمدت.', en: 'Approved.' },
  'lp.task.changesSent': { ar: 'أُعيدت مع طلب التعديل.', en: 'Sent back with the requested changes.' },
  'lp.task.waitingFor': { ar: 'بانتظار اعتماد', en: 'Waiting for approval by' },
  'lp.task.startReview': { ar: 'بدء المراجعة', en: 'Start review' },
  'lp.task.approvedBy': { ar: 'اعتمدها {who} في {day}', en: 'Approved by {who} on {day}' },
  'lp.task.doneBy': { ar: 'أنجزها {who} في {day}', en: 'Done by {who} on {day}' },
  'lp.task.waivedBy': { ar: 'تخطاها {who} في {day}', en: 'Waived by {who} on {day}' },
  'lp.task.readOnly': { ar: 'هذه المهمة ليست لديك — يمكنك متابعتها والتعليق عليها.', en: 'This task is not yours — you can follow it and comment.' },
  'lp.task.waive': { ar: 'تخطي المهمة', en: 'Waive' },
  'lp.task.waiveTitle': { ar: 'تخطي هذه المهمة', en: 'Waive this task' },
  'lp.task.waiveBody': { ar: 'تخرج المهمة من حساب مرحلتها، ويُحفظ السبب.', en: 'The task leaves its stage’s count; the reason is kept.' },
  'lp.task.waiveCondition': { ar: 'هذه مهمة شرطية: {condition}', en: 'This task is conditional: {condition}' },
  'lp.task.waiveRequired': { ar: 'هذه مهمة مطلوبة — تخطيها تجاوز من مدير النظام، ويُسجل كذلك.', en: 'This task is required — waiving it is an administrator override and is recorded as one.' },
  'lp.task.waived': { ar: 'تم التخطي، والسبب محفوظ.', en: 'Waived; the reason is kept.' },
  'lp.task.reopen': { ar: 'إعادة فتح', en: 'Reopen' },
  'lp.task.reopenTitle': { ar: 'إعادة فتح المهمة', en: 'Reopen the task' },
  'lp.task.reopenBody': { ar: 'تعود المهمة قيد التنفيذ، وتبقى الاعتمادات السابقة مرتبطة بإرسالها كما هي.', en: 'The task goes back in progress; earlier approvals stay attached to their submissions.' },
  'lp.task.reopened': { ar: 'أُعيد فتح المهمة.', en: 'Task reopened.' },
  'lp.task.moreActions': { ar: 'إجراءات أخرى', en: 'More actions' },
  'lp.task.saved': { ar: 'حُفظ.', en: 'Saved.' },
  'lp.task.about': { ar: 'عن المهمة', en: 'About' },
  'lp.task.condition': { ar: 'الشرط:', en: 'Condition:' },
  'lp.task.sensitiveNote': { ar: 'أدلة هذه المهمة يراها منسق الخبراء ومدير الإنتاج ومن أُسندت إليهم فقط.', en: 'Evidence here is visible only to the expert coordinator, the production manager and the people named on the task.' },
  'lp.task.externalTool': { ar: 'تسليم يدوي إلى {tool} — لا يوجد ربط برمجي؛ أرفق رابطًا أو ملفًا كدليل.', en: 'A manual handoff to {tool} — no integration exists; attach a link or file as evidence.' },
  'lp.task.kind': { ar: 'النوع', en: 'Kind' },
  'lp.task.source': { ar: 'المصدر', en: 'Source' },
  'lp.task.approval': { ar: 'الاعتماد من', en: 'Approved by' },
  'lp.task.deliverable': { ar: 'المُخرج', en: 'Deliverable' },
  'lp.task.assignment': { ar: 'الإسناد', en: 'Assignment' },
  'lp.task.changesAsked': { ar: 'طلب {who} تعديلات:', en: '{who} asked for changes:' },
  'lp.task.submissions': { ar: 'الإرسالات والقرارات', en: 'Submissions and decisions' },
  'lp.task.submissionN': { ar: 'الإرسال {n}', en: 'Submission {n}' },
  'lp.task.resubmission': { ar: 'إعادة إرسال', en: 'resubmission' },
  'lp.task.decidedBy': { ar: 'قرر {who} في {day}', en: 'Decided by {who} on {day}' },
  'lp.task.adminOverride': { ar: 'تجاوز إداري: {reason}', en: 'Administrator override: {reason}' },
  'lp.task.discussion': { ar: 'النقاش ({n})', en: 'Discussion ({n})' },
  'lp.task.commentLabel': { ar: 'تعليق', en: 'Comment' },
  'lp.task.commentPlaceholder': { ar: 'اكتب تعليقًا — اذكر زميلًا بكتابة @ثم اسمه', en: 'Write a comment — mention a colleague with @ and their name' },
  'lp.task.comment': { ar: 'إرسال', en: 'Post' },
  'lp.task.history': { ar: 'السجل', en: 'History' },

  /* ── checklist and evidence ────────────────────────────────── */
  'lp.checklist.title': { ar: 'قائمة الخطوات', en: 'Checklist' },
  'lp.checklist.progress': { ar: '{done} من {total}', en: '{done} of {total}' },
  'lp.checklist.optional': { ar: 'اختياري', en: 'optional' },
  'lp.checklist.na': { ar: 'لا ينطبق', en: 'N/A' },
  'lp.checklist.markNa': { ar: 'تعليم بأنه لا ينطبق', en: 'Mark not applicable' },
  'lp.checklist.naTitle': { ar: 'لماذا لا ينطبق هذا البند؟', en: 'Why does this line not apply?' },
  'lp.checklist.logIssue': { ar: 'تسجيل مشكلة', en: 'Log an issue' },
  'lp.checklist.issueLogged': { ar: 'سُجلت مشكلة', en: 'Issue logged' },
  'lp.checklist.undo': { ar: 'تراجع', en: 'Undo' },
  'lp.evidence.title': { ar: 'الأدلة', en: 'Evidence' },
  'lp.evidence.titleFor': { ar: 'الدليل: {what}', en: 'Evidence: {what}' },
  'lp.evidence.provided': { ar: 'مُقدم', en: 'Provided' },
  'lp.evidence.required': { ar: 'مطلوب', en: 'Required' },
  'lp.evidence.none': { ar: 'لا توجد أدلة بعد.', en: 'No evidence yet.' },
  'lp.evidence.restricted': { ar: 'دليل مقيد — يراه منسق الخبراء ومدير الإنتاج فقط.', en: 'Restricted — visible to the expert coordinator and production manager.' },
  'lp.evidence.download': { ar: 'تنزيل', en: 'Download' },
  'lp.evidence.withdraw': { ar: 'سحب الدليل', en: 'Withdraw' },
  'lp.evidence.withdrawTitle': { ar: 'سحب هذا الدليل', en: 'Withdraw this evidence' },
  'lp.evidence.withdrawBody': { ar: 'يبقى سجله ظاهرًا، لأن إرسالات سابقة قد تشير إليه.', en: 'Its record stays visible, because earlier submissions may cite it.' },
  'lp.evidence.withdrawnNote': { ar: 'سُحب: {reason}', en: 'withdrawn: {reason}' },
  'lp.evidence.addFile': { ar: 'رفع ملف', en: 'Upload a file' },
  'lp.evidence.addLink': { ar: 'إضافة رابط', en: 'Add a link' },
  'lp.evidence.addNote': { ar: 'إضافة ملاحظة', en: 'Add a note' },
  'lp.evidence.url': { ar: 'الرابط', en: 'Link' },
  'lp.evidence.noteLabel': { ar: 'الملاحظة', en: 'Note' },
  'lp.evidence.noteOptional': { ar: 'ملاحظة (اختياري)', en: 'Note (optional)' },
  'lp.evidence.accepted': { ar: 'المقبول: {types} · حتى {size}', en: 'Accepted: {types} · up to {size}' },
  'lp.evidence.added': { ar: 'أُضيف الدليل.', en: 'Evidence added.' },

  /* ── QA, issues, release ───────────────────────────────────── */
  'lp.qa.legacy': { ar: 'لا تُتتبع الجودة والإصدار لدورة إنتاج سابقة. اعتمد سير عمل من النظرة العامة لتتبعها.', en: 'QA and release are not tracked for a legacy run. Adopt a workflow from the overview to track them.' },
  'lp.qa.signoffs': { ar: 'اعتمادات النشر واختبار القبول', en: 'Deployment and UAT sign-offs' },
  'lp.qa.issues': { ar: 'مشكلات التجارب واختبار القبول', en: 'Dry-run and UAT issues' },
  'lp.qa.issueStage': { ar: 'المرحلة', en: 'Stage' },
  'lp.qa.allStages': { ar: 'كل المراحل', en: 'All stages' },
  'lp.qa.filter.open': { ar: 'مفتوحة', en: 'Open' },
  'lp.qa.filter.fixed': { ar: 'بانتظار التحقق', en: 'To verify' },
  'lp.qa.filter.closed': { ar: 'مغلقة', en: 'Closed' },
  'lp.qa.filter.all': { ar: 'الكل', en: 'All' },
  'lp.qa.noIssues': { ar: 'لم تُسجل مشكلات', en: 'No issues logged' },
  'lp.qa.noIssuesBody': { ar: 'تُسجل المشكلات من قوائم التجربة الداخلية واختبار القبول أو من زر «تسجيل مشكلة».', en: 'Issues are logged from the dry-run and UAT checklists, or with “Report an issue”.' },
  'lp.qa.noIssuesHere': { ar: 'لا توجد مشكلات بهذه التصفية', en: 'No issues with this filter' },
  'lp.issue.report': { ar: 'تسجيل مشكلة', en: 'Report an issue' },
  'lp.issue.log': { ar: 'تسجيل المشكلة', en: 'Log the issue' },
  'lp.issue.logTitle': { ar: 'تسجيل مشكلة من هذا البند', en: 'Log an issue from this line' },
  'lp.issue.logged': { ar: 'سُجلت المشكلة وأُبلغ مسؤولها.', en: 'Issue logged; its owner was told.' },
  'lp.issue.title': { ar: 'عنوان المشكلة', en: 'Title' },
  'lp.issue.severity': { ar: 'الخطورة', en: 'Severity' },
  'lp.issue.area': { ar: 'الفريق المسؤول', en: 'Team' },
  'lp.issue.owner': { ar: 'المسؤول عن الإصلاح', en: 'Owner' },
  'lp.issue.description': { ar: 'الوصف', en: 'Description' },
  'lp.issue.reported': { ar: 'تاريخ التسجيل', en: 'Reported' },
  'lp.issue.reportedBy': { ar: 'سجّلها', en: 'Reported by' },
  'lp.issue.fixedBy': { ar: 'أصلحها', en: 'Fixed by' },
  'lp.issue.verifiedBy': { ar: 'تحقق منها', en: 'Verified by' },
  'lp.issue.fixNote': { ar: 'ما الذي أُصلح', en: 'What was fixed' },
  'lp.issue.verifyNote': { ar: 'ملاحظة التحقق (اختياري)', en: 'Verification note (optional)' },
  'lp.issue.start': { ar: 'بدء المعالجة', en: 'Start' },
  'lp.issue.markFixed': { ar: 'تم الإصلاح', en: 'Mark fixed' },
  'lp.issue.verify': { ar: 'تأكيد الإصلاح', en: 'Verify the fix' },
  'lp.issue.verifyOwn': { ar: 'يتحقق من الإصلاح شخص غير من أصلحه.', en: 'The fix is verified by someone other than the person who made it.' },
  'lp.issue.reopen': { ar: 'إعادة فتح', en: 'Reopen' },
  'lp.issue.wontFix': { ar: 'لن تُصلح', en: "Won't fix" },
  'lp.issue.wontFixBody': { ar: 'تُغلق المشكلة دون إصلاح، ويُحفظ السبب.', en: 'The issue closes without a fix; the reason is kept.' },
  'lp.release.title': { ar: 'الإصدار', en: 'Release' },
  'lp.release.readyToPrepare': { ar: 'الدورة جاهزة: جهّز نسخة الإصدار المرشحة ليعتمدها شخص آخر.', en: 'The run is ready: prepare a release candidate for someone else to sign off.' },
  'lp.release.notReady': { ar: 'يمكن التجهيز عندما تتحقق كل شروط الجاهزية أعلاه.', en: 'You can prepare it once every readiness check above is met.' },
  'lp.release.none': { ar: 'لا توجد نسخة إصدار مرشحة.', en: 'No release candidate.' },
  'lp.release.label': { ar: 'رقم الإصدار', en: 'Version' },
  'lp.release.labelAuto': { ar: 'يُقترح تلقائيًا', en: 'Suggested automatically' },
  'lp.release.notes': { ar: 'ملاحظات', en: 'Notes' },
  'lp.release.prepare': { ar: 'تجهيز نسخة الإصدار', en: 'Prepare the release' },
  'lp.release.prepared': { ar: 'جُهزت', en: 'Prepared' },
  'lp.release.summary': { ar: '{lessons} دروس · {approved} من {assets} ملف معتمد', en: '{lessons} lessons · {approved} of {assets} assets approved' },
  'lp.release.signoff': { ar: 'اعتماد الإصدار', en: 'Sign off the release' },
  'lp.release.signedOff': { ar: 'اعتُمد الإصدار.', en: 'Release signed off.' },
  'lp.release.signedOffBy': { ar: 'اعتمده', en: 'Signed off by' },
  'lp.release.ownCandidate': { ar: 'جهّزت هذا الإصدار بنفسك، فيعتمده شخص آخر.', en: 'You prepared this release, so someone else signs it off.' },
  'lp.release.waitingSignoff': { ar: 'بانتظار اعتماد مدير الإنتاج أو مدير الكورس.', en: 'Waiting for the production or course manager to sign off.' },
  'lp.release.publishHint': { ar: 'لا يوجد ربط مع منصة التعلم: انشر يدويًا ثم سجّل رابط الإصدار كدليل.', en: 'There is no LMS integration: deploy by hand, then record the release link as evidence.' },
  'lp.release.platformUrl': { ar: 'رابط الإصدار على المنصة', en: 'Release link on the platform' },
  'lp.release.deploymentNotes': { ar: 'ملاحظات النشر', en: 'Deployment notes' },
  'lp.release.publish': { ar: 'تسجيل النشر', en: 'Record the publication' },
  'lp.release.published': { ar: 'سُجل النشر وأصبح هذا الإصدار الحالي.', en: 'Publication recorded; this is now the current release.' },
  'lp.release.publishedAs': { ar: 'نُشر كـ {label}', en: 'Published as {label}' },
  'lp.release.publishedCol': { ar: 'نُشر', en: 'Published' },
  'lp.release.withdraw': { ar: 'سحب نسخة الإصدار', en: 'Withdraw the candidate' },
  'lp.release.withdrawBody': { ar: 'تبقى النسخة المسحوبة في السجل مع السبب.', en: 'The withdrawn candidate stays in the history with its reason.' },
  'lp.release.withdrawn': { ar: 'سُحبت نسخة الإصدار.', en: 'Candidate withdrawn.' },
  'lp.release.history': { ar: 'سجل الإصدارات', en: 'Release history' },
  'lp.release.historyEmpty': { ar: 'لا توجد إصدارات بعد', en: 'No releases yet' },
  'lp.release.current': { ar: 'الحالي', en: 'Current' },
  'lp.release.drawerTitle': { ar: 'الإصدار {label}', en: 'Release {label}' },
  'lp.release.stale': { ar: 'تغير {n} ملف معتمد بعد تجهيز هذه النسخة — لا يمكن نشرها كما هي.', en: '{n} approved assets changed after this candidate was prepared — it cannot be published as is.' },
  'lp.release.baselineNote': { ar: 'خط أساس سُجل من المحتوى كما كان عند بدء التطوير — لم يُتحقق من نشره في هذا النظام.', en: 'A baseline recorded from the content as it stood when the revamp began — its publication was not verified in this system.' },
  'lp.release.contents': { ar: 'المحتوى ({n} دروس)', en: 'Contents ({n} lessons)' },
  'lp.release.notApproved': { ar: 'غير معتمد', en: 'not approved' },
  'lp.release.rollback': { ar: 'التراجع عن الإصدار', en: 'Roll back' },
  'lp.release.rollbackBody': { ar: 'يُعلَّم هذا الإصدار كمتراجع عنه ويعود الإصدار الذي حل محله إصدارًا حاليًا. لا يُحذف شيء.', en: 'This release is marked rolled back and the one it replaced becomes current again. Nothing is deleted.' },
  'lp.release.rolledBack': { ar: 'تم التراجع عن الإصدار.', en: 'Release rolled back.' },

  /* ── impact ────────────────────────────────────────────────── */
  'lp.impact.title': { ar: 'أثر التغيير', en: 'Change impact' },
  'lp.impact.source': { ar: 'مقارنة بـ {label}', en: 'Against {label}' },
  'lp.impact.lede': { ar: 'لكل درس: يبقى (تُحال إلى اعتماده السابق دون نسخه)، أو يتغير (كله أو ملفات منه، فتُفتح وتحتاج اعتمادًا جديدًا)، أو يُحذف.', en: 'For each lesson: keep it (its approval is referenced, not copied), change it (all or some assets, which reopen and need new approval), or remove it.' },
  'lp.impact.decision': { ar: 'القرار', en: 'Decision' },
  'lp.impact.assets': { ar: 'الملفات المتأثرة', en: 'Assets affected' },
  'lp.impact.note': { ar: 'ملاحظة', en: 'Note' },
  'lp.impact.keepHint': { ar: 'تبقى الاعتمادات كما هي', en: 'Approvals stay as they are' },
  'lp.impact.removeHint': { ar: 'يُؤرشف الدرس عند التطبيق', en: 'The lesson is archived when applied' },
  'lp.impact.save': { ar: 'حفظ القرارات', en: 'Save decisions' },
  'lp.impact.saveFirst': { ar: 'حفظ القرارات الأولى', en: 'Save the first decisions' },
  'lp.impact.saved': { ar: 'حُفظ أثر التغيير.', en: 'Change impact saved.' },
  'lp.impact.apply': { ar: 'تطبيق القرارات', en: 'Apply the decisions' },
  'lp.impact.applied': { ar: 'طُبق أثر التغيير: فُتح ما يتغير وأُرشف ما يُحذف.', en: 'Applied: what changes was reopened and what goes was archived.' },
  'lp.impact.appliedOn': { ar: 'طُبق في {day}', en: 'Applied on {day}' },
  'lp.impact.signoffTask': { ar: 'مهمة الاعتماد:', en: 'Sign-off task:' },
  'lp.impact.noSource': { ar: 'لا يوجد إصدار مصدر لهذه الدورة.', en: 'This run has no source release.' },

  /* ── curriculum, team, candidates ─────────────────────────── */
  'lp.curriculum.title': { ar: 'المنهج', en: 'Curriculum' },
  'lp.curriculum.notApproved': { ar: 'لم يُعتمد المنهج النهائي بعد — يمكن إضافة الدروس الآن، لكن هيكلها قد يتغير.', en: 'The final curriculum is not approved yet — you can add lessons now, but their structure may change.' },
  'lp.team.runOnly': { ar: 'أدوار في هذه الدورة فقط', en: 'Roles on this run only' },
  'lp.team.runOnlyHint': { ar: 'لأشخاص يشاركون في هذه الدورة وحدها، مثل مختبري القبول لهذه الجولة.', en: 'For people on this run only — the testers for this UAT cycle, say.' },
  'lp.team.runOnlyEmpty': { ar: 'لا يوجد أحد بدور خاص بهذه الدورة.', en: 'Nobody holds a role on this run only.' },
  'lp.team.person': { ar: 'الشخص', en: 'Person' },
  'lp.team.role': { ar: 'الدور', en: 'Role' },
  'lp.candidates.title': { ar: 'المرشحون من الخبراء', en: 'Expert candidates' },
  'lp.candidates.sensitive': { ar: 'بيانات حساسة: تظهر لمنسق الخبراء ومدير الإنتاج ومدير النظام فقط، ولا تُذكر الأسماء في السجل.', en: 'Sensitive: visible to the expert coordinator, the production manager and administrators only; names never appear in the history.' },
  'lp.candidates.add': { ar: 'إضافة مرشح', en: 'Add a candidate' },
  'lp.candidates.empty': { ar: 'لا يوجد مرشحون بعد', en: 'No candidates yet' },
  'lp.candidates.name': { ar: 'الاسم', en: 'Name' },
  'lp.candidates.email': { ar: 'الإيميل', en: 'Email' },
  'lp.candidates.phone': { ar: 'الهاتف', en: 'Phone' },
  'lp.candidates.source': { ar: 'المصدر', en: 'Source' },
  'lp.candidates.years': { ar: 'سنوات الخبرة', en: 'Years' },
  'lp.candidates.profile': { ar: 'رابط الملف الشخصي', en: 'Profile link' },
  'lp.candidates.assessment': { ar: 'التقييم (من 1 إلى 5)', en: 'Assessment (1–5)' },
  'lp.candidates.notes': { ar: 'ملاحظات', en: 'Notes' },
  'lp.candidates.files': { ar: 'الملفات', en: 'Files' },
  'lp.candidates.fileKind': { ar: 'نوع الملف', en: 'File type' },
  'lp.candidates.updated': { ar: 'آخر تحديث', en: 'Updated' },
  'lp.candidates.saved': { ar: 'حُفظ المرشح.', en: 'Candidate saved.' },

  /* ── my work, reviews, preferences ─────────────────────────── */
  'lp.myWork.title': { ar: 'عملي', en: 'My work' },
  'lp.myWork.lede': { ar: 'ما هو لك، وما التالي، وما المتوقف ولماذا — وكل سطر يفتح مكان العمل مباشرة.', en: 'What is yours, what is next, what is blocked and why — every row opens the exact place to act.' },
  'lp.myWork.now': { ar: 'الآن', en: 'Now' },
  'lp.myWork.review': { ar: 'بانتظار قراري', en: 'For my decision' },
  'lp.myWork.blocked': { ar: 'متوقف', en: 'Blocked' },
  'lp.myWork.done': { ar: 'أنجزته مؤخرًا', en: 'Recently done' },
  'lp.myWork.empty.now': { ar: 'لا يوجد عمل عليك الآن', en: 'Nothing for you right now' },
  'lp.myWork.empty.review': { ar: 'لا شيء بانتظار قرارك', en: 'Nothing waits for your decision' },
  'lp.myWork.empty.blocked': { ar: 'لا يوجد عمل متوقف', en: 'Nothing of yours is blocked' },
  'lp.myWork.empty.done': { ar: 'لم تُنجز شيئًا في آخر أسبوعين', en: 'Nothing finished in the last two weeks' },
  'lp.myWork.emptyNowBody': { ar: 'عندما تُسند إليك مهمة أو ملف تصلك رسالة ويظهر هنا.', en: 'When a task or asset is assigned to you, you are notified and it appears here.' },
  'lp.work.kind.TASK': { ar: 'مهمة', en: 'Task' },
  'lp.work.kind.ASSET': { ar: 'ملف درس', en: 'Lesson asset' },
  'lp.work.kind.ISSUE': { ar: 'مشكلة', en: 'Issue' },
  'lp.work.kind.RELEASE': { ar: 'إصدار', en: 'Release' },
  'lp.work.action.ASSIGN': { ar: 'أسند', en: 'Assign' },
  'lp.work.lessonsCount': { ar: '{n} درس بلا مسؤول', en: '{n} lessons with nobody on them' },
  'lp.work.action.START': { ar: 'ابدأ', en: 'Start' },
  'lp.work.action.CONTINUE': { ar: 'تابع', en: 'Continue' },
  'lp.work.action.FIX': { ar: 'عدّل', en: 'Fix' },
  'lp.work.action.REVIEW': { ar: 'راجع', en: 'Review' },
  'lp.work.action.VERIFY': { ar: 'تحقق', en: 'Verify' },
  'lp.work.action.SIGN_OFF': { ar: 'اعتمد', en: 'Sign off' },
  'lp.work.action.PUBLISH': { ar: 'سجّل النشر', en: 'Publish' },
  'lp.work.open': { ar: 'فتح', en: 'Open' },
  'lp.work.release': { ar: 'الإصدار {label}', en: 'Release {label}' },
  'lp.work.resubmission': { ar: 'إعادة إرسال', en: 'Resubmission' },
  'lp.work.openComments': { ar: '{n} ملاحظة مفتوحة', en: '{n} open comments' },
  'lp.reviews.title': { ar: 'المراجعات', en: 'Reviews' },
  'lp.reviews.lede': { ar: 'كل ما ينتظر قرارك، مقسمًا كما يعمل المراجعون. لا يظهر هنا ما أرسلته بنفسك.', en: 'Everything waiting for your decision, grouped the way reviewers work. Your own submissions never appear here.' },
  'lp.reviews.includeOthers': { ar: 'إظهار ما أُسند لمراجعين آخرين', en: 'Include those named to other reviewers' },
  'lp.reviews.group.firstSubmissions': { ar: 'إرسالات أولى', en: 'First submissions' },
  'lp.reviews.group.resubmissions': { ar: 'إعادة إرسال', en: 'Resubmissions' },
  'lp.reviews.group.curriculum': { ar: 'اعتمادات المنهج', en: 'Curriculum approvals' },
  'lp.reviews.group.mediaQa': { ar: 'جودة الوسائط', en: 'Media QA' },
  'lp.reviews.group.signoff': { ar: 'اختبار القبول والإصدار', en: 'UAT and release sign-off' },
  'lp.reviews.hint.firstSubmissions': { ar: 'أعمال تصلك للمرة الأولى: مخططات وسكريبتات ومهام تحتاج اعتمادًا.', en: 'Work reaching you for the first time: outlines, scripts and tasks that need approval.' },
  'lp.reviews.hint.resubmissions': { ar: 'أعمال أُعيدت بعد طلب تعديل — راجع ما تغير منذ قرارك السابق.', en: 'Work sent back after changes — check what changed since your last decision.' },
  'lp.reviews.hint.curriculum': { ar: 'البحث والمسودة والمنهج النهائي والتصميم التعليمي وأثر التغيير.', en: 'Research, drafts, the final curriculum, instructional design and change impact.' },
  'lp.reviews.hint.mediaQa': { ar: 'العروض والتعليق الصوتي والفيديو، مع قوائم الجودة.', en: 'Slides, voice-over and video, with their QA checklists.' },
  'lp.reviews.hint.signoff': { ar: 'اعتماد اختبار القبول، ونسخ الإصدار، والمشكلات المُصلحة التي تنتظر التحقق.', en: 'UAT sign-off, release candidates, and fixed issues waiting to be verified.' },
  'lp.reviews.empty': { ar: 'لا شيء هنا — أنت على اطلاع بكل شيء.', en: 'Nothing here — you are all caught up.' },
  'lp.prefs.title': { ar: 'التنبيهات', en: 'Notifications' },
  'lp.prefs.lede': { ar: 'اختر ما يصلك من تنبيهات الإنتاج ومتى. تصل كلها إلى جرس مساحة العمل.', en: 'Choose which production alerts reach you and when. They all arrive in the workspace bell.' },
  'lp.prefs.kinds': { ar: 'أنواع التنبيهات', en: 'Kinds of alert' },
  'lp.prefs.on': { ar: 'مفعّل', en: 'On' },
  'lp.prefs.off': { ar: 'متوقف', en: 'Off' },
  'lp.prefs.dueSoon': { ar: 'تذكير قبل الموعد', en: 'Remind me before a deadline' },
  'lp.prefs.overdueRepeat': { ar: 'تذكير بالمتأخر', en: 'Remind me about overdue work' },
  'lp.prefs.never': { ar: 'لا تذكير', en: 'Never' },
  'lp.prefs.days': { ar: 'قبل {n} يوم', en: '{n} days before' },
  'lp.prefs.once': { ar: 'مرة واحدة', en: 'Once' },
  'lp.prefs.everyDays': { ar: 'كل {n} أيام', en: 'Every {n} days' },
  'lp.prefs.event.assigned': { ar: 'إسناد عمل إليّ', en: 'Work assigned to me' },
  'lp.prefs.event.review_requested': { ar: 'طلب اعتماد مني', en: 'Approval requested from me' },
  'lp.prefs.event.changes_requested': { ar: 'طلب تعديل على عملي', en: 'Changes requested on my work' },
  'lp.prefs.event.approved': { ar: 'اعتماد عملي', en: 'My work approved' },
  'lp.prefs.event.comment': { ar: 'تعليقات', en: 'Comments' },
  'lp.prefs.event.mention': { ar: 'ذكر اسمي', en: 'Mentions' },
  'lp.prefs.event.handoff': { ar: 'انتقال المراحل', en: 'Stage handoffs' },
  'lp.prefs.event.deadline': { ar: 'المواعيد', en: 'Deadlines' },
  'lp.prefs.event.issue': { ar: 'المشكلات', en: 'Issues' },
  'lp.prefs.event.release': { ar: 'الإصدارات', en: 'Releases' },
  'lp.prefs.eventHint.assigned': { ar: 'مهمة أو ملف درس صار باسمك.', en: 'A task or lesson asset now carries your name.' },
  'lp.prefs.eventHint.review_requested': { ar: 'إرسال أو نسخة إصدار تنتظر قرارك.', en: 'A submission or release candidate waits for your decision.' },
  'lp.prefs.eventHint.changes_requested': { ar: 'أُعيد عملك مع ما يجب تعديله.', en: 'Your work came back with what to change.' },
  'lp.prefs.eventHint.approved': { ar: 'اعتُمد ما أرسلته.', en: 'What you sent was approved.' },
  'lp.prefs.eventHint.comment': { ar: 'تعليق على عمل أنت مسؤول عنه أو تراجعه.', en: 'A comment on work you hold or review.' },
  'lp.prefs.eventHint.mention': { ar: 'ذكرك أحدهم في نقاش.', en: 'Someone mentioned you in a discussion.' },
  'lp.prefs.eventHint.handoff': { ar: 'اكتملت مرحلة أو صار عملك جاهزًا للبدء.', en: 'A stage finished or your work became ready to start.' },
  'lp.prefs.eventHint.deadline': { ar: 'قرب الموعد أو تجاوزه.', en: 'A deadline is close or passed.' },
  'lp.prefs.eventHint.issue': { ar: 'مشكلة أُسندت إليك أو أُصلحت أو أُعيد فتحها.', en: 'An issue assigned to you, fixed or reopened.' },
  'lp.prefs.eventHint.release': { ar: 'تجهيز الإصدار واعتماده ونشره والتراجع عنه.', en: 'A release prepared, signed off, published or rolled back.' },

  /* ── templates ─────────────────────────────────────────────── */
  'lp.templates.title': { ar: 'قوالب سير العمل', en: 'Workflow templates' },
  'lp.templates.lede': { ar: 'القوالب مبنية من ملف «Content Development Checklists» صفًا بصف. كل دورة إنتاج تُثبَّت على نسخة القالب التي بدأت بها.', en: 'Templates are built from the “Content Development Checklists” workbook, row by row. Every run is pinned to the template version it started with.' },
  'lp.templates.tab.templates': { ar: 'القوالب', en: 'Templates' },
  'lp.templates.tab.trace': { ar: 'تتبع ملف العمل', en: 'Workbook trace' },
  'lp.templates.tab.decisions': { ar: 'قرارات مفتوحة', en: 'Open decisions' },
  'lp.templates.scenario': { ar: 'الطريقة', en: 'Way' },
  'lp.templates.version': { ar: 'النسخة الحالية: {n}', en: 'Current version: {n}' },
  'lp.templates.hiddenCount': { ar: '{n} من صفوف مخفية', en: '{n} from hidden rows' },
  'lp.templates.after': { ar: 'بعد: {stages}', en: 'after: {stages}' },
  'lp.templates.approvedBy': { ar: 'يعتمدها {role}', en: 'approved by {role}' },
  'lp.templates.options': { ar: 'خيارات القالب', en: 'Template options' },
  'lp.templates.default': { ar: 'الافتراضي: {value}', en: 'Default: {value}' },
  'lp.templates.notes': { ar: 'ملاحظات النسخة', en: 'Version notes' },
  'lp.templates.publish': { ar: 'نشر نسخة جديدة', en: 'Publish a new version' },
  'lp.templates.publishHint': { ar: 'تستخدم الدورات الجديدة النسخة الجديدة؛ الدورات الجارية تبقى على نسختها.', en: 'New runs use the new version; runs in progress keep theirs.' },
  'lp.templates.published': { ar: 'نُشرت نسخة جديدة من القالب.', en: 'A new template version was published.' },
  'lp.templates.adminOnly': { ar: 'تغيير الخيارات صلاحية مدير القوالب.', en: 'Changing options is for template administrators.' },
  'lp.templates.versions': { ar: 'النسخ', en: 'Versions' },
  'lp.templates.current': { ar: 'الحالية', en: 'Current' },
  'lp.templates.runs': { ar: '{n} دورة', en: '{n} runs' },
  'lp.templates.traceTitle': { ar: '{rows} صف من ملف العمل ({hidden} مخفي)', en: '{rows} workbook rows ({hidden} hidden)' },
  'lp.templates.allTraced': { ar: 'كل صف متتبع', en: 'Every row traced' },
  'lp.templates.untraced': { ar: '{n} صف غير متتبع', en: '{n} rows untraced' },
  'lp.templates.sheet': { ar: 'الورقة', en: 'Sheet' },
  'lp.templates.row': { ar: 'الصف', en: 'Row' },
  'lp.templates.text': { ar: 'النص', en: 'Text' },
  'lp.templates.allSheets': { ar: 'كل الأوراق', en: 'All sheets' },
  'lp.templates.allStatuses': { ar: 'كل الحالات', en: 'All statuses' },
  'lp.templates.usedBy': { ar: 'مستخدم في', en: 'Used by' },
  'lp.templates.openDecisions': { ar: 'قرارات بانتظار مالك العمل', en: 'Decisions for the business owner' },
  'lp.templates.anomalies': { ar: 'ملاحظات على ملف العمل', en: 'Workbook anomalies' },
  'lp.templates.affectsRelease': { ar: 'يؤثر على الإطلاق', en: 'Affects release' },
  'lp.templates.englishSource': { ar: 'هذه السجلات مكتوبة بلغة ملف العمل المصدر (الإنجليزية) لتطابق نصه.', en: 'These records are kept in the source workbook’s language (English) so they match its text.' },

  /* ── the simple screens (2026-09-30) ───────────────────────── */
  'lp.nav.home': { ar: 'مهامي', en: 'My tasks' },
  'lp.nav.more': { ar: 'المزيد', en: 'More' },
  'lp.home.hello': { ar: 'أهلًا {name}', en: 'Hello, {name}' },
  'lp.home.summary': { ar: 'عليك {work} عمل، وبانتظار قرارك {reviews}.', en: 'You have {work} to do and {reviews} to review.' },
  'lp.home.late': { ar: '{n} متأخر', en: '{n} late' },
  'lp.home.allClear': { ar: 'لا شيء بانتظارك الآن.', en: 'Nothing is waiting for you right now.' },
  'lp.home.decide': { ar: 'بانتظار قرارك', en: 'Waiting for your decision' },
  'lp.home.do': { ar: 'مطلوب منك', en: 'Yours to do' },
  'lp.home.emptyTitle': { ar: 'لا توجد مهام لك الآن', en: 'No tasks for you right now' },
  'lp.home.emptyBody': { ar: 'عندما يُسند إليك عمل أو تصلك مراجعة ستظهر هنا مباشرة.', en: 'When work is assigned to you or a review reaches you, it shows up here.' },
  'lp.home.waiting': { ar: 'متوقف على غيرك', en: 'Waiting on others' },
  'lp.home.waitingHint': { ar: 'أعمال مسندة إليك لا تبدأ إلا بعد أن ينتهي ما قبلها.', en: 'Work assigned to you that starts once what comes before it is done.' },
  'lp.home.done': { ar: 'أنجزته مؤخرًا', en: 'Done recently' },
  'lp.home.othersReviews': { ar: 'مراجعات عند أعضاء الفريق', en: 'Reviews with the team' },
  'lp.home.othersNone': { ar: 'لا توجد مراجعات معلقة عند غيرك.', en: 'No reviews are waiting with anyone else.' },
  'lp.home.reviewer': { ar: 'المراجع: {name}', en: 'Reviewer: {name}' },
  'lp.home.notYet': { ar: 'لم يحن دوره', en: 'Not yet' },
  'lp.home.due': { ar: 'التسليم {day}', en: 'Due {day}' },
  'lp.home.lateSince': { ar: 'متأخر منذ {day}', en: 'Late since {day}' },
  'lp.home.attention': { ar: 'كورسات تحتاج انتباهك', en: 'Courses that need you' },
  'lp.home.attentionNone': { ar: 'كل الكورسات تسير في موعدها.', en: 'Every course is on schedule.' },
  'lp.home.allCourses': { ar: 'كل الكورسات', en: 'All courses' },
  'lp.courses.count': { ar: 'عدد الكورسات: {n}', en: '{n} courses' },
  'lp.courses.show': { ar: 'عرض', en: 'Show' },
  'lp.courses.now': { ar: 'الآن:', en: 'Now:' },
  'lp.courses.legacyWhere': { ar: 'إنتاج سابق بلا مراحل', en: 'Earlier production, no stages' },
  'lp.courses.due': { ar: 'التسليم {day}', en: 'Due {day}' },
  'lp.courses.lessons': { ar: 'الدروس: {n}', en: '{n} lessons' },
  'lp.course.where': { ar: 'أين وصلنا', en: 'Where we are' },
  'lp.course.released': { ar: 'تم الإصدار', en: 'Released' },
  'lp.course.allStagesDone': { ar: 'اكتملت كل المراحل', en: 'Every stage is complete' },
  'lp.course.thenStage': { ar: 'بعدها: {stage}', en: 'Then: {stage}' },
  'lp.course.stagesDone': { ar: '{done} من {total} مراحل انتهت', en: '{done} of {total} stages done' },
  'lp.course.needsNow': { ar: 'المطلوب في هذه المرحلة', en: 'What this stage needs' },
  'lp.course.allStages': { ar: 'كل المراحل', en: 'All stages' },
  'lp.course.noTasks': { ar: 'لا توجد مهام في هذه المرحلة.', en: 'This stage has no tasks.' },
  'lp.course.tasksDone': { ar: '{done} من {total} مهام', en: '{done} of {total} tasks' },
  'lp.course.lessons': { ar: 'الدروس', en: 'Lessons' },
  'lp.course.lessonsDone': { ar: '{done} من {total} دروس اكتملت', en: '{done} of {total} lessons complete' },
  'lp.course.pipsHint': { ar: 'ملفات كل درس بالترتيب: {order}', en: 'Each lesson’s files, in order: {order}' },
  'lp.course.editLessons': { ar: 'تعديل الدروس', en: 'Edit lessons' },
  'lp.course.assignAll': { ar: 'الإسناد الجماعي', en: 'Assign in bulk' },
  'lp.course.contentApproved': { ar: 'المحتوى المعتمد', en: 'Content approved' },
  'lp.course.tasksProgress': { ar: 'مهام الخطة', en: 'Plan tasks' },
  'lp.course.openQa': { ar: 'فتح الجودة والإصدار', en: 'Open QA & release' },
  'lp.course.blockingIssues': { ar: 'مشكلات حرجة مفتوحة: {n}', en: '{n} blocking issues open' },
  'lp.course.noBlockingIssues': { ar: 'لا توجد مشكلات حرجة', en: 'No blocking issues' },
  'lp.course.publishedAs': { ar: 'منشور: {label}', en: 'Published: {label}' },
  'lp.course.notPublished': { ar: 'لم يُنشر إصدار بعد', en: 'Nothing published yet' },
  'lp.course.readinessLeft': { ar: 'شروط إصدار متبقية: {n}', en: '{n} release conditions left' },
  'lp.course.readyToRelease': { ar: 'جاهز للإصدار', en: 'Ready to release' },
  'lp.course.openTeam': { ar: 'إدارة الفريق', en: 'Manage the team' },
  'lp.course.noTeam': { ar: 'لم يُضف أحد إلى الفريق بعد.', en: 'Nobody is on the team yet.' },
  'lp.course.members': { ar: 'أعضاء الفريق: {n}', en: '{n} people' },
  'lp.course.filesHint': { ar: 'كل ما رُفع، وسجل ما حدث', en: 'Everything uploaded, and what happened' },
  'lp.comment.showResolved': { ar: 'عرض الملاحظات المحلولة ({n})', en: 'Show resolved notes ({n})' },
  'lp.comment.hideResolved': { ar: 'إخفاء الملاحظات المحلولة', en: 'Hide resolved notes' },
  /* ── inside a lesson and a task (2026-09-30) ───────────────── */
  'lp.lessonPage.filesApproved': { ar: '{done} من {total} ملفات معتمدة', en: '{done} of {total} files approved' },
  'lp.lessonPage.notYet': { ar: 'لم يحن دوره', en: 'Not yet' },
  'lp.lessonPage.notNeeded': { ar: 'لا يلزم', en: 'Not needed' },
  'lp.assetBar.maker': { ar: 'المسؤول: {name}', en: 'Owner: {name}' },
  'lp.assetBar.reviewer': { ar: 'المراجع: {name}', en: 'Reviewer: {name}' },
  'lp.assetBar.due': { ar: 'التسليم {day}', en: 'Due {day}' },
  'lp.assetBar.late': { ar: 'متأخر — كان التسليم {day}', en: 'Late — was due {day}' },
  'lp.assetBar.startsAfter': { ar: 'يبدأ هذا الملف بعد اعتماد:', en: 'This file starts once this is approved:' },
  'lp.assetBar.waitingTitle': { ar: 'لم يحن دور هذا الملف بعد', en: 'This file’s turn has not come yet' },
  'lp.assetBar.waitingBody': { ar: 'سيفتح تلقائيًا عند اعتماد الملف الذي قبله، ويصل تنبيه للمسؤول عنه.', en: 'It opens by itself once the file before it is approved, and its owner is notified.' },
  'lp.ppt.markSlide': { ar: 'التعليم على الشريحة', en: 'Mark up the slide' },
  'lp.taskPage.approver': { ar: 'المعتمد: {name}', en: 'Approver: {name}' },
  'lp.taskPage.editAssignment': { ar: 'تعديل', en: 'Change' },
  'lp.taskPage.details': { ar: 'التفاصيل والسجل', en: 'Details and history' },
  'lp.taskPage.classification': { ar: 'التصنيف', en: 'Classification' },
  'lp.home.lateChip': { ar: 'متأخر', en: 'late' },
  'lp.lessonPage.ofApproved': { ar: 'من {total} ملفات معتمدة', en: 'of {total} files approved' },
  'lp.course.stageLater': { ar: 'لاحقًا', en: 'Later' },
  'lp.course.startsWhen': { ar: 'تبدأ بعد:', en: 'Starts after:' },
  'lp.course.showStages': { ar: 'عرض', en: 'Show' },
  'lp.course.hideStages': { ar: 'إخفاء', en: 'Hide' },
  'lp.newRun.pm': { ar: 'مدير المشروع', en: 'Project manager' },
  'lp.newRun.pmHint': { ar: 'شخص واحد يدير الدورة: يوزّع الشغل على فريقه من صفحة الكورس، وتصله أي مهمة لم تُسند لأحد.', en: 'One person runs the run: hands out the work from the course page, and receives any task nobody holds.' },
  'lp.newRun.keyRoles': { ar: 'أهم الأدوار في هذه الطريقة', en: 'The key roles for this way' },
  'lp.newRun.keyRolesHint': { ar: 'اختيارية — حدّدها الآن إن كنت تعرف أصحابها، أو اتركها لمدير المشروع.', en: 'Optional — name them now if you know who, or leave them to the project manager.' },
  'lp.newRun.otherRoles': { ar: 'باقي الأدوار (اختياري)', en: 'Other roles (optional)' },
  'lp.newRun.otherRolesHint': { ar: 'لا حاجة لملئها الآن؛ يسندها مدير المشروع لاحقًا من صفحة الكورس.', en: 'No need to fill these now; the project manager assigns them later from the course page.' },
  'lp.newRun.unassignedGoToPm': { ar: 'أي مهمة بلا شخص ستظهر لـ {name} في «مهامي» ليسندها.', en: 'Any task without a person will appear in {name}’s My tasks to assign.' },
  'lp.course.ofFiles': { ar: '{done} من {total} ملف', en: '{done} of {total} files' },
};
