/**
 * E-Learning Production — the copy for production runs and the rebuilt
 * screens, in Arabic and English.
 *
 * Arabic is Modern Standard Arabic, written for the reader, not translated
 * word for word. Keys are stable and language-neutral; enum families
 * (`lp.taskStatus.*`, `lp.stageKey.*`, …) cover every value the server can
 * send, and server/learningProduction.i18n.test.js fails when a key used in
 * the code, or a value of one of those families, has no entry here or in
 * strings.ts — or when an Arabic entry is just the English copied across.
 *
 * Entries here take precedence over strings.ts, which is how a few older
 * labels (two role names, the health reasons) were corrected.
 */

type Pair = { ar: string; en: string };

const ENUMS: Record<string, Pair> = {
  /* ── scenarios ─────────────────────────────────────────────── */
  'lp.scenario.AI_NEW': { ar: 'برنامج جديد بمساعدة الذكاء الاصطناعي', en: 'New program — AI-assisted' },
  'lp.scenario.EXPERT_NEW': { ar: 'برنامج جديد بقيادة خبير', en: 'New program — expert-led' },
  'lp.scenario.REVAMP': { ar: 'تطوير برنامج قائم', en: 'Revamp an existing program' },
  'lp.scenario.LEGACY': { ar: 'إنتاج سابق', en: 'Legacy production' },
  'lp.scenarioShort.AI_NEW': { ar: 'جديد · ذكاء اصطناعي', en: 'New · AI' },
  'lp.scenarioShort.EXPERT_NEW': { ar: 'جديد · خبير', en: 'New · expert' },
  'lp.scenarioShort.REVAMP': { ar: 'تطوير', en: 'Revamp' },
  'lp.scenarioShort.LEGACY': { ar: 'إنتاج سابق', en: 'Legacy' },
  'lp.scenarioHint.AI_NEW': {
    ar: 'تُولّد أدوات الذكاء الاصطناعي المخططات والسكريبتات والشرائح والفيديو، ويراجع كل مخرج شخصٌ مسؤول ويعتمده.',
    en: 'AI tools draft the outlines, scripts, slides and video; a named person reviews and approves every output.',
  },
  'lp.scenarioHint.EXPERT_NEW': {
    ar: 'بحث ومنهج أولي واستقطاب خبير ومنهج نهائي وتصميم تعليمي وإنتاج ونشر وتجربة داخلية واختبار قبول.',
    en: 'Research, a first curriculum, an expert, the final curriculum, instructional design, media, deployment, a dry run and UAT.',
  },
  'lp.scenarioHint.REVAMP': {
    ar: 'يبدأ من إصدار منشور، ويسجل ما يبقى وما يتغير، ثم تصميم وإنتاج ونشر وتجربتان داخليتان واختبار قبول وإصدار جديد.',
    en: 'Starts from a published release, records what stays and what changes, then design, media, deployment, two dry runs, UAT and a new release.',
  },
  'lp.scenarioPath.AI_NEW': {
    ar: 'المدخلات ← المخططات ← مراجعتها ← المنهج النهائي ← السكريبتات ← Docki ← التعليق الصوتي وThink ← مراجعة الفيديو ← التعديلات ← التحقق',
    en: 'Input → outlines → review → final curriculum → scripts → Docki → VO and Think → video review → fixes → check',
  },
  'lp.scenarioPath.EXPERT_NEW': {
    ar: 'البحث ← المسودة الأولى ← الخبراء ← المنهج النهائي ← التصميم التعليمي ← الوسائط ← النشر ← التجربة الداخلية ← التعديلات ← إعادة النشر ← اختبار القبول',
    en: 'Research → first draft → experts → final curriculum → ID → media → deployment → dry run → fixes → redeploy → UAT',
  },
  'lp.scenarioPath.REVAMP': {
    ar: 'أثر التغيير ← التصميم التعليمي ← الوسائط ← النشر ← التجربة الأولى ← التعديلات ← ملاحظات التجربة ← التجربة الثانية ← اختبار القبول',
    en: 'Change impact → ID → media → deployment → dry run 1 → changes → dry-run comments → dry run 2 → UAT',
  },

  /* ── statuses ──────────────────────────────────────────────── */
  'lp.runStatus.ACTIVE': { ar: 'نشطة', en: 'Active' },
  'lp.runStatus.ON_HOLD': { ar: 'متوقفة مؤقتًا', en: 'On hold' },
  'lp.runStatus.RELEASED': { ar: 'صدر إصدارها', en: 'Released' },
  'lp.runStatus.CLOSED': { ar: 'مغلقة', en: 'Closed' },
  'lp.runStatus.CANCELLED': { ar: 'ملغاة', en: 'Cancelled' },
  'lp.stageStatus.BLOCKED': { ar: 'بانتظار ما قبلها', en: 'Waiting' },
  'lp.stageStatus.READY': { ar: 'جاهزة للبدء', en: 'Ready' },
  'lp.stageStatus.IN_PROGRESS': { ar: 'جارية', en: 'In progress' },
  'lp.stageStatus.DONE': { ar: 'مكتملة', en: 'Done' },
  'lp.stageStatus.SKIPPED': { ar: 'تم تخطيها', en: 'Skipped' },
  'lp.taskStatus.BLOCKED': { ar: 'بانتظار ما قبلها', en: 'Waiting' },
  'lp.taskStatus.READY': { ar: 'جاهزة', en: 'Ready' },
  'lp.taskStatus.NOT_STARTED': { ar: 'لم تبدأ', en: 'Not started' },
  'lp.taskStatus.IN_PROGRESS': { ar: 'قيد التنفيذ', en: 'In progress' },
  'lp.taskStatus.SUBMITTED': { ar: 'بانتظار الاعتماد', en: 'Waiting for approval' },
  'lp.taskStatus.UNDER_REVIEW': { ar: 'قيد المراجعة', en: 'Under review' },
  'lp.taskStatus.CHANGES_REQUESTED': { ar: 'مطلوب تعديل', en: 'Changes requested' },
  'lp.taskStatus.APPROVED': { ar: 'معتمدة', en: 'Approved' },
  'lp.taskStatus.DONE': { ar: 'منجزة', en: 'Done' },
  'lp.taskStatus.WAIVED': { ar: 'تم تخطيها', en: 'Waived' },
  'lp.taskKind.WORK': { ar: 'عمل', en: 'Work' },
  'lp.taskKind.REVIEW': { ar: 'مراجعة', en: 'Review' },
  'lp.taskKind.HANDOFF': { ar: 'تسليم', en: 'Handoff' },
  'lp.taskKind.ISSUES': { ar: 'فحص وتسجيل مشكلات', en: 'Check and log issues' },
  'lp.taskKind.SIGNOFF': { ar: 'اعتماد', en: 'Sign-off' },
  'lp.taskKind.AUTO': { ar: 'بوابة تلقائية', en: 'Automatic gate' },
  'lp.classification.REQUIRED': { ar: 'مطلوبة', en: 'Required' },
  'lp.classification.OPTIONAL': { ar: 'اختيارية', en: 'Optional' },
  'lp.classification.CONDITIONAL': { ar: 'شرطية', en: 'Conditional' },
  'lp.origin.WORKBOOK': { ar: 'من ملف العمل', en: 'Workbook' },
  'lp.origin.WORKBOOK_HIDDEN': { ar: 'صف مخفي', en: 'Hidden row' },
  'lp.origin.OLD_PROMPT': { ar: 'من وصف الإنتاج', en: 'Production brief' },
  'lp.origin.PROPOSED': { ar: 'مقترح', en: 'Proposal' },
  'lp.origin.WORKBOOK.hint': { ar: 'مأخوذ من ملف "Content Development Checklists".', en: 'Taken from the "Content Development Checklists" workbook.' },
  'lp.origin.WORKBOOK_HIDDEN.hint': { ar: 'مأخوذ من صف مخفي في ملف العمل، وفُعّل كمقترح.', en: 'Taken from a hidden workbook row and activated as a proposal.' },
  'lp.origin.OLD_PROMPT.hint': { ar: 'من وصف مدير الإنتاج الأصلي (مسار ملفات الدروس).', en: 'From the original production-manager brief (the lesson asset pipeline).' },
  'lp.origin.PROPOSED.hint': { ar: 'اقتراح حيث لا يحدد ملف العمل شيئًا — بانتظار اعتماد مالك العمل.', en: 'A proposal where the workbook is silent — pending the business owner.' },
  'lp.origin.row': { ar: 'صف', en: 'Row' },
  'lp.origin.hiddenRow': { ar: 'صف مخفي', en: 'Hidden row' },
  'lp.origin.master': { ar: 'الورقة الرئيسية', en: 'Master sheet' },
  'lp.checkLine.PENDING': { ar: 'لم يُنجز', en: 'Pending' },
  'lp.checkLine.DONE': { ar: 'تم', en: 'Done' },
  'lp.checkLine.ISSUE': { ar: 'مشكلة', en: 'Issue' },
  'lp.checkLine.NOT_APPLICABLE': { ar: 'لا ينطبق', en: 'Not applicable' },
  'lp.issueSeverity.LOW': { ar: 'منخفضة', en: 'Low' },
  'lp.issueSeverity.MEDIUM': { ar: 'متوسطة', en: 'Medium' },
  'lp.issueSeverity.HIGH': { ar: 'عالية', en: 'High' },
  'lp.issueSeverity.CRITICAL': { ar: 'حرجة', en: 'Critical' },
  'lp.issueArea.CONTENT': { ar: 'المحتوى', en: 'Content' },
  'lp.issueArea.OPERATIONS': { ar: 'العمليات', en: 'Operations' },
  'lp.issueArea.PRODUCT': { ar: 'المنتج', en: 'Product' },
  'lp.issueArea.MEDIA': { ar: 'الوسائط', en: 'Media' },
  'lp.issueArea.PLATFORM': { ar: 'المنصة', en: 'Platform' },
  'lp.issueArea.OTHER': { ar: 'أخرى', en: 'Other' },
  'lp.issueStatus.OPEN': { ar: 'مفتوحة', en: 'Open' },
  'lp.issueStatus.IN_PROGRESS': { ar: 'قيد المعالجة', en: 'In progress' },
  'lp.issueStatus.FIXED': { ar: 'أُصلحت · للتحقق', en: 'Fixed — to verify' },
  'lp.issueStatus.VERIFIED': { ar: 'تم التحقق', en: 'Verified' },
  'lp.issueStatus.WONT_FIX': { ar: 'لن تُصلح', en: "Won't fix" },
  'lp.issue.done.start': { ar: 'بدأت معالجة المشكلة.', en: 'Work on the issue started.' },
  'lp.issue.done.fix': { ar: 'سُجل الإصلاح وأُبلغ من أبلغ عنها.', en: 'Fix recorded; the reporter was told.' },
  'lp.issue.done.verify': { ar: 'تم التحقق من الإصلاح.', en: 'Fix verified.' },
  'lp.issue.done.reopen': { ar: 'أُعيد فتح المشكلة.', en: 'Issue reopened.' },
  'lp.issue.done.wont-fix': { ar: 'أُغلقت المشكلة دون إصلاح، والسبب محفوظ.', en: "Closed as won't fix; the reason is kept." },
  'lp.releaseStatus.CANDIDATE': { ar: 'نسخة مرشحة', en: 'Candidate' },
  'lp.releaseStatus.SIGNED_OFF': { ar: 'معتمد — جاهز للنشر', en: 'Signed off' },
  'lp.releaseStatus.PUBLISHED': { ar: 'منشور', en: 'Published' },
  'lp.releaseStatus.SUPERSEDED': { ar: 'حل محله إصدار أحدث', en: 'Superseded' },
  'lp.releaseStatus.ROLLED_BACK': { ar: 'تم التراجع عنه', en: 'Rolled back' },
  'lp.releaseStatus.WITHDRAWN': { ar: 'سُحب', en: 'Withdrawn' },
  'lp.releaseKind.RELEASE': { ar: 'إصدار', en: 'Release' },
  'lp.releaseKind.LEGACY_BASELINE': { ar: 'خط أساس مسجل', en: 'Recorded baseline' },
  'lp.impact.KEEP': { ar: 'يبقى', en: 'Keep' },
  'lp.impact.CHANGE': { ar: 'يتغير', en: 'Change' },
  'lp.impact.REMOVE': { ar: 'يُحذف', en: 'Remove' },
  'lp.candidateStatus.SOURCED': { ar: 'مرشح', en: 'Sourced' },
  'lp.candidateStatus.CONTACTED': { ar: 'تم التواصل', en: 'Contacted' },
  'lp.candidateStatus.SCREENING': { ar: 'فرز أولي', en: 'Screening' },
  'lp.candidateStatus.TECHNICAL_DISCUSSION': { ar: 'مناقشة تقنية', en: 'Technical discussion' },
  'lp.candidateStatus.PASSED': { ar: 'اجتاز', en: 'Passed' },
  'lp.candidateStatus.ONBOARDING': { ar: 'تهيئة', en: 'Onboarding' },
  'lp.candidateStatus.CONTRACTED': { ar: 'متعاقد', en: 'Contracted' },
  'lp.candidateStatus.REJECTED': { ar: 'مرفوض', en: 'Rejected' },
  'lp.candidateStatus.WITHDRAWN': { ar: 'انسحب', en: 'Withdrawn' },
  'lp.candidateSource.LINKEDIN': { ar: 'LinkedIn', en: 'LinkedIn' },
  'lp.candidateSource.APOLLO': { ar: 'Apollo.io', en: 'Apollo.io' },
  'lp.candidateSource.REFERRAL': { ar: 'ترشيح', en: 'Referral' },
  'lp.candidateSource.OTHER': { ar: 'مصدر آخر', en: 'Other' },
  'lp.candidateFile.CV': { ar: 'السيرة الذاتية', en: 'CV' },
  'lp.candidateFile.SAMPLE': { ar: 'عينة', en: 'Sample' },
  'lp.candidateFile.ASSESSMENT': { ar: 'تقييم', en: 'Assessment' },
  'lp.candidateFile.CONTRACT': { ar: 'العقد', en: 'Contract' },
  'lp.candidateFile.OTHER': { ar: 'ملف آخر', en: 'Other' },
  'lp.candidates.score.relevantExperience': { ar: 'الخبرة ذات الصلة', en: 'Relevant experience' },
  'lp.candidates.score.teachingExperience': { ar: 'خبرة التدريس', en: 'Teaching experience' },
  'lp.candidates.score.english': { ar: 'الإنجليزية', en: 'English' },
  'lp.candidates.score.technical': { ar: 'العمق التقني', en: 'Technical depth' },
  'lp.readiness.STAGES_COMPLETE': { ar: 'كل المراحل قبل الإصدار مكتملة', en: 'Every stage before release is done' },
  'lp.readiness.CONTENT_APPROVED': { ar: 'كل ملفات الدروس معتمدة', en: 'Every lesson asset is approved' },
  'lp.readiness.NO_BLOCKING_ISSUES': { ar: 'لا توجد مشكلات عالية أو حرجة مفتوحة', en: 'No high or critical issue is open' },
  'lp.readiness.DEPLOYMENT_VERIFIED': { ar: 'تم التحقق من النشر', en: 'Deployment verified' },
  'lp.readiness.UAT_SIGNED_OFF': { ar: 'اعتُمد اختبار قبول المستخدم', en: 'UAT signed off' },
  'lp.readiness.RELEASE_SIGNED_OFF': { ar: 'اعتُمد الإصدار من شخص آخر', en: 'Release signed off by someone else' },
  'lp.healthReason.TARGET_PASSED': { ar: 'فات الموعد المستهدف ({targetDate})', en: 'The target date ({targetDate}) has passed' },
  'lp.healthReason.MANY_OVERDUE': { ar: '{count} عناصر متأخرة ({share}٪ من العمل المفتوح)', en: '{count} overdue items ({share}% of open work)' },
  'lp.healthReason.SOME_OVERDUE': { ar: '{count} عناصر متأخرة', en: '{count} overdue items' },
  'lp.healthReason.BEHIND_SCHEDULE': { ar: 'أُنجز {actual}٪ من سير العمل والمتوقع حتى الآن {expected}٪', en: '{actual}% of the workflow done, {expected}% expected by now' },
  'lp.healthReason.TARGET_CLOSE': { ar: 'باقٍ {daysLeft} يوم على الموعد والمنجز {actual}٪', en: '{daysLeft} days to target, {actual}% done' },
  'lp.rule.met': { ar: 'تحقق الشرط: {done} من {total}.', en: 'Met: {done} of {total}.' },
  'lp.rule.notMet': { ar: 'لم يتحقق بعد: {done} من {total}.', en: 'Not met yet: {done} of {total}.' },
  'lp.rule.waiting': { ar: 'يُحسب عندما تبدأ هذه المرحلة.', en: 'Checked once this stage begins.' },
  'lp.run.statusChanged.ACTIVE': { ar: 'استُؤنفت دورة الإنتاج.', en: 'The run is active again.' },
  'lp.run.statusChanged.ON_HOLD': { ar: 'أُوقفت دورة الإنتاج مؤقتًا.', en: 'The run is on hold.' },
  'lp.run.statusChanged.CANCELLED': { ar: 'أُلغيت دورة الإنتاج.', en: 'The run was cancelled.' },
  'lp.trace.USED': { ar: 'مستخدم', en: 'Used' },
  'lp.trace.SHEET_FURNITURE': { ar: 'عنوان الورقة', en: 'Sheet heading' },
  'lp.trace.DUPLICATE': { ar: 'مكرر', en: 'Duplicate' },
  'lp.trace.UNTRACED': { ar: 'غير متتبع', en: 'Untraced' },

  /* ── stages ────────────────────────────────────────────────── */
  'lp.stageKey.CHANGE_IMPACT': { ar: 'خط الأساس وأثر التغيير', en: 'Baseline and change impact' },
  'lp.stageKey.AI_INPUT': { ar: 'تجهيز المحتوى المدخل', en: 'Content input' },
  'lp.stageKey.AI_OUTLINES': { ar: 'المخططات', en: 'Outlines' },
  'lp.stageKey.AI_OUTLINE_REVIEW': { ar: 'مراجعة المخططات', en: 'Outline review' },
  'lp.stageKey.RESEARCH': { ar: 'البحث', en: 'Research' },
  'lp.stageKey.CURRICULUM_DRAFT': { ar: 'المسودة الأولى للمنهج', en: 'First draft curriculum' },
  'lp.stageKey.EXPERT_ACQUISITION': { ar: 'استقطاب الخبراء والكوتشز', en: 'Experts and coaches' },
  'lp.stageKey.FINAL_CURRICULUM': { ar: 'التفاصيل النهائية للمنهج', en: 'Final curriculum' },
  'lp.stageKey.AI_SCRIPTS': { ar: 'السكريبتات', en: 'Scripts' },
  'lp.stageKey.AI_SCRIPT_REVIEW': { ar: 'مراجعة السكريبتات', en: 'Script review' },
  'lp.stageKey.AI_SLIDES': { ar: 'الشرائح عبر Docki', en: 'Slides by Docki' },
  'lp.stageKey.AI_VOICE_VIDEO': { ar: 'التعليق الصوتي وفيديو Think', en: 'VO and Think video' },
  'lp.stageKey.AI_VIDEO_REVIEW': { ar: 'مراجعة الفيديوهات', en: 'Video review' },
  'lp.stageKey.AI_COMMENTS_FIX': { ar: 'تنفيذ الملاحظات', en: 'Implement comments' },
  'lp.stageKey.AI_COMMENTS_VERIFY': { ar: 'التحقق من الملاحظات', en: 'Check comments' },
  'lp.stageKey.INSTRUCTIONAL_DESIGN': { ar: 'التصميم التعليمي', en: 'Instructional design' },
  'lp.stageKey.MEDIA_PRODUCTION': { ar: 'إنتاج الوسائط', en: 'Media production' },
  'lp.stageKey.PLATFORM_DEPLOYMENT': { ar: 'النشر على المنصة', en: 'Platform deployment' },
  'lp.stageKey.DRY_RUN_1': { ar: 'التجربة الداخلية الأولى', en: 'First dry run' },
  'lp.stageKey.APPLY_CHANGES': { ar: 'تطبيق التعديلات إن وجدت', en: 'Apply changes, if any' },
  'lp.stageKey.DRY_RUN_FIXES': { ar: 'تطبيق ملاحظات التجربة', en: 'Dry-run fixes' },
  'lp.stageKey.APPLY_DRY_RUN_COMMENTS': { ar: 'تطبيق ملاحظات التجربة', en: 'Apply dry-run comments' },
  'lp.stageKey.REDEPLOYMENT': { ar: 'النشر بعد التعديلات', en: 'Redeployment' },
  'lp.stageKey.DRY_RUN_2': { ar: 'التجربة الداخلية الثانية', en: 'Second dry run' },
  'lp.stageKey.UAT': { ar: 'اختبار قبول المستخدم', en: 'User acceptance test' },
  'lp.stageKey.RELEASE': { ar: 'الإصدار', en: 'Release' },

  /* ── roles (two older labels corrected) ────────────────────── */
  'lp.role.SUBJECT_MATTER_EXPERT': { ar: 'خبير المحتوى / الكوتش', en: 'Subject-matter expert / coach' },
  'lp.role.QUALITY_REVIEWER': { ar: 'مراجع جودة الوسائط والمحتوى', en: 'Media / content QA' },
  'lp.role.RESEARCHER': { ar: 'باحث / مخطط محتوى', en: 'Researcher / content strategist' },
  'lp.role.EXPERT_COORDINATOR': { ar: 'منسق استقطاب الخبراء', en: 'Expert acquisition coordinator' },
  'lp.role.TECHNICAL_PM': { ar: 'مدير المشروع التقني', en: 'Technical PM' },
  'lp.role.DELIVERY_PM': { ar: 'مدير التسليم', en: 'Delivery PM' },
  'lp.role.TECHNICAL_CONSULTANT': { ar: 'الاستشاري التقني', en: 'Technical consultant' },
  'lp.role.LEARNING_OPERATIONS': { ar: 'عمليات التعلم', en: 'Learning operations' },
  'lp.role.MARKETING': { ar: 'التسويق', en: 'Marketing' },
  'lp.role.UAT_COORDINATOR': { ar: 'منسق اختبار القبول', en: 'UAT coordinator' },
  'lp.role.UAT_TESTER': { ar: 'مختبِر قبول', en: 'UAT tester' },

  /* ── refusals ──────────────────────────────────────────────── */
  'lp.error.DEMO_DISABLED': { ar: 'البيانات التجريبية متوقفة في هذه البيئة.', en: 'Demo data is switched off on this deployment.' },
  'lp.error.SERVER_ERROR': { ar: 'حدث خطأ من جهتنا ولم يتغير شيء. حاول مرة أخرى.', en: 'Something went wrong on our side. Nothing was changed. Please try again.' },
  'lp.error.TASK_BLOCKED': { ar: 'هذه المهمة بانتظار انتهاء عمل سابق.', en: 'This task is waiting for earlier work to finish.' },
  'lp.error.EVIDENCE_REQUIRED': { ar: 'أضف الدليل المطلوب لهذه المهمة أولًا.', en: 'Add the evidence this task asks for first.' },
  'lp.error.NEW_EVIDENCE_REQUIRED': { ar: 'أضف دليلًا جديدًا يعالج التعديلات المطلوبة قبل إعادة الإرسال.', en: 'Add new evidence that answers the requested changes before resubmitting.' },
  'lp.error.APPROVAL_REQUIRED': { ar: 'هذا يحتاج اعتمادًا أولًا.', en: 'This needs an approval first.' },
  'lp.error.AUTOMATIC': { ar: 'هذه البوابة تُحسب تلقائيًا ولا تُغير يدويًا.', en: 'This gate is checked automatically.' },
  'lp.error.STAGE_SKIPPED': { ar: 'تم تخطي هذه المرحلة.', en: 'This stage was skipped.' },
  'lp.error.RUN_CLOSED': { ar: 'دورة الإنتاج غير نشطة، فلا يمكن تغيير عملها.', en: 'This run is not active, so its work cannot change.' },
  'lp.error.REQUIRED_TASK': { ar: 'المهمة المطلوبة لا يتخطاها إلا مدير النظام.', en: 'Only an administrator can waive a required task.' },
  'lp.error.RUN_ALREADY_OPEN': { ar: 'لهذا الكورس دورة إنتاج جارية بالفعل.', en: 'This course already has a run in progress.' },
  'lp.error.RELEASE_NOT_READY': { ar: 'الدورة غير جاهزة للإصدار بعد.', en: 'The run is not ready for release yet.' },
  'lp.error.RELEASE_IN_PROGRESS': { ar: 'توجد نسخة إصدار مرشحة بالفعل لهذه الدورة.', en: 'A release candidate for this run is already waiting.' },
  'lp.error.RELEASE_STALE': { ar: 'تغير محتوى معتمد بعد تجهيز هذا الإصدار.', en: 'Approved content changed after this release was prepared.' },
  'lp.error.RELEASE_LABEL_TAKEN': { ar: 'هذا الرقم مستخدم لإصدار آخر للكورس.', en: 'Another release of this course uses this label.' },
  'lp.error.SIGNOFF_REQUIRED': { ar: 'يجب اعتماد الإصدار قبل نشره.', en: 'The release must be signed off before it is published.' },
  'lp.error.STAGE_NOT_SKIPPABLE': { ar: 'لا يمكن تخطي هذه المرحلة.', en: 'This stage cannot be skipped.' },
  'lp.error.IMPACT_LOCKED': { ar: 'اعتُمد أثر التغيير أو طُبق، ولم يعد قابلًا للتعديل.', en: 'The change impact is signed off or applied and can no longer change.' },
  'lp.error.IMPACT_APPLIED': { ar: 'طُبق أثر التغيير بالفعل.', en: 'The change impact was already applied.' },
  'lp.error.LEGACY_RUN': { ar: 'اعتمد سير عمل لهذه الدورة السابقة أولًا.', en: 'Adopt a workflow for this legacy run first.' },
  'lp.error.NOT_APPLICABLE': { ar: 'هذا الملف معلَّم بأنه لا ينطبق.', en: 'This asset is marked not applicable.' },
};

/** History sentences for the run events. {task} and {phase} are template text in the reader's language. */
const ACTIVITY: Record<string, Pair> = {
  'lp.activity.RUN_CREATED': { ar: 'بدأ {actor} دورة إنتاج ({scenario})', en: '{actor} started a production run ({scenario})' },
  'lp.activity.RUN_UPDATED': { ar: 'حدّث {actor} بيانات دورة الإنتاج', en: '{actor} updated the run' },
  'lp.activity.RUN_STATUS_CHANGED': { ar: 'غيّر {actor} حالة دورة الإنتاج', en: '{actor} changed the run status' },
  'lp.activity.TEMPLATE_PUBLISHED': { ar: 'نشر {actor} نسخة جديدة من قالب سير العمل', en: '{actor} published a new template version' },
  'lp.activity.TEMPLATE_ADOPTED': { ar: 'اعتمد {actor} سير عمل ({scenario}) لهذه الدورة', en: '{actor} adopted a workflow ({scenario})' },
  'lp.activity.RUN_MEMBER_ADDED': { ar: 'أضاف {actor} عضوًا لهذه الدورة', en: '{actor} added a member to this run' },
  'lp.activity.RUN_MEMBER_UPDATED': { ar: 'غيّر {actor} أدوار عضو في هذه الدورة', en: '{actor} changed a run member’s roles' },
  'lp.activity.RUN_MEMBER_REMOVED': { ar: 'أزال {actor} عضوًا من هذه الدورة', en: '{actor} removed a run member' },
  'lp.activity.STAGE_COMPLETED': { ar: 'اكتملت مرحلة «{phase}»', en: 'Stage “{phase}” completed' },
  'lp.activity.STAGE_REOPENED': { ar: 'أُعيد فتح مرحلة «{phase}»', en: 'Stage “{phase}” reopened' },
  'lp.activity.STAGE_SKIPPED': { ar: 'تخطى {actor} مرحلة «{phase}»', en: '{actor} skipped “{phase}”' },
  'lp.activity.TASK_ASSIGNED': { ar: 'غيّر {actor} إسناد «{task}»', en: '{actor} changed who holds “{task}”' },
  'lp.activity.TASK_STARTED': { ar: 'بدأ {actor} «{task}»', en: '{actor} started “{task}”' },
  'lp.activity.TASK_CHECKLIST_UPDATED': { ar: 'حدّث {actor} قائمة «{task}»', en: '{actor} updated the checklist of “{task}”' },
  'lp.activity.EVIDENCE_ADDED': { ar: 'أضاف {actor} دليلًا إلى «{task}»', en: '{actor} added evidence to “{task}”' },
  'lp.activity.EVIDENCE_WITHDRAWN': { ar: 'سحب {actor} دليلًا من «{task}»', en: '{actor} withdrew evidence from “{task}”' },
  'lp.activity.TASK_SUBMITTED': { ar: 'أرسل {actor} «{task}» للاعتماد', en: '{actor} sent “{task}” for approval' },
  'lp.activity.TASK_RESUBMITTED': { ar: 'أعاد {actor} إرسال «{task}» بعد التعديل', en: '{actor} resubmitted “{task}”' },
  'lp.activity.TASK_REVIEW_STARTED': { ar: 'بدأ {actor} مراجعة «{task}»', en: '{actor} started reviewing “{task}”' },
  'lp.activity.TASK_CHANGES_REQUESTED': { ar: 'طلب {actor} تعديلات على «{task}»', en: '{actor} requested changes on “{task}”' },
  'lp.activity.TASK_APPROVED': { ar: 'اعتمد {actor} «{task}»', en: '{actor} approved “{task}”' },
  'lp.activity.TASK_COMPLETED': { ar: 'أنجز {actor} «{task}»', en: '{actor} completed “{task}”' },
  'lp.activity.TASK_WAIVED': { ar: 'تخطى {actor} «{task}»', en: '{actor} waived “{task}”' },
  'lp.activity.TASK_REOPENED': { ar: 'أعاد {actor} فتح «{task}»', en: '{actor} reopened “{task}”' },
  'lp.activity.TASK_DEPENDENCY_OVERRIDDEN': { ar: 'تجاوز {actor} انتظار «{task}»', en: '{actor} let “{task}” start early' },
  'lp.activity.TASK_COMMENTED': { ar: 'علّق {actor} على «{task}»', en: '{actor} commented on “{task}”' },
  'lp.activity.ISSUE_REPORTED': { ar: 'سجّل {actor} المشكلة {issue}', en: '{actor} logged issue {issue}' },
  'lp.activity.ISSUE_UPDATED': { ar: 'حدّث {actor} المشكلة {issue}', en: '{actor} updated issue {issue}' },
  'lp.activity.ISSUE_FIXED': { ar: 'أصلح {actor} المشكلة {issue}', en: '{actor} fixed issue {issue}' },
  'lp.activity.ISSUE_VERIFIED': { ar: 'تحقق {actor} من إصلاح المشكلة {issue}', en: '{actor} verified issue {issue}' },
  'lp.activity.ISSUE_REOPENED': { ar: 'أعاد {actor} فتح المشكلة {issue}', en: '{actor} reopened issue {issue}' },
  'lp.activity.ISSUE_WONT_FIX': { ar: 'أغلق {actor} المشكلة {issue} دون إصلاح', en: "{actor} closed issue {issue} as won't fix" },
  'lp.activity.RELEASE_PREPARED': { ar: 'جهّز {actor} الإصدار {release}', en: '{actor} prepared release {release}' },
  'lp.activity.RELEASE_SIGNED_OFF': { ar: 'اعتمد {actor} الإصدار {release}', en: '{actor} signed off release {release}' },
  'lp.activity.RELEASE_PUBLISHED': { ar: 'نشر {actor} الإصدار {release}', en: '{actor} published release {release}' },
  'lp.activity.RELEASE_ROLLED_BACK': { ar: 'تراجع {actor} عن الإصدار {release}', en: '{actor} rolled back release {release}' },
  'lp.activity.RELEASE_WITHDRAWN': { ar: 'سحب {actor} الإصدار {release}', en: '{actor} withdrew release {release}' },
  'lp.activity.IMPACT_RECORDED': { ar: 'سجّل {actor} أثر التغيير', en: '{actor} recorded the change impact' },
  'lp.activity.IMPACT_APPLIED': { ar: 'طبّق {actor} أثر التغيير', en: '{actor} applied the change impact' },
  'lp.activity.CANDIDATE_ADDED': { ar: 'أضاف {actor} مرشحًا', en: '{actor} added a candidate' },
  'lp.activity.CANDIDATE_UPDATED': { ar: 'حدّث {actor} بيانات مرشح', en: '{actor} updated a candidate' },
  'lp.activity.CANDIDATE_FILE_ADDED': { ar: 'أرفق {actor} ملفًا لمرشح', en: '{actor} attached a candidate file' },
  'lp.activity.ASSET_ADDED': { ar: 'أضاف {actor} {stage} إلى الدرس', en: '{actor} added the {stage} to the lesson' },
  'lp.activity.ASSET_NOT_APPLICABLE': { ar: 'علّم {actor} {stage} بأنه لا ينطبق', en: '{actor} marked the {stage} not applicable' },
  'lp.activity.ASSET_APPLICABLE': { ar: 'أعاد {actor} {stage} إلى الدرس', en: '{actor} brought the {stage} back' },
};

import { SCREEN_STRINGS } from './studioScreens';

export const STUDIO_STRINGS: Record<string, Pair> = { ...ENUMS, ...ACTIVITY, ...SCREEN_STRINGS };
