-- Qodo Projects — the metadata engine.
--
-- Fields, layouts, statuses, views, rules and tags are data, not React forms
-- and not switch statements. One engine serves projects, phases, task lists,
-- tasks, issues, users, time logs and custom modules.
--
-- This ships in Phase 1 rather than Phase 7, which is where the original brief
-- put it, and the live audit is why: Zoho Projects "Infinity" (April 2026) is
-- built around custom modules — they carry their own layouts, rules, reports,
-- dashboards and automation, and since June 2026 they can be generated by AI.
-- Writing eight hardcoded modules first and retrofitting a metadata engine
-- underneath them afterwards is the most expensive mistake available here. See
-- ADR-4.
--
-- What this deliberately is *not*: executable. Field types are a closed set,
-- layout-rule conditions and effects are closed vocabularies, and nothing
-- stored here is ever evaluated as code. Executable extension is a separate,
-- sandboxed, quota'd thing (ADR-10) and it is not this.
--
-- Rollback: DROP SCHEMA qodo_projects CASCADE;

SET search_path TO qodo_projects, public;

-- ────────────────────────────────────────────────────────────────────
-- Modules
--
-- The built-ins are rows, not constants, for one concrete reason: Zoho lets an
-- administrator rename Tasks, Issues and Phases organization-wide, and a
-- company that calls them "Deliverables" and "Defects" should see those words
-- everywhere including in reports. A renameable label has to be data.
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE modules (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   text NOT NULL,
  key               text NOT NULL,
  label_ar          text NOT NULL,
  label_en          text NOT NULL,
  plural_ar         text NOT NULL,
  plural_en         text NOT NULL,
  icon              text NOT NULL DEFAULT 'layers',
  color             text NOT NULL DEFAULT '#1D6FB8',
  is_custom         boolean NOT NULL DEFAULT false,
  is_enabled        boolean NOT NULL DEFAULT true,
  -- A custom module is either organization-wide or scoped to one project.
  -- Zoho offers both, and the difference matters: a risk register belongs to a
  -- project, a vendor list belongs to the company.
  project_id        uuid REFERENCES projects(id) ON DELETE CASCADE,
  order_index       int NOT NULL DEFAULT 0,
  created_at        timestamptz NOT NULL DEFAULT now(),
  created_by        text,
  UNIQUE (organization_id, key)
);

CREATE INDEX ON modules (organization_id, is_enabled);
CREATE INDEX ON modules (project_id) WHERE project_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────
-- Statuses
--
-- §32: a retired status must not break the historical records still pointing at
-- it. That is why retiring sets is_active = false and nothing is ever deleted,
-- and why `category` exists — the product needs to know that a company's
-- "Awaiting client sign-off" is a review state without knowing its name.
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE statuses (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  module_id       uuid NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  key             text NOT NULL,
  label_ar        text NOT NULL,
  label_en        text NOT NULL,
  color           text NOT NULL DEFAULT '#64748B',
  category        text NOT NULL DEFAULT 'active'
                    CHECK (category IN ('open', 'active', 'review', 'done', 'cancelled')),
  order_index     int NOT NULL DEFAULT 0,
  is_active       boolean NOT NULL DEFAULT true,
  is_default      boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (module_id, key)
);

CREATE INDEX ON statuses (organization_id, module_id, order_index);
CREATE UNIQUE INDEX ON statuses (module_id) WHERE is_default;

-- ────────────────────────────────────────────────────────────────────
-- Layouts and fields
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE layouts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  module_id       uuid NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  name_ar         text NOT NULL,
  name_en         text NOT NULL,
  is_default      boolean NOT NULL DEFAULT false,
  project_id      uuid REFERENCES projects(id) ON DELETE CASCADE,
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      text
);

CREATE INDEX ON layouts (organization_id, module_id);
CREATE UNIQUE INDEX ON layouts (module_id) WHERE is_default AND project_id IS NULL;

CREATE TABLE layout_sections (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Carried even though the parent layout has it too. §70 asks every protected
  -- entity to hold its own boundary rather than borrow one: a query that joins
  -- through `layouts` is tenant-safe, and the first query that forgets to join
  -- is not.
  organization_id text NOT NULL,
  layout_id   uuid NOT NULL REFERENCES layouts(id) ON DELETE CASCADE,
  label_ar    text NOT NULL,
  label_en    text NOT NULL,
  columns     int NOT NULL DEFAULT 2 CHECK (columns BETWEEN 1 AND 3),
  order_index int NOT NULL DEFAULT 0,
  is_collapsible boolean NOT NULL DEFAULT true
);

CREATE INDEX ON layout_sections (layout_id, order_index);

CREATE TABLE custom_fields (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  module_id       uuid NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  section_id      uuid REFERENCES layout_sections(id) ON DELETE SET NULL,
  key             text NOT NULL,
  label_ar        text NOT NULL,
  label_en        text NOT NULL,

  -- A closed set. Adding a type is a migration *and* a renderer *and* a
  -- validator, together — which is exactly the coupling that stops a field type
  -- from existing in the database with nothing able to display it.
  --
  -- 'summary' aggregates over a related module (Zoho, April 2026) and 'connect'
  -- links records across modules (December 2025); both are computed on read and
  -- never stored in custom_field_values.
  type            text NOT NULL CHECK (type IN (
                    'text', 'textarea', 'richtext', 'integer', 'decimal', 'currency',
                    'percent', 'checkbox', 'select', 'multiselect', 'radio', 'date',
                    'datetime', 'email', 'phone', 'url', 'user', 'multiuser',
                    'lookup', 'summary', 'connect')),

  is_required     boolean NOT NULL DEFAULT false,
  is_system       boolean NOT NULL DEFAULT false,
  default_value   jsonb,
  -- select/radio/multiselect choices; lookup/summary/connect targets.
  options         jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- min, max, pattern, maxLength — checked on the server, never only in React.
  validation      jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- { view: [...permission keys], edit: [...] }. Empty means "whoever may read
  -- the record", which is the safe default only because the record itself is
  -- already authorized before any field is projected.
  permissions     jsonb NOT NULL DEFAULT '{}'::jsonb,
  order_index     int NOT NULL DEFAULT 0,
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      text,
  UNIQUE (module_id, key)
);

CREATE INDEX ON custom_fields (organization_id, module_id) WHERE is_active;
CREATE INDEX ON custom_fields (section_id);

-- The one deliberate EAV table in the schema.
--
-- The alternative — a jsonb column on each entity — cannot be indexed per field,
-- and §33 requires filtering and reporting on custom fields. So: a row per
-- value, indexed both ways, and a functional index on the extracted scalar so
-- "tasks where Risk Level = High" is an index scan rather than a table scan.
CREATE TABLE custom_field_values (
  field_id    uuid NOT NULL REFERENCES custom_fields(id) ON DELETE CASCADE,
  organization_id text NOT NULL,
  entity_type text NOT NULL,
  entity_id   text NOT NULL,
  value       jsonb,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  updated_by  text,
  PRIMARY KEY (field_id, entity_id)
);

CREATE INDEX ON custom_field_values (entity_type, entity_id);
CREATE INDEX ON custom_field_values (field_id, (value #>> '{}'));

-- ────────────────────────────────────────────────────────────────────
-- Layout rules
--
-- New in Zoho during 2025–26, and rolled out module by module (issues first,
-- then tasks, then projects, phases and custom modules). Conditional field
-- behaviour: when Priority is Urgent, require Justification and show the
-- Escalation section.
--
-- Conditions and effects are closed vocabularies evaluated by our own code.
-- Nothing here is executable, and the evaluation happens on the server as well
-- as in the browser — a required field enforced only in React is not enforced.
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE layout_rules (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  layout_id       uuid NOT NULL REFERENCES layouts(id) ON DELETE CASCADE,
  name            text NOT NULL,
  -- [{ field, operator, value }] joined by `match` below.
  conditions      jsonb NOT NULL DEFAULT '[]'::jsonb,
  match           text NOT NULL DEFAULT 'all' CHECK (match IN ('all', 'any')),
  -- [{ effect: show|hide|require|optional|readonly|editable, target }]
  effects         jsonb NOT NULL DEFAULT '[]'::jsonb,
  order_index     int NOT NULL DEFAULT 0,
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON layout_rules (layout_id, order_index) WHERE is_active;

-- ────────────────────────────────────────────────────────────────────
-- Custom views
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE custom_views (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  module_id       uuid NOT NULL REFERENCES modules(id) ON DELETE CASCADE,
  project_id      uuid REFERENCES projects(id) ON DELETE CASCADE,
  name            text NOT NULL,
  -- { match: 'all'|'any', conditions: [{ field, operator, value }] }.
  -- Relative date ranges ('last_7_days', 'this_quarter') are values here rather
  -- than resolved dates, so a saved view keeps meaning what it said.
  criteria        jsonb NOT NULL DEFAULT '{}'::jsonb,
  sort            jsonb NOT NULL DEFAULT '[]'::jsonb,
  group_by        text,
  columns         jsonb NOT NULL DEFAULT '[]'::jsonb,
  visibility      text NOT NULL DEFAULT 'private'
                    CHECK (visibility IN ('private', 'shared', 'project', 'organization')),
  shared_with     jsonb NOT NULL DEFAULT '[]'::jsonb,
  owner_id        text NOT NULL,
  is_default      boolean NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX ON custom_views (organization_id, module_id, owner_id);
CREATE INDEX ON custom_views (project_id) WHERE project_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────
-- Tags
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE tags (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  name            text NOT NULL,
  color           text NOT NULL DEFAULT '#64748B',
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      text,
  UNIQUE (organization_id, name)
);

CREATE TABLE entity_tags (
  tag_id          uuid NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  organization_id text NOT NULL,
  entity_type     text NOT NULL,
  entity_id       text NOT NULL,
  tagged_at       timestamptz NOT NULL DEFAULT now(),
  tagged_by       text,
  PRIMARY KEY (tag_id, entity_type, entity_id)
);

CREATE INDEX ON entity_tags (entity_type, entity_id);

-- ────────────────────────────────────────────────────────────────────
-- Configuration versions — the sandbox (ADR-9)
--
-- §38 asks for a safe place to test layouts, workflows and fields before they
-- reach production. A duplicated environment would mean duplicating storage,
-- users and integrations for a single-tenant deployment, which is cost without
-- matching safety: the risk being managed is "a bad layout reaches everybody",
-- not "a test writes to real data". Versioned draft → publish → rollback buys
-- the same protection.
--
-- The reason this table matters beyond the sandbox: a record remembers the
-- configuration version it was created under, so publishing a new blueprint
-- cannot retroactively invalidate history (§25).
-- ────────────────────────────────────────────────────────────────────

CREATE TABLE config_versions (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id text NOT NULL,
  scope           text NOT NULL,
  version_no      int NOT NULL,
  payload         jsonb NOT NULL,
  state           text NOT NULL DEFAULT 'draft' CHECK (state IN ('draft', 'published', 'superseded')),
  notes           text NOT NULL DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now(),
  created_by      text,
  published_at    timestamptz,
  published_by    text,
  UNIQUE (organization_id, scope, version_no)
);

CREATE INDEX ON config_versions (organization_id, scope, state);

CREATE TRIGGER custom_views_touch BEFORE UPDATE ON custom_views
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
