/**
 * GENERATED by scripts/generate-events-layout-seed.mjs from "SCHEDULE REPORT - 2026.xlsx".
 * Do not edit by hand — regenerate from the workbook.
 *
 * The Events schedule's default structure: departments in sheet order, their
 * packages, optional levels, and each course by its workbook code. The server
 * resolves codes to Odoo event ids; nothing here is read from the workbook at
 * runtime. 135 coded courses, 6 rows or levels skipped (see `skipped`).
 */

export const EVENTS_LAYOUT_SEED = {
  "source": "SCHEDULE REPORT - 2026.xlsx",
  "departments": [
    {
      "department": "Arch & Decor",
      "sheet": "Arch & Decor",
      "packages": [
        {
          "id": "seed:arch:p1",
          "label": "Interior Design Package Online",
          "accent": "blue",
          "courses": [
            {
              "code": "5600",
              "name": "Interior Design Using SketchUp",
              "row": 3,
              "start": "2026-07-26"
            },
            {
              "code": "5601",
              "name": "Photoshop",
              "row": 4,
              "start": "2026-08-25"
            },
            {
              "code": "5602",
              "name": "3D MAX",
              "row": 5,
              "start": "2026-09-06"
            },
            {
              "code": "5605",
              "name": "AutoCad",
              "row": 6,
              "start": "2026-10-11"
            },
            {
              "code": "5669",
              "name": "Interior Design Using SketchUp",
              "row": 7,
              "start": "2026-08-10"
            },
            {
              "code": "5670",
              "name": "Photoshop",
              "row": 8,
              "start": "2026-09-27"
            },
            {
              "code": "5671",
              "name": "3D MAX",
              "row": 9,
              "start": "2026-10-08"
            },
            {
              "code": "5672",
              "name": "AutoCad",
              "row": 10,
              "start": "2026-11-12"
            }
          ],
          "groups": [
            {
              "id": "seed:arch:p1:g1",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5712",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 11,
                  "start": "2026-09-28"
                },
                {
                  "code": "5713",
                  "name": "AI Tools",
                  "row": 12,
                  "start": "2026-10-26"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g2",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5719",
                  "name": "AutoCad",
                  "row": 13,
                  "start": "2026-11-02"
                },
                {
                  "code": "5715",
                  "name": "Interior Design Advanced",
                  "row": 14,
                  "start": "2026-11-18"
                },
                {
                  "code": "5720",
                  "name": "3D MAX & Vray",
                  "row": 15,
                  "start": "2026-11-28"
                },
                {
                  "code": "5721",
                  "name": "Photoshop",
                  "row": 16,
                  "start": "2026-12-30"
                },
                {
                  "code": "5718",
                  "name": "AI Tools Advanced",
                  "row": 17,
                  "start": "2027-01-09"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g3",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5767",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 18,
                  "start": "2026-09-28"
                },
                {
                  "code": "5768",
                  "name": "AI Tools",
                  "row": 19,
                  "start": "2026-11-09"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g4",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5769",
                  "name": "AutoCad",
                  "row": 20,
                  "start": "2026-11-18"
                },
                {
                  "code": "5770",
                  "name": "Interior Design Advanced",
                  "row": 21,
                  "start": "2026-12-14"
                },
                {
                  "code": "5771",
                  "name": "3D MAX & Vray",
                  "row": 22,
                  "start": "2026-12-28"
                },
                {
                  "code": "5772",
                  "name": "Photoshop",
                  "row": 23,
                  "start": "2027-02-15"
                },
                {
                  "code": "5773",
                  "name": "AI Tools Advanced",
                  "row": 24,
                  "start": "2027-03-01"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g5",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5821",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 25,
                  "start": "2026-11-08"
                },
                {
                  "code": "5822",
                  "name": "AI Tools",
                  "row": 26,
                  "start": "2026-12-08"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g6",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5823",
                  "name": "AutoCad",
                  "row": 27,
                  "start": "2026-12-17"
                },
                {
                  "code": "5824",
                  "name": "Interior Design Advanced",
                  "row": 28,
                  "start": "2027-01-05"
                },
                {
                  "code": "5825",
                  "name": "3D MAX & Vray",
                  "row": 29,
                  "start": "2027-01-17"
                },
                {
                  "code": "5826",
                  "name": "Photoshop",
                  "row": 30,
                  "start": "2027-02-21"
                },
                {
                  "code": "5827",
                  "name": "AI Tools Advanced",
                  "row": 31,
                  "start": "2027-03-04"
                }
              ]
            },
            {
              "id": "seed:arch:p1:g7",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5839",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 32,
                  "start": "2026-12-06"
                },
                {
                  "code": "5840",
                  "name": "AI Tools",
                  "row": 33,
                  "start": "2027-01-05"
                }
              ]
            }
          ]
        },
        {
          "id": "seed:arch:p2",
          "label": "Interior Design Package Offline",
          "accent": "violet",
          "courses": [
            {
              "code": "5620",
              "name": "Interior Design Using SketchUp",
              "row": 40,
              "start": "2026-07-20"
            },
            {
              "code": "5621",
              "name": "Photoshop",
              "row": 41,
              "start": "2026-08-12"
            },
            {
              "code": "5622",
              "name": "3D MAX",
              "row": 42,
              "start": "2026-08-22"
            },
            {
              "code": "5623",
              "name": "AutoCad",
              "row": 43,
              "start": "2026-09-19"
            },
            {
              "code": "5627",
              "name": "Interior Design Using SketchUp",
              "row": 44,
              "start": "2026-07-19"
            },
            {
              "code": "5628",
              "name": "Photoshop",
              "row": 45,
              "start": "2026-08-11"
            },
            {
              "code": "5629",
              "name": "3D MAX",
              "row": 46,
              "start": "2026-08-23"
            },
            {
              "code": "5630",
              "name": "AutoCad",
              "row": 47,
              "start": "2026-09-22"
            }
          ],
          "groups": [
            {
              "id": "seed:arch:p2:g1",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5723",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 48,
                  "start": "2026-09-11"
                },
                {
                  "code": "5724",
                  "name": "AI Tools",
                  "row": 49,
                  "start": "2026-10-17"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g2",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5725",
                  "name": "AutoCad",
                  "row": 50,
                  "start": "2026-10-24"
                },
                {
                  "code": "5726",
                  "name": "Interior Design Advanced",
                  "row": 51,
                  "start": "2026-11-14"
                },
                {
                  "code": "5727",
                  "name": "3D MAX & Vray",
                  "row": 52,
                  "start": "2026-11-28"
                },
                {
                  "code": "5728",
                  "name": "Photoshop",
                  "row": 53,
                  "start": "2027-01-09"
                },
                {
                  "code": "5729",
                  "name": "AI Tools Advanced",
                  "row": 54,
                  "start": "2027-01-22"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g3",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5753",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 55,
                  "start": "2026-10-18"
                },
                {
                  "code": "5754",
                  "name": "AI Tools",
                  "row": 56,
                  "start": "2026-11-10"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g4",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5755",
                  "name": "AutoCad",
                  "row": 57,
                  "start": "2026-11-15"
                },
                {
                  "code": "5756",
                  "name": "Interior Design Advanced",
                  "row": 58,
                  "start": "2026-11-29"
                },
                {
                  "code": "5757",
                  "name": "3D MAX & Vray",
                  "row": 59,
                  "start": "2026-12-06"
                },
                {
                  "code": "5758",
                  "name": "Photoshop",
                  "row": 60,
                  "start": "2027-01-03"
                },
                {
                  "code": "5759",
                  "name": "AI Tools Advanced",
                  "row": 61,
                  "start": "2027-01-10"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g5",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5779",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 62,
                  "start": "2026-10-19"
                },
                {
                  "code": "5780",
                  "name": "AI Tools",
                  "row": 63,
                  "start": "2026-11-11"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g6",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5781",
                  "name": "AutoCad",
                  "row": 64,
                  "start": "2026-11-16"
                },
                {
                  "code": "5782",
                  "name": "Interior Design Advanced",
                  "row": 65,
                  "start": "2026-11-30"
                },
                {
                  "code": "5783",
                  "name": "3D MAX & Vray",
                  "row": 66,
                  "start": "2026-12-07"
                },
                {
                  "code": "5784",
                  "name": "Photoshop",
                  "row": 67,
                  "start": "2027-01-04"
                },
                {
                  "code": "5785",
                  "name": "AI Tools Advanced",
                  "row": 68,
                  "start": "2027-01-11"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g7",
              "label": "Interior Design Basic Level",
              "courses": [
                {
                  "code": "5810",
                  "name": "Interior Design Using SketchUp & Canva",
                  "row": 69,
                  "start": "2027-03-19"
                },
                {
                  "code": "5811",
                  "name": "AI Tools",
                  "row": 70,
                  "start": "2027-04-23"
                }
              ]
            },
            {
              "id": "seed:arch:p2:g8",
              "label": "Interior Design Advanced Level",
              "courses": [
                {
                  "code": "5812",
                  "name": "AutoCad",
                  "row": 71,
                  "start": "2027-04-30"
                },
                {
                  "code": "5813",
                  "name": "Interior Design Advanced",
                  "row": 72,
                  "start": "2027-05-21"
                },
                {
                  "code": "5814",
                  "name": "3D MAX & Vray",
                  "row": 73,
                  "start": "2027-05-29"
                },
                {
                  "code": "5815",
                  "name": "Photoshop",
                  "row": 74,
                  "start": "2027-07-10"
                },
                {
                  "code": "5816",
                  "name": "AI Tools Advanced",
                  "row": 75,
                  "start": "2027-07-23"
                }
              ]
            }
          ]
        },
        {
          "id": "seed:arch:p3",
          "label": "BIM Architecture Package",
          "accent": "green",
          "courses": [],
          "groups": [
            {
              "id": "seed:arch:p3:g1",
              "label": "Basic Level",
              "courses": [
                {
                  "code": "5651",
                  "name": "BIM Fundamentals",
                  "row": 77,
                  "start": "2026-08-10"
                },
                {
                  "code": "5652",
                  "name": "Revit Architecture",
                  "row": 78,
                  "start": "2026-08-17"
                }
              ]
            },
            {
              "id": "seed:arch:p3:g2",
              "label": "Advanced Level",
              "courses": [
                {
                  "code": "5653",
                  "name": "Revit Family Creation",
                  "row": 79,
                  "start": "2026-09-19"
                },
                {
                  "code": "5654",
                  "name": "Revit Worksharing",
                  "row": 80,
                  "start": "2026-09-28"
                },
                {
                  "code": "5655",
                  "name": "Navisworks",
                  "row": 81,
                  "start": "2026-09-30"
                }
              ]
            },
            {
              "id": "seed:arch:p3:g3",
              "label": "Basic Level",
              "courses": [
                {
                  "code": "5774",
                  "name": "BIM Fundamentals",
                  "row": 82,
                  "start": "2026-10-10"
                },
                {
                  "code": "5775",
                  "name": "Revit Architecture",
                  "row": 83,
                  "start": "2026-10-14"
                }
              ]
            },
            {
              "id": "seed:arch:p3:g4",
              "label": "Advanced Level",
              "courses": [
                {
                  "code": "5776",
                  "name": "Revit Family Creation",
                  "row": 84,
                  "start": "2026-11-14"
                },
                {
                  "code": "5777",
                  "name": "Revit Worksharing",
                  "row": 85,
                  "start": "2026-11-25"
                },
                {
                  "code": "5778",
                  "name": "Navisworks",
                  "row": 86,
                  "start": "2026-12-05"
                }
              ]
            }
          ]
        },
        {
          "id": "seed:arch:p4",
          "label": "Private Courses",
          "accent": "amber",
          "courses": [],
          "groups": []
        }
      ]
    },
    {
      "department": "Mechanical",
      "sheet": "Mechanical",
      "packages": [
        {
          "id": "seed:mechanical:p1",
          "label": "Mechanical Package",
          "accent": "blue",
          "courses": [
            {
              "code": "5592",
              "name": "HVAC",
              "row": 3,
              "start": "2026-08-15"
            },
            {
              "code": "5593",
              "name": "Fire Fighting",
              "row": 4,
              "start": "2026-09-14"
            },
            {
              "code": "5594",
              "name": "Plumbing",
              "row": 5,
              "start": "2026-10-07"
            },
            {
              "code": "5595",
              "name": "Shop Drawing Mec",
              "row": 6,
              "start": "2026-10-26"
            },
            {
              "code": "5703",
              "name": "HVAC",
              "row": 7,
              "start": "2026-10-18"
            },
            {
              "code": "5704",
              "name": "Fire Fighting",
              "row": 8,
              "start": "2026-11-17"
            },
            {
              "code": "5705",
              "name": "Plumbing",
              "row": 9,
              "start": "2026-12-10"
            },
            {
              "code": "5706",
              "name": "Shop Drawing Mec",
              "row": 10,
              "start": "2026-12-29"
            }
          ],
          "groups": []
        },
        {
          "id": "seed:mechanical:p2",
          "label": "BIM MEP Package",
          "accent": "violet",
          "courses": [],
          "groups": [
            {
              "id": "seed:mechanical:p2:g1",
              "label": "BIM Modeler Basic Level",
              "courses": [
                {
                  "code": "5679",
                  "name": "BIM Fundmentals MEP",
                  "row": 12,
                  "start": "2026-09-12"
                },
                {
                  "code": "5680",
                  "name": "Revit MEP",
                  "row": 13,
                  "start": "2026-09-16"
                }
              ]
            },
            {
              "id": "seed:mechanical:p2:g2",
              "label": "BIM Coordinator Advanced Level",
              "courses": [
                {
                  "code": "5681",
                  "name": "Revit Family Creation MEP",
                  "row": 14,
                  "start": "2026-10-10"
                },
                {
                  "code": "5682",
                  "name": "Revit Worksharing MEP",
                  "row": 15,
                  "start": "2026-10-17"
                },
                {
                  "code": "5683",
                  "name": "Navisworks MEP",
                  "row": 16,
                  "start": "2026-10-21"
                }
              ]
            },
            {
              "id": "seed:mechanical:p2:g3",
              "label": "BIM Modeler Basic Level",
              "courses": [
                {
                  "code": "5788",
                  "name": "BIM Fundmentals MEP",
                  "row": 17,
                  "start": "2026-11-14"
                },
                {
                  "code": "5789",
                  "name": "Revit MEP",
                  "row": 18,
                  "start": "2026-11-18"
                }
              ]
            },
            {
              "id": "seed:mechanical:p2:g4",
              "label": "BIM Coordinator Advanced Level",
              "courses": [
                {
                  "code": "5790",
                  "name": "Revit Family Creation MEP",
                  "row": 19,
                  "start": "2026-12-12"
                },
                {
                  "code": "5791",
                  "name": "Revit Worksharing MEP",
                  "row": 20,
                  "start": "2026-12-19"
                },
                {
                  "code": "5792",
                  "name": "Navisworks MEP",
                  "row": 21,
                  "start": "2026-12-21"
                }
              ]
            }
          ]
        },
        {
          "id": "seed:mechanical:p3",
          "label": "Automotive Package Offline",
          "accent": "green",
          "courses": [
            {
              "code": "5748",
              "name": "Automotive Mechanicals & Electrical",
              "row": 23,
              "start": "2026-09-08"
            },
            {
              "code": "5749",
              "name": "Automotive Mechanicals & Electrical",
              "row": 24,
              "start": "2026-10-11"
            },
            {
              "code": "5750",
              "name": "Automotive Mechanicals & Electrical",
              "row": 25,
              "start": "2026-11-08"
            },
            {
              "code": "5751",
              "name": "Automotive Mechanicals & Electrical",
              "row": 26,
              "start": "2027-01-03"
            }
          ],
          "groups": []
        },
        {
          "id": "seed:mechanical:p4",
          "label": "Companies Courses",
          "accent": "amber",
          "courses": [
            {
              "code": "5800",
              "name": "Plumbing",
              "row": 28,
              "start": "2026-09-06",
              "badge": "Mechanical Package"
            },
            {
              "code": "5802",
              "name": "BIM MEP - English - MOUSA Company",
              "row": 29,
              "start": null,
              "badge": "BIM MEP"
            }
          ],
          "groups": []
        }
      ]
    },
    {
      "department": "Electrical",
      "sheet": "Electrical",
      "packages": [
        {
          "id": "seed:electrical:p1",
          "label": "Electrical Package",
          "accent": "blue",
          "courses": [
            {
              "code": "5580",
              "name": "Lighting",
              "row": 3,
              "start": "2026-07-18"
            },
            {
              "code": "5581",
              "name": "Power",
              "row": 4,
              "start": "2026-07-29"
            },
            {
              "code": "5582",
              "name": "Light Current",
              "row": 5,
              "start": "2026-09-02"
            },
            {
              "code": "5583",
              "name": "Shop Drawing Elec",
              "row": 6,
              "start": "2026-09-23"
            },
            {
              "code": "5685",
              "name": "Lighting",
              "row": 7,
              "start": "2026-09-27"
            },
            {
              "code": "5686",
              "name": "Power",
              "row": 8,
              "start": "2026-10-08"
            },
            {
              "code": "5687",
              "name": "Light Current",
              "row": 9,
              "start": "2026-11-05"
            },
            {
              "code": "5688",
              "name": "Shop Drawing Elec",
              "row": 10,
              "start": "2026-11-26"
            },
            {
              "code": "5828",
              "name": "Lighting",
              "row": 11,
              "start": "2026-11-28"
            },
            {
              "code": "5829",
              "name": "Power",
              "row": 12,
              "start": "2026-12-09"
            },
            {
              "code": "5830",
              "name": "Light Current",
              "row": 13,
              "start": "2027-01-06"
            },
            {
              "code": "5831",
              "name": "Shop Drawing Elec",
              "row": 14,
              "start": "2027-01-27"
            }
          ],
          "groups": []
        },
        {
          "id": "seed:electrical:p2",
          "label": "Companies Courses",
          "accent": "violet",
          "courses": [],
          "groups": []
        }
      ]
    },
    {
      "department": "Civil",
      "sheet": "Civil",
      "packages": [
        {
          "id": "seed:civil:p1",
          "label": "BIM Structure Package",
          "accent": "blue",
          "courses": [],
          "groups": [
            {
              "id": "seed:civil:p1:g1",
              "label": "Basic Level",
              "courses": [
                {
                  "code": "5689",
                  "name": "BIM Fundamentals Structure",
                  "row": 3,
                  "start": "2026-10-03"
                },
                {
                  "code": "5690",
                  "name": "Revit Structure",
                  "row": 4,
                  "start": "2026-10-07"
                }
              ]
            },
            {
              "id": "seed:civil:p1:g2",
              "label": "Advanced Level",
              "courses": [
                {
                  "code": "5691",
                  "name": "Revit Family Creation",
                  "row": 5,
                  "start": "2026-11-02"
                },
                {
                  "code": "5692",
                  "name": "Revit Worksharing",
                  "row": 6,
                  "start": "2026-11-11"
                },
                {
                  "code": "5693",
                  "name": "Navisworks Structure",
                  "row": 7,
                  "start": "2026-11-16"
                }
              ]
            },
            {
              "id": "seed:civil:p1:g3",
              "label": "Basic Level",
              "courses": [
                {
                  "code": "5834",
                  "name": "BIM Fundamentals Structure",
                  "row": 8,
                  "start": "2026-12-01"
                },
                {
                  "code": "5835",
                  "name": "Revit Structure",
                  "row": 9,
                  "start": "2026-12-06"
                }
              ]
            },
            {
              "id": "seed:civil:p1:g4",
              "label": "Advanced Level",
              "courses": [
                {
                  "code": "5836",
                  "name": "Revit Family Creation",
                  "row": 10,
                  "start": "2026-12-31"
                },
                {
                  "code": "5837",
                  "name": "Revit Worksharing",
                  "row": 11,
                  "start": "2027-01-10"
                },
                {
                  "code": "5838",
                  "name": "Navisworks Structure",
                  "row": 12,
                  "start": "2027-01-14"
                }
              ]
            }
          ]
        },
        {
          "id": "seed:civil:p2",
          "label": "Companies Courses",
          "accent": "violet",
          "courses": [],
          "groups": []
        }
      ]
    },
    {
      "department": "Development",
      "sheet": "Development",
      "packages": [
        {
          "id": "seed:development:p1",
          "label": "Management Courses",
          "accent": "blue",
          "courses": [
            {
              "code": "5675",
              "name": "PMP",
              "row": 3,
              "start": "2026-08-16"
            },
            {
              "code": "5742",
              "name": "PMP",
              "row": 4,
              "start": "2026-09-12"
            },
            {
              "code": "5798",
              "name": "PMP",
              "row": 5,
              "start": "2026-10-13"
            },
            {
              "code": "5743",
              "name": "PMP",
              "row": 6,
              "start": "2026-11-29"
            },
            {
              "code": "5711",
              "name": "PRIMAVERA",
              "row": 7,
              "start": "2026-10-18"
            },
            {
              "code": "5832",
              "name": "PRIMAVERA",
              "row": 8,
              "start": "2026-12-29"
            },
            {
              "code": "5674",
              "name": "CFM",
              "row": 9,
              "start": "2026-08-11"
            },
            {
              "code": "5744",
              "name": "CFM",
              "row": 10,
              "start": "2026-10-04"
            },
            {
              "code": "5745",
              "name": "CFM",
              "row": 11,
              "start": "2026-12-05"
            },
            {
              "code": "5678",
              "name": "CMRP",
              "row": 12,
              "start": "2026-08-23"
            },
            {
              "code": "5801",
              "name": "CMRP",
              "row": 13,
              "start": "2026-10-17"
            }
          ],
          "groups": []
        },
        {
          "id": "seed:development:p2",
          "label": "Companies Courses",
          "accent": "violet",
          "courses": [
            {
              "code": "5376",
              "name": "CMRP & PMP - شركة المرافق",
              "row": 15,
              "start": "2025-02-11",
              "badge": "Management Courses Companies"
            }
          ],
          "groups": []
        }
      ]
    },
    {
      "department": "English",
      "sheet": "English Current Round",
      "packages": []
    },
    {
      "department": "Webinar",
      "sheet": "Webinar",
      "packages": []
    }
  ],
  "skipped": [
    {
      "sheet": "Arch & Decor",
      "row": 34,
      "name": "AutoCad",
      "reason": "no course code"
    },
    {
      "sheet": "Arch & Decor",
      "row": 35,
      "name": "Interior Design Advanced",
      "reason": "no course code"
    },
    {
      "sheet": "Arch & Decor",
      "row": 36,
      "name": "3D MAX & Vray",
      "reason": "no course code"
    },
    {
      "sheet": "Arch & Decor",
      "row": 37,
      "name": "Photoshop",
      "reason": "no course code"
    },
    {
      "sheet": "Arch & Decor",
      "row": 38,
      "name": "AI Tools Advanced",
      "reason": "no course code"
    },
    {
      "sheet": "Arch & Decor",
      "group": "Interior Design Advanced Level",
      "package": "Interior Design Package Online",
      "reason": "level with no coded courses"
    }
  ]
};
