/**
 * Pure scheduling rules for the HR operating catalogue.
 *
 * The spreadsheet mixes two kinds of work:
 *   - calendar obligations (daily, Sunday, month-end, quarter-end)
 *   - event obligations (a new hire arrived, a course ended, a legal date was set)
 *
 * Only the first kind may be generated by a clock. Event work is deliberately
 * marked `event` so a scheduler never invents an employee, course or deadline.
 */

const EVENT_DRIVEN_IDS = new Set([
  'hr-013', // a new employee joined
  'hr-014',
  'hr-015',
  'hr-024', // depends on the authority's legal filing date
  'hr-034', // only while a training programme is running
  'hr-036', // after a course ends
  'hr-046', // after the evaluation cycle closes
]);

const pad = (value) => String(value).padStart(2, '0');
const iso = (date) =>
  `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())}`;
const at = (value) => new Date(`${value}T00:00:00Z`);
const addCalendarDays = (value, amount) => {
  const date = at(value);
  date.setUTCDate(date.getUTCDate() + amount);
  return iso(date);
};
const monthKey = (year, month) => `${year}-${pad(month + 1)}`;

export function normaliseWorkingDays(days) {
  const valid = Array.isArray(days)
    ? [...new Set(days.map(Number).filter((day) => Number.isInteger(day) && day >= 0 && day <= 6))]
    : [];
  return valid.length ? valid : [0, 1, 2, 3, 4];
}

export function isWorkingDate(value, workingDays = [0, 1, 2, 3, 4]) {
  return normaliseWorkingDays(workingDays).includes(at(value).getUTCDay());
}

export function addWorkingDays(value, amount, workingDays = [0, 1, 2, 3, 4]) {
  if (!amount) return value;
  const direction = amount > 0 ? 1 : -1;
  let left = Math.abs(amount);
  let cursor = value;
  while (left > 0) {
    cursor = addCalendarDays(cursor, direction);
    if (isWorkingDate(cursor, workingDays)) left -= 1;
  }
  return cursor;
}

function workingOnOrBefore(value, workingDays) {
  let cursor = value;
  while (!isWorkingDate(cursor, workingDays)) cursor = addCalendarDays(cursor, -1);
  return cursor;
}

function workingOnOrAfter(value, workingDays) {
  let cursor = value;
  while (!isWorkingDate(cursor, workingDays)) cursor = addCalendarDays(cursor, 1);
  return cursor;
}

function lastCalendarDay(year, month) {
  return iso(new Date(Date.UTC(year, month + 1, 0)));
}

function scheduledWindow(key, taskDate, dueDate) {
  return { key, taskDate, dueDate };
}

function dateInside(value, window) {
  return value >= window.taskDate && value <= window.dueDate;
}

function arabicWorkingDayOffset(rule, fallback = 5) {
  const numeric = rule.match(/خلال\s+(\d+)\s+أيام?\s+عمل/);
  if (numeric) return Math.max(1, Number(numeric[1]));
  if (/خلال\s+يومي\s+عمل/.test(rule)) return 2;
  if (/خلال\s+أسبوعين/.test(rule)) return 10;
  if (/خلال\s+أسبوع/.test(rule)) return 5;
  return fallback;
}

function weeklyDueDay(rule) {
  if (rule.includes('أحد')) return 0;
  if (rule.includes('خميس')) return 4;
  return null;
}

function monthlyWindows(template, year, month, workingDays) {
  const key = monthKey(year, month);
  const id = template.id;

  // Payroll is anchored to the 27th in the supplied policy.
  const rawPayrollDay = `${key}-27`;
  const payrollDay = workingOnOrBefore(rawPayrollDay, workingDays);
  if (id === 'hr-011') {
    return [scheduledWindow(key, addWorkingDays(payrollDay, -5, workingDays), payrollDay)];
  }
  if (id === 'hr-012') {
    const due = addWorkingDays(payrollDay, -3, workingDays);
    return [scheduledWindow(key, addWorkingDays(due, -3, workingDays), due)];
  }
  if (id === 'hr-021') {
    const start = addWorkingDays(payrollDay, 1, workingDays);
    return [scheduledWindow(key, start, addWorkingDays(payrollDay, 2, workingDays))];
  }

  const end = lastCalendarDay(year, month);
  const lastWorkday = workingOnOrBefore(end, workingDays);
  if (id === 'hr-023') {
    return [scheduledWindow(key, addWorkingDays(lastWorkday, -2, workingDays), lastWorkday)];
  }
  if (id === 'hr-045') {
    const lastWeekStarts = addCalendarDays(end, -6);
    return [scheduledWindow(key, workingOnOrAfter(lastWeekStarts, workingDays), lastWorkday)];
  }

  // Reports described as "after month-end" belong to the month that closed,
  // but their working window lives at the beginning of the following month.
  const start = workingOnOrAfter(addCalendarDays(end, 1), workingDays);
  const allowance = arabicWorkingDayOffset(template.dueRule, 5);
  return [scheduledWindow(key, start, addWorkingDays(start, allowance - 1, workingDays))];
}

function quarterlyWindow(template, year, quarter, workingDays) {
  const endMonth = quarter * 3 + 2;
  const end = lastCalendarDay(year, endMonth);
  const start = workingOnOrAfter(addCalendarDays(end, 1), workingDays);
  const allowance = arabicWorkingDayOffset(template.dueRule, 5);
  return scheduledWindow(
    `${year}-Q${quarter + 1}`,
    start,
    addWorkingDays(start, allowance - 1, workingDays)
  );
}

export function hrScheduleForTemplate(template) {
  if (!template || EVENT_DRIVEN_IDS.has(template.id)) {
    return {
      mode: 'event',
      labelAr: 'حسب وقوع الحدث',
      labelEn: 'Triggered by an event',
    };
  }
  return {
    mode: 'scheduled',
    labelAr: template.dueRule,
    labelEn: template.frequency === 'daily'
      ? 'Every working day'
      : template.frequency === 'weekly'
        ? 'Weekly calendar rule'
        : template.frequency === 'semi_monthly'
          ? 'Twice-monthly calendar rule'
          : template.frequency === 'monthly'
            ? 'Monthly calendar rule'
            : 'Quarterly calendar rule',
  };
}

/**
 * Return the one occurrence whose creation window contains `onDate`.
 * Repeated calls return the same key, which is the scheduler's idempotency key.
 */
export function hrOccurrenceForDate(template, onDate, workingDays = [0, 1, 2, 3, 4]) {
  if (!/^\d{4}-\d{2}-\d{2}$/.test(String(onDate || ''))) return null;
  if (hrScheduleForTemplate(template).mode !== 'scheduled') return null;
  const days = normaliseWorkingDays(workingDays);
  if (!isWorkingDate(onDate, days)) return null;
  const date = at(onDate);

  if (template.frequency === 'daily') {
    return scheduledWindow(onDate, onDate, onDate);
  }

  if (template.frequency === 'weekly') {
    const dueDay = weeklyDueDay(template.dueRule);
    if (dueDay === null) return null;
    const currentDay = date.getUTCDay();
    const untilDue = (dueDay - currentDay + 7) % 7;
    const rawDue = addCalendarDays(onDate, untilDue);
    const due = workingOnOrBefore(rawDue, days);
    const weekSunday = addCalendarDays(rawDue, -at(rawDue).getUTCDay());
    const start = workingOnOrAfter(weekSunday, days);
    const window = scheduledWindow(due, start, due);
    return dateInside(onDate, window) ? window : null;
  }

  if (template.frequency === 'semi_monthly') {
    const year = date.getUTCFullYear();
    const month = date.getUTCMonth();
    const key = monthKey(year, month);
    const dueDates = [
      workingOnOrBefore(`${key}-15`, days),
      workingOnOrBefore(lastCalendarDay(year, month), days),
    ];
    const windows = dueDates.map((due, index) =>
      scheduledWindow(`${key}-${index + 1}`, addWorkingDays(due, -2, days), due)
    );
    return windows.find((window) => dateInside(onDate, window)) ?? null;
  }

  if (template.frequency === 'monthly') {
    const year = date.getUTCFullYear();
    const month = date.getUTCMonth();
    const previous = month === 0 ? { year: year - 1, month: 11 } : { year, month: month - 1 };
    const candidates = [
      ...monthlyWindows(template, year, month, days),
      ...monthlyWindows(template, previous.year, previous.month, days),
    ];
    return candidates.find((window) => dateInside(onDate, window)) ?? null;
  }

  if (template.frequency === 'quarterly') {
    const year = date.getUTCFullYear();
    const currentQuarter = Math.floor(date.getUTCMonth() / 3);
    const previous = currentQuarter === 0
      ? { year: year - 1, quarter: 3 }
      : { year, quarter: currentQuarter - 1 };
    const candidates = [
      quarterlyWindow(template, year, currentQuarter, days),
      quarterlyWindow(template, previous.year, previous.quarter, days),
    ];
    return candidates.find((window) => dateInside(onDate, window)) ?? null;
  }

  return null;
}

export function hrAutomationSummary(templates) {
  return templates.reduce(
    (summary, template) => {
      const mode = hrScheduleForTemplate(template).mode;
      summary[mode] += 1;
      return summary;
    },
    { scheduled: 0, event: 0 }
  );
}
